/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type CallRoutesCreateAllowedCallerPayloadV2,
    CallRoutesCreateAllowedCallerPayloadV2FromJSON,
    CallRoutesCreateAllowedCallerPayloadV2ToJSON,
} from '../models/CallRoutesCreateAllowedCallerPayloadV2.js';
import {
    type CallRoutesCreateAllowedCallerResultV2,
    CallRoutesCreateAllowedCallerResultV2FromJSON,
    CallRoutesCreateAllowedCallerResultV2ToJSON,
} from '../models/CallRoutesCreateAllowedCallerResultV2.js';
import {
    type CallRoutesCreateOptionPayloadV2,
    CallRoutesCreateOptionPayloadV2FromJSON,
    CallRoutesCreateOptionPayloadV2ToJSON,
} from '../models/CallRoutesCreateOptionPayloadV2.js';
import {
    type CallRoutesCreateOptionResultV2,
    CallRoutesCreateOptionResultV2FromJSON,
    CallRoutesCreateOptionResultV2ToJSON,
} from '../models/CallRoutesCreateOptionResultV2.js';
import {
    type CallRoutesListAllowedCallersResultV2,
    CallRoutesListAllowedCallersResultV2FromJSON,
    CallRoutesListAllowedCallersResultV2ToJSON,
} from '../models/CallRoutesListAllowedCallersResultV2.js';
import {
    type CallRoutesListOptionsResultV2,
    CallRoutesListOptionsResultV2FromJSON,
    CallRoutesListOptionsResultV2ToJSON,
} from '../models/CallRoutesListOptionsResultV2.js';
import {
    type CallRoutesListResultV2,
    CallRoutesListResultV2FromJSON,
    CallRoutesListResultV2ToJSON,
} from '../models/CallRoutesListResultV2.js';
import {
    type CallRoutesShowAllowedCallerResultV2,
    CallRoutesShowAllowedCallerResultV2FromJSON,
    CallRoutesShowAllowedCallerResultV2ToJSON,
} from '../models/CallRoutesShowAllowedCallerResultV2.js';
import {
    type CallRoutesShowOptionResultV2,
    CallRoutesShowOptionResultV2FromJSON,
    CallRoutesShowOptionResultV2ToJSON,
} from '../models/CallRoutesShowOptionResultV2.js';
import {
    type CallRoutesShowResultV2,
    CallRoutesShowResultV2FromJSON,
    CallRoutesShowResultV2ToJSON,
} from '../models/CallRoutesShowResultV2.js';
import {
    type CallRoutesUpdateAllowedCallerPayloadV2,
    CallRoutesUpdateAllowedCallerPayloadV2FromJSON,
    CallRoutesUpdateAllowedCallerPayloadV2ToJSON,
} from '../models/CallRoutesUpdateAllowedCallerPayloadV2.js';
import {
    type CallRoutesUpdateAllowedCallerResultV2,
    CallRoutesUpdateAllowedCallerResultV2FromJSON,
    CallRoutesUpdateAllowedCallerResultV2ToJSON,
} from '../models/CallRoutesUpdateAllowedCallerResultV2.js';
import {
    type CallRoutesUpdateOptionPayloadV2,
    CallRoutesUpdateOptionPayloadV2FromJSON,
    CallRoutesUpdateOptionPayloadV2ToJSON,
} from '../models/CallRoutesUpdateOptionPayloadV2.js';
import {
    type CallRoutesUpdateOptionResultV2,
    CallRoutesUpdateOptionResultV2FromJSON,
    CallRoutesUpdateOptionResultV2ToJSON,
} from '../models/CallRoutesUpdateOptionResultV2.js';
import {
    type CallRoutesUpdatePayloadV2,
    CallRoutesUpdatePayloadV2FromJSON,
    CallRoutesUpdatePayloadV2ToJSON,
} from '../models/CallRoutesUpdatePayloadV2.js';
import {
    type CallRoutesUpdateResultV2,
    CallRoutesUpdateResultV2FromJSON,
    CallRoutesUpdateResultV2ToJSON,
} from '../models/CallRoutesUpdateResultV2.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';

export interface CallRoutesV2CreateAllowedCallerRequest {
    /**
     * The call route to allow this number to call
     */
    call_route_id: string;
    /**
     * 
     */
    body: CallRoutesCreateAllowedCallerPayloadV2;
}

export interface CallRoutesV2CreateOptionRequest {
    /**
     * The call route to add this option to
     */
    call_route_id: string;
    /**
     * 
     */
    body: CallRoutesCreateOptionPayloadV2;
}

export interface CallRoutesV2DestroyAllowedCallerRequest {
    /**
     * The call route's ID
     */
    call_route_id: string;
    /**
     * The allowed caller's ID
     */
    id: string;
}

export interface CallRoutesV2DestroyOptionRequest {
    /**
     * The call route's ID
     */
    call_route_id: string;
    /**
     * The option's ID
     */
    id: string;
}

export interface CallRoutesV2ListRequest {
    /**
     * Integer number of records to return
     */
    page_size?: number;
    /**
     * A call route's ID. This endpoint will return a list of call routes after this ID in relation to the API response order.
     */
    after?: string;
}

export interface CallRoutesV2ListAllowedCallersRequest {
    /**
     * The call route's ID
     */
    call_route_id: string;
}

export interface CallRoutesV2ListOptionsRequest {
    /**
     * The call route's ID
     */
    call_route_id: string;
}

export interface CallRoutesV2ShowRequest {
    /**
     * The call route's ID
     */
    id: string;
}

export interface CallRoutesV2ShowAllowedCallerRequest {
    /**
     * The call route's ID
     */
    call_route_id: string;
    /**
     * The allowed caller's ID
     */
    id: string;
}

export interface CallRoutesV2ShowOptionRequest {
    /**
     * The call route's ID
     */
    call_route_id: string;
    /**
     * The option's ID
     */
    id: string;
}

export interface CallRoutesV2UpdateRequest {
    /**
     * The call route's ID
     */
    id: string;
    /**
     * 
     */
    body: CallRoutesUpdatePayloadV2;
}

export interface CallRoutesV2UpdateAllowedCallerRequest {
    /**
     * The call route's ID
     */
    call_route_id: string;
    /**
     * The allowed caller's ID
     */
    id: string;
    /**
     * 
     */
    body: CallRoutesUpdateAllowedCallerPayloadV2;
}

export interface CallRoutesV2UpdateOptionRequest {
    /**
     * The call route's ID
     */
    call_route_id: string;
    /**
     * The option's ID
     */
    id: string;
    /**
     * 
     */
    body: CallRoutesUpdateOptionPayloadV2;
}

/**
 * 
 */
export class CallRoutesV2Api extends runtime.BaseAPI {

    /**
     * Creates request options for callRoutesV2CreateAllowedCaller without sending the request
     */
    async callRoutesV2CreateAllowedCallerRequestOpts(requestParameters: CallRoutesV2CreateAllowedCallerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2CreateAllowedCaller().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling callRoutesV2CreateAllowedCaller().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/allowed_callers`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CallRoutesCreateAllowedCallerPayloadV2ToJSON(requestParameters['body']),
        };
    }

    /**
     * Allow a number to call this route.
     * CreateAllowedCaller Call Routes V2
     */
    async callRoutesV2CreateAllowedCallerRaw(requestParameters: CallRoutesV2CreateAllowedCallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesCreateAllowedCallerResultV2>> {
        const requestOptions = await this.callRoutesV2CreateAllowedCallerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesCreateAllowedCallerResultV2FromJSON(jsonValue));
    }

    /**
     * Allow a number to call this route.
     * CreateAllowedCaller Call Routes V2
     */
    async callRoutesV2CreateAllowedCaller(requestParameters: CallRoutesV2CreateAllowedCallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesCreateAllowedCallerResultV2> {
        const response = await this.callRoutesV2CreateAllowedCallerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2CreateOption without sending the request
     */
    async callRoutesV2CreateOptionRequestOpts(requestParameters: CallRoutesV2CreateOptionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2CreateOption().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling callRoutesV2CreateOption().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/options`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CallRoutesCreateOptionPayloadV2ToJSON(requestParameters['body']),
        };
    }

    /**
     * Add an option to a call route\'s phone-tree menu.  Callers hear the menu instead of being routed down the route\'s own path, so adding the first option clears that path. Every plan allows a single option. A menu of two or more options is not on every plan, so get in touch if you need one enabled.
     * CreateOption Call Routes V2
     */
    async callRoutesV2CreateOptionRaw(requestParameters: CallRoutesV2CreateOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesCreateOptionResultV2>> {
        const requestOptions = await this.callRoutesV2CreateOptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesCreateOptionResultV2FromJSON(jsonValue));
    }

    /**
     * Add an option to a call route\'s phone-tree menu.  Callers hear the menu instead of being routed down the route\'s own path, so adding the first option clears that path. Every plan allows a single option. A menu of two or more options is not on every plan, so get in touch if you need one enabled.
     * CreateOption Call Routes V2
     */
    async callRoutesV2CreateOption(requestParameters: CallRoutesV2CreateOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesCreateOptionResultV2> {
        const response = await this.callRoutesV2CreateOptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2DestroyAllowedCaller without sending the request
     */
    async callRoutesV2DestroyAllowedCallerRequestOpts(requestParameters: CallRoutesV2DestroyAllowedCallerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2DestroyAllowedCaller().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling callRoutesV2DestroyAllowedCaller().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/allowed_callers/{id}`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stop allowing a number to call this route.  A route that only answers its allowed callers must keep at least one, so turn use_caller_allowlist off before removing the last number.
     * DestroyAllowedCaller Call Routes V2
     */
    async callRoutesV2DestroyAllowedCallerRaw(requestParameters: CallRoutesV2DestroyAllowedCallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.callRoutesV2DestroyAllowedCallerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stop allowing a number to call this route.  A route that only answers its allowed callers must keep at least one, so turn use_caller_allowlist off before removing the last number.
     * DestroyAllowedCaller Call Routes V2
     */
    async callRoutesV2DestroyAllowedCaller(requestParameters: CallRoutesV2DestroyAllowedCallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.callRoutesV2DestroyAllowedCallerRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for callRoutesV2DestroyOption without sending the request
     */
    async callRoutesV2DestroyOptionRequestOpts(requestParameters: CallRoutesV2DestroyOptionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2DestroyOption().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling callRoutesV2DestroyOption().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/options/{id}`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove an option from a call route\'s phone-tree menu.  A route has to route calls somewhere, so give it a path before removing its last option.
     * DestroyOption Call Routes V2
     */
    async callRoutesV2DestroyOptionRaw(requestParameters: CallRoutesV2DestroyOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.callRoutesV2DestroyOptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove an option from a call route\'s phone-tree menu.  A route has to route calls somewhere, so give it a path before removing its last option.
     * DestroyOption Call Routes V2
     */
    async callRoutesV2DestroyOption(requestParameters: CallRoutesV2DestroyOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.callRoutesV2DestroyOptionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for callRoutesV2List without sending the request
     */
    async callRoutesV2ListRequestOpts(requestParameters: CallRoutesV2ListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page_size'] != null) {
            queryParameters['page_size'] = requestParameters['page_size'];
        }

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all call routes for this organisation.
     * List Call Routes V2
     */
    async callRoutesV2ListRaw(requestParameters: CallRoutesV2ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesListResultV2>> {
        const requestOptions = await this.callRoutesV2ListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesListResultV2FromJSON(jsonValue));
    }

    /**
     * List all call routes for this organisation.
     * List Call Routes V2
     */
    async callRoutesV2List(requestParameters: CallRoutesV2ListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesListResultV2> {
        const response = await this.callRoutesV2ListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2ListAllowedCallers without sending the request
     */
    async callRoutesV2ListAllowedCallersRequestOpts(requestParameters: CallRoutesV2ListAllowedCallersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2ListAllowedCallers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/allowed_callers`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the numbers allowed to call a route.
     * ListAllowedCallers Call Routes V2
     */
    async callRoutesV2ListAllowedCallersRaw(requestParameters: CallRoutesV2ListAllowedCallersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesListAllowedCallersResultV2>> {
        const requestOptions = await this.callRoutesV2ListAllowedCallersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesListAllowedCallersResultV2FromJSON(jsonValue));
    }

    /**
     * List the numbers allowed to call a route.
     * ListAllowedCallers Call Routes V2
     */
    async callRoutesV2ListAllowedCallers(requestParameters: CallRoutesV2ListAllowedCallersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesListAllowedCallersResultV2> {
        const response = await this.callRoutesV2ListAllowedCallersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2ListOptions without sending the request
     */
    async callRoutesV2ListOptionsRequestOpts(requestParameters: CallRoutesV2ListOptionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2ListOptions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/options`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List a call route\'s phone-tree options, in the order callers hear them.
     * ListOptions Call Routes V2
     */
    async callRoutesV2ListOptionsRaw(requestParameters: CallRoutesV2ListOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesListOptionsResultV2>> {
        const requestOptions = await this.callRoutesV2ListOptionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesListOptionsResultV2FromJSON(jsonValue));
    }

    /**
     * List a call route\'s phone-tree options, in the order callers hear them.
     * ListOptions Call Routes V2
     */
    async callRoutesV2ListOptions(requestParameters: CallRoutesV2ListOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesListOptionsResultV2> {
        const response = await this.callRoutesV2ListOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2Show without sending the request
     */
    async callRoutesV2ShowRequestOpts(requestParameters: CallRoutesV2ShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling callRoutesV2Show().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show a single call route.
     * Show Call Routes V2
     */
    async callRoutesV2ShowRaw(requestParameters: CallRoutesV2ShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesShowResultV2>> {
        const requestOptions = await this.callRoutesV2ShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesShowResultV2FromJSON(jsonValue));
    }

    /**
     * Show a single call route.
     * Show Call Routes V2
     */
    async callRoutesV2Show(requestParameters: CallRoutesV2ShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesShowResultV2> {
        const response = await this.callRoutesV2ShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2ShowAllowedCaller without sending the request
     */
    async callRoutesV2ShowAllowedCallerRequestOpts(requestParameters: CallRoutesV2ShowAllowedCallerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2ShowAllowedCaller().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling callRoutesV2ShowAllowedCaller().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/allowed_callers/{id}`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show a single allowed caller.
     * ShowAllowedCaller Call Routes V2
     */
    async callRoutesV2ShowAllowedCallerRaw(requestParameters: CallRoutesV2ShowAllowedCallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesShowAllowedCallerResultV2>> {
        const requestOptions = await this.callRoutesV2ShowAllowedCallerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesShowAllowedCallerResultV2FromJSON(jsonValue));
    }

    /**
     * Show a single allowed caller.
     * ShowAllowedCaller Call Routes V2
     */
    async callRoutesV2ShowAllowedCaller(requestParameters: CallRoutesV2ShowAllowedCallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesShowAllowedCallerResultV2> {
        const response = await this.callRoutesV2ShowAllowedCallerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2ShowOption without sending the request
     */
    async callRoutesV2ShowOptionRequestOpts(requestParameters: CallRoutesV2ShowOptionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2ShowOption().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling callRoutesV2ShowOption().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/options/{id}`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show a single phone-tree option.
     * ShowOption Call Routes V2
     */
    async callRoutesV2ShowOptionRaw(requestParameters: CallRoutesV2ShowOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesShowOptionResultV2>> {
        const requestOptions = await this.callRoutesV2ShowOptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesShowOptionResultV2FromJSON(jsonValue));
    }

    /**
     * Show a single phone-tree option.
     * ShowOption Call Routes V2
     */
    async callRoutesV2ShowOption(requestParameters: CallRoutesV2ShowOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesShowOptionResultV2> {
        const response = await this.callRoutesV2ShowOptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2Update without sending the request
     */
    async callRoutesV2UpdateRequestOpts(requestParameters: CallRoutesV2UpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling callRoutesV2Update().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling callRoutesV2Update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CallRoutesUpdatePayloadV2ToJSON(requestParameters['body']),
        };
    }

    /**
     * Replace a call route\'s configuration.  Sending a path retires any phone-tree menu on the route. Send an empty path to keep the menu.
     * Update Call Routes V2
     */
    async callRoutesV2UpdateRaw(requestParameters: CallRoutesV2UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesUpdateResultV2>> {
        const requestOptions = await this.callRoutesV2UpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesUpdateResultV2FromJSON(jsonValue));
    }

    /**
     * Replace a call route\'s configuration.  Sending a path retires any phone-tree menu on the route. Send an empty path to keep the menu.
     * Update Call Routes V2
     */
    async callRoutesV2Update(requestParameters: CallRoutesV2UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesUpdateResultV2> {
        const response = await this.callRoutesV2UpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2UpdateAllowedCaller without sending the request
     */
    async callRoutesV2UpdateAllowedCallerRequestOpts(requestParameters: CallRoutesV2UpdateAllowedCallerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2UpdateAllowedCaller().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling callRoutesV2UpdateAllowedCaller().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling callRoutesV2UpdateAllowedCaller().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/allowed_callers/{id}`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CallRoutesUpdateAllowedCallerPayloadV2ToJSON(requestParameters['body']),
        };
    }

    /**
     * Replace an allowed caller\'s number and label.
     * UpdateAllowedCaller Call Routes V2
     */
    async callRoutesV2UpdateAllowedCallerRaw(requestParameters: CallRoutesV2UpdateAllowedCallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesUpdateAllowedCallerResultV2>> {
        const requestOptions = await this.callRoutesV2UpdateAllowedCallerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesUpdateAllowedCallerResultV2FromJSON(jsonValue));
    }

    /**
     * Replace an allowed caller\'s number and label.
     * UpdateAllowedCaller Call Routes V2
     */
    async callRoutesV2UpdateAllowedCaller(requestParameters: CallRoutesV2UpdateAllowedCallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesUpdateAllowedCallerResultV2> {
        const response = await this.callRoutesV2UpdateAllowedCallerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for callRoutesV2UpdateOption without sending the request
     */
    async callRoutesV2UpdateOptionRequestOpts(requestParameters: CallRoutesV2UpdateOptionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['call_route_id'] == null) {
            throw new runtime.RequiredError(
                'call_route_id',
                'Required parameter "call_route_id" was null or undefined when calling callRoutesV2UpdateOption().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling callRoutesV2UpdateOption().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling callRoutesV2UpdateOption().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/call_routes/{call_route_id}/options/{id}`;
        urlPath = urlPath.replace('{call_route_id}', encodeURIComponent(String(requestParameters['call_route_id'])));
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CallRoutesUpdateOptionPayloadV2ToJSON(requestParameters['body']),
        };
    }

    /**
     * Replace a phone-tree option.  Two live options can\'t share a digit, so moving an option onto a digit the menu already uses is rejected.
     * UpdateOption Call Routes V2
     */
    async callRoutesV2UpdateOptionRaw(requestParameters: CallRoutesV2UpdateOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CallRoutesUpdateOptionResultV2>> {
        const requestOptions = await this.callRoutesV2UpdateOptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CallRoutesUpdateOptionResultV2FromJSON(jsonValue));
    }

    /**
     * Replace a phone-tree option.  Two live options can\'t share a digit, so moving an option onto a digit the menu already uses is rejected.
     * UpdateOption Call Routes V2
     */
    async callRoutesV2UpdateOption(requestParameters: CallRoutesV2UpdateOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CallRoutesUpdateOptionResultV2> {
        const response = await this.callRoutesV2UpdateOptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
