/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type CustomFieldsCreatePayloadV1,
    CustomFieldsCreatePayloadV1FromJSON,
    CustomFieldsCreatePayloadV1ToJSON,
} from '../models/CustomFieldsCreatePayloadV1.js';
import {
    type CustomFieldsCreateResultV1,
    CustomFieldsCreateResultV1FromJSON,
    CustomFieldsCreateResultV1ToJSON,
} from '../models/CustomFieldsCreateResultV1.js';
import {
    type CustomFieldsListResultV1,
    CustomFieldsListResultV1FromJSON,
    CustomFieldsListResultV1ToJSON,
} from '../models/CustomFieldsListResultV1.js';
import {
    type CustomFieldsShowResultV1,
    CustomFieldsShowResultV1FromJSON,
    CustomFieldsShowResultV1ToJSON,
} from '../models/CustomFieldsShowResultV1.js';
import {
    type CustomFieldsUpdatePayloadV1,
    CustomFieldsUpdatePayloadV1FromJSON,
    CustomFieldsUpdatePayloadV1ToJSON,
} from '../models/CustomFieldsUpdatePayloadV1.js';
import {
    type CustomFieldsUpdateResultV1,
    CustomFieldsUpdateResultV1FromJSON,
    CustomFieldsUpdateResultV1ToJSON,
} from '../models/CustomFieldsUpdateResultV1.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';

export interface CustomFieldsV1CreateRequest {
    /**
     * 
     */
    body: CustomFieldsCreatePayloadV1;
}

export interface CustomFieldsV1DeleteRequest {
    /**
     * Unique identifier for the custom field
     */
    id: string;
}

export interface CustomFieldsV1ShowRequest {
    /**
     * Unique identifier for the custom field
     */
    id: string;
}

export interface CustomFieldsV1UpdateRequest {
    /**
     * Unique identifier for the custom field
     */
    id: string;
    /**
     * 
     */
    body: CustomFieldsUpdatePayloadV1;
}

/**
 * customFieldsV1List takes no parameters yet. The argument exists so that the first
 * one the API adds is a new optional field here, not a change to the
 * method's signature. Pass request options as the second argument.
 */
export interface CustomFieldsV1ListRequest {
    [key: string]: never;
}

/**
 * 
 */
export class CustomFieldsV1Api extends runtime.BaseAPI {

    /**
     * Creates request options for customFieldsV1Create without sending the request
     * @deprecated
     */
    async customFieldsV1CreateRequestOpts(requestParameters: CustomFieldsV1CreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling customFieldsV1Create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/custom_fields`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomFieldsCreatePayloadV1ToJSON(requestParameters['body']),
        };
    }

    /**
     * Create a new custom field
     * Create Custom Fields V1
     * @deprecated
     */
    async customFieldsV1CreateRaw(requestParameters: CustomFieldsV1CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldsCreateResultV1>> {
        const requestOptions = await this.customFieldsV1CreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldsCreateResultV1FromJSON(jsonValue));
    }

    /**
     * Create a new custom field
     * Create Custom Fields V1
     * @deprecated
     */
    async customFieldsV1Create(requestParameters: CustomFieldsV1CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldsCreateResultV1> {
        const response = await this.customFieldsV1CreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for customFieldsV1Delete without sending the request
     * @deprecated
     */
    async customFieldsV1DeleteRequestOpts(requestParameters: CustomFieldsV1DeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling customFieldsV1Delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/custom_fields/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a custom field
     * Delete Custom Fields V1
     * @deprecated
     */
    async customFieldsV1DeleteRaw(requestParameters: CustomFieldsV1DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.customFieldsV1DeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a custom field
     * Delete Custom Fields V1
     * @deprecated
     */
    async customFieldsV1Delete(requestParameters: CustomFieldsV1DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.customFieldsV1DeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for customFieldsV1List without sending the request
     * @deprecated
     */
    async customFieldsV1ListRequestOpts(requestParameters: CustomFieldsV1ListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/custom_fields`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all custom fields for an organisation.
     * List Custom Fields V1
     * @deprecated
     */
    async customFieldsV1ListRaw(requestParameters: CustomFieldsV1ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldsListResultV1>> {
        const requestOptions = await this.customFieldsV1ListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldsListResultV1FromJSON(jsonValue));
    }

    /**
     * List all custom fields for an organisation.
     * List Custom Fields V1
     * @deprecated
     */
    async customFieldsV1List(requestParameters: CustomFieldsV1ListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldsListResultV1> {
        const response = await this.customFieldsV1ListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for customFieldsV1Show without sending the request
     * @deprecated
     */
    async customFieldsV1ShowRequestOpts(requestParameters: CustomFieldsV1ShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling customFieldsV1Show().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/custom_fields/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single custom field.
     * Show Custom Fields V1
     * @deprecated
     */
    async customFieldsV1ShowRaw(requestParameters: CustomFieldsV1ShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldsShowResultV1>> {
        const requestOptions = await this.customFieldsV1ShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldsShowResultV1FromJSON(jsonValue));
    }

    /**
     * Get a single custom field.
     * Show Custom Fields V1
     * @deprecated
     */
    async customFieldsV1Show(requestParameters: CustomFieldsV1ShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldsShowResultV1> {
        const response = await this.customFieldsV1ShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for customFieldsV1Update without sending the request
     * @deprecated
     */
    async customFieldsV1UpdateRequestOpts(requestParameters: CustomFieldsV1UpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling customFieldsV1Update().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling customFieldsV1Update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/custom_fields/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CustomFieldsUpdatePayloadV1ToJSON(requestParameters['body']),
        };
    }

    /**
     * Update the details of a custom field
     * Update Custom Fields V1
     * @deprecated
     */
    async customFieldsV1UpdateRaw(requestParameters: CustomFieldsV1UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldsUpdateResultV1>> {
        const requestOptions = await this.customFieldsV1UpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldsUpdateResultV1FromJSON(jsonValue));
    }

    /**
     * Update the details of a custom field
     * Update Custom Fields V1
     * @deprecated
     */
    async customFieldsV1Update(requestParameters: CustomFieldsV1UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldsUpdateResultV1> {
        const response = await this.customFieldsV1UpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
