/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type IncidentTypesListResultV1,
    IncidentTypesListResultV1FromJSON,
    IncidentTypesListResultV1ToJSON,
} from '../models/IncidentTypesListResultV1.js';
import {
    type IncidentTypesShowResultV1,
    IncidentTypesShowResultV1FromJSON,
    IncidentTypesShowResultV1ToJSON,
} from '../models/IncidentTypesShowResultV1.js';

export interface IncidentTypesV1ShowRequest {
    /**
     * Unique identifier for this Incident Type
     */
    id: string;
}

/**
 * incidentTypesV1List takes no parameters yet. The argument exists so that the first
 * one the API adds is a new optional field here, not a change to the
 * method's signature. Pass request options as the second argument.
 */
export interface IncidentTypesV1ListRequest {
    [key: string]: never;
}

/**
 * 
 */
export class IncidentTypesV1Api extends runtime.BaseAPI {

    /**
     * Creates request options for incidentTypesV1List without sending the request
     */
    async incidentTypesV1ListRequestOpts(requestParameters: IncidentTypesV1ListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/incident_types`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all incident types for an organisation.
     * List Incident Types V1
     */
    async incidentTypesV1ListRaw(requestParameters: IncidentTypesV1ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentTypesListResultV1>> {
        const requestOptions = await this.incidentTypesV1ListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentTypesListResultV1FromJSON(jsonValue));
    }

    /**
     * List all incident types for an organisation.
     * List Incident Types V1
     */
    async incidentTypesV1List(requestParameters: IncidentTypesV1ListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentTypesListResultV1> {
        const response = await this.incidentTypesV1ListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for incidentTypesV1Show without sending the request
     */
    async incidentTypesV1ShowRequestOpts(requestParameters: IncidentTypesV1ShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling incidentTypesV1Show().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/incident_types/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single incident type.
     * Show Incident Types V1
     */
    async incidentTypesV1ShowRaw(requestParameters: IncidentTypesV1ShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentTypesShowResultV1>> {
        const requestOptions = await this.incidentTypesV1ShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentTypesShowResultV1FromJSON(jsonValue));
    }

    /**
     * Get a single incident type.
     * Show Incident Types V1
     */
    async incidentTypesV1Show(requestParameters: IncidentTypesV1ShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentTypesShowResultV1> {
        const response = await this.incidentTypesV1ShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
