/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type IncidentParticipantWorkloadsListResultV2,
    IncidentParticipantWorkloadsListResultV2FromJSON,
    IncidentParticipantWorkloadsListResultV2ToJSON,
} from '../models/IncidentParticipantWorkloadsListResultV2.js';

export interface IncidentParticipantWorkloadsV2ListRequest {
    /**
     * Find participant workload for this incident
     */
    incident_id: string;
}

/**
 * 
 */
export class IncidentParticipantWorkloadsV2Api extends runtime.BaseAPI {

    /**
     * Creates request options for incidentParticipantWorkloadsV2List without sending the request
     */
    async incidentParticipantWorkloadsV2ListRequestOpts(requestParameters: IncidentParticipantWorkloadsV2ListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['incident_id'] == null) {
            throw new runtime.RequiredError(
                'incident_id',
                'Required parameter "incident_id" was null or undefined when calling incidentParticipantWorkloadsV2List().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['incident_id'] != null) {
            queryParameters['incident_id'] = requestParameters['incident_id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/incident_participant_workloads`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the participants of an incident with their workload.  We calculate how much time each participant has spent working on the incident, aggregated per participant. Each participant is annotated with their participant type and, if they have left the incident, when they were archived.  Workload is calculated periodically, so values can lag real time and the most recent period may still be filling. The metadata reports the time the figures are calculated up to.  Workload for private incidents is only returned to API keys with the `incident_workloads.view_private` scope.
     * List IncidentParticipantWorkloads V2
     */
    async incidentParticipantWorkloadsV2ListRaw(requestParameters: IncidentParticipantWorkloadsV2ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentParticipantWorkloadsListResultV2>> {
        const requestOptions = await this.incidentParticipantWorkloadsV2ListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentParticipantWorkloadsListResultV2FromJSON(jsonValue));
    }

    /**
     * List the participants of an incident with their workload.  We calculate how much time each participant has spent working on the incident, aggregated per participant. Each participant is annotated with their participant type and, if they have left the incident, when they were archived.  Workload is calculated periodically, so values can lag real time and the most recent period may still be filling. The metadata reports the time the figures are calculated up to.  Workload for private incidents is only returned to API keys with the `incident_workloads.view_private` scope.
     * List IncidentParticipantWorkloads V2
     */
    async incidentParticipantWorkloadsV2List(requestParameters: IncidentParticipantWorkloadsV2ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentParticipantWorkloadsListResultV2> {
        const response = await this.incidentParticipantWorkloadsV2ListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
