/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type IncidentMembershipsCreatePayloadV1,
    IncidentMembershipsCreatePayloadV1FromJSON,
    IncidentMembershipsCreatePayloadV1ToJSON,
} from '../models/IncidentMembershipsCreatePayloadV1.js';
import {
    type IncidentMembershipsCreateResultV1,
    IncidentMembershipsCreateResultV1FromJSON,
    IncidentMembershipsCreateResultV1ToJSON,
} from '../models/IncidentMembershipsCreateResultV1.js';
import {
    type IncidentMembershipsRevokePayloadV1,
    IncidentMembershipsRevokePayloadV1FromJSON,
    IncidentMembershipsRevokePayloadV1ToJSON,
} from '../models/IncidentMembershipsRevokePayloadV1.js';

export interface IncidentMembershipsV1CreateRequest {
    /**
     * 
     */
    body: IncidentMembershipsCreatePayloadV1;
}

export interface IncidentMembershipsV1RevokeRequest {
    /**
     * 
     */
    body: IncidentMembershipsRevokePayloadV1;
}

/**
 * 
 */
export class IncidentMembershipsV1Api extends runtime.BaseAPI {

    /**
     * Creates request options for incidentMembershipsV1Create without sending the request
     */
    async incidentMembershipsV1CreateRequestOpts(requestParameters: IncidentMembershipsV1CreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling incidentMembershipsV1Create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/incident_memberships`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IncidentMembershipsCreatePayloadV1ToJSON(requestParameters['body']),
        };
    }

    /**
     * Makes a user a member of a private incident
     * Create Incident Memberships V1
     */
    async incidentMembershipsV1CreateRaw(requestParameters: IncidentMembershipsV1CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncidentMembershipsCreateResultV1>> {
        const requestOptions = await this.incidentMembershipsV1CreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncidentMembershipsCreateResultV1FromJSON(jsonValue));
    }

    /**
     * Makes a user a member of a private incident
     * Create Incident Memberships V1
     */
    async incidentMembershipsV1Create(requestParameters: IncidentMembershipsV1CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncidentMembershipsCreateResultV1> {
        const response = await this.incidentMembershipsV1CreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for incidentMembershipsV1Revoke without sending the request
     */
    async incidentMembershipsV1RevokeRequestOpts(requestParameters: IncidentMembershipsV1RevokeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling incidentMembershipsV1Revoke().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/incident_memberships/actions/revoke`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IncidentMembershipsRevokePayloadV1ToJSON(requestParameters['body']),
        };
    }

    /**
     * Revoke a user\'s membership of a private incident
     * Revoke Incident Memberships V1
     */
    async incidentMembershipsV1RevokeRaw(requestParameters: IncidentMembershipsV1RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.incidentMembershipsV1RevokeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke a user\'s membership of a private incident
     * Revoke Incident Memberships V1
     */
    async incidentMembershipsV1Revoke(requestParameters: IncidentMembershipsV1RevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.incidentMembershipsV1RevokeRaw(requestParameters, initOverrides);
    }

}
