/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse.js';
import {
    type UtilitiesIPRangesResultV1,
    UtilitiesIPRangesResultV1FromJSON,
    UtilitiesIPRangesResultV1ToJSON,
} from '../models/UtilitiesIPRangesResultV1.js';
import {
    type UtilitiesIdentityResultV1,
    UtilitiesIdentityResultV1FromJSON,
    UtilitiesIdentityResultV1ToJSON,
} from '../models/UtilitiesIdentityResultV1.js';

/**
 * utilitiesV1IPRanges takes no parameters yet. The argument exists so that the first
 * one the API adds is a new optional field here, not a change to the
 * method's signature. Pass request options as the second argument.
 */
export interface UtilitiesV1IPRangesRequest {
    [key: string]: never;
}

/**
 * utilitiesV1Identity takes no parameters yet. The argument exists so that the first
 * one the API adds is a new optional field here, not a change to the
 * method's signature. Pass request options as the second argument.
 */
export interface UtilitiesV1IdentityRequest {
    [key: string]: never;
}

/**
 * utilitiesV1OpenAPIV3 takes no parameters yet. The argument exists so that the first
 * one the API adds is a new optional field here, not a change to the
 * method's signature. Pass request options as the second argument.
 */
export interface UtilitiesV1OpenAPIV3Request {
    [key: string]: never;
}

/**
 * 
 */
export class UtilitiesV1Api extends runtime.BaseAPI {

    /**
     * Creates request options for utilitiesV1IPRanges without sending the request
     */
    async utilitiesV1IPRangesRequestOpts(requestParameters: UtilitiesV1IPRangesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/ip_ranges`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the IP addresses our requests to your systems come from.  Use this to keep a firewall allowlist up to date without watching our documentation. Poll it rather than copying the list once. We give at least two weeks\' notice before our own addresses change. Webhook deliveries come from our provider\'s addresses, so we cannot promise notice on those.  These are the addresses we send from. Do not allowlist them for inbound access: our API is served on different addresses, and those change without notice.
     * IPRanges Utilities V1
     */
    async utilitiesV1IPRangesRaw(requestParameters: UtilitiesV1IPRangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UtilitiesIPRangesResultV1>> {
        const requestOptions = await this.utilitiesV1IPRangesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UtilitiesIPRangesResultV1FromJSON(jsonValue));
    }

    /**
     * List the IP addresses our requests to your systems come from.  Use this to keep a firewall allowlist up to date without watching our documentation. Poll it rather than copying the list once. We give at least two weeks\' notice before our own addresses change. Webhook deliveries come from our provider\'s addresses, so we cannot promise notice on those.  These are the addresses we send from. Do not allowlist them for inbound access: our API is served on different addresses, and those change without notice.
     * IPRanges Utilities V1
     */
    async utilitiesV1IPRanges(requestParameters: UtilitiesV1IPRangesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UtilitiesIPRangesResultV1> {
        const response = await this.utilitiesV1IPRangesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for utilitiesV1Identity without sending the request
     */
    async utilitiesV1IdentityRequestOpts(requestParameters: UtilitiesV1IdentityRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/identity`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Test if your API key is valid, and which roles it has.
     * Identity Utilities V1
     */
    async utilitiesV1IdentityRaw(requestParameters: UtilitiesV1IdentityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UtilitiesIdentityResultV1>> {
        const requestOptions = await this.utilitiesV1IdentityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UtilitiesIdentityResultV1FromJSON(jsonValue));
    }

    /**
     * Test if your API key is valid, and which roles it has.
     * Identity Utilities V1
     */
    async utilitiesV1Identity(requestParameters: UtilitiesV1IdentityRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UtilitiesIdentityResultV1> {
        const response = await this.utilitiesV1IdentityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for utilitiesV1OpenAPIV3 without sending the request
     */
    async utilitiesV1OpenAPIV3RequestOpts(requestParameters: UtilitiesV1OpenAPIV3Request): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/openapiV3.json`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the OpenAPI (v3) definition.
     * OpenAPIV3 Utilities V1
     */
    async utilitiesV1OpenAPIV3Raw(requestParameters: UtilitiesV1OpenAPIV3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.utilitiesV1OpenAPIV3RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Get the OpenAPI (v3) definition.
     * OpenAPIV3 Utilities V1
     */
    async utilitiesV1OpenAPIV3(requestParameters: UtilitiesV1OpenAPIV3Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.utilitiesV1OpenAPIV3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
