/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ActionV1 } from './ActionV1.js';
import {
    ActionV1FromJSON,
    ActionV1FromJSONTyped,
    ActionV1ToJSON,
    ActionV1ToJSONTyped,
} from './ActionV1.js';

/**
 * 
 * @export
 * @interface ActionsShowResultV1
 */
export interface ActionsShowResultV1 {
    /**
     * 
     */
    action: ActionV1;
}

/**
 * Check if a given object implements the ActionsShowResultV1 interface.
 */
export function instanceOfActionsShowResultV1(value: object): value is ActionsShowResultV1 {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function ActionsShowResultV1FromJSON(json: any): ActionsShowResultV1 {
    return ActionsShowResultV1FromJSONTyped(json, false);
}

export function ActionsShowResultV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionsShowResultV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'action': ActionV1FromJSON(json['action']),
    };
}

export function ActionsShowResultV1ToJSON(json: any): ActionsShowResultV1 {
    return ActionsShowResultV1ToJSONTyped(json, false);
}

export function ActionsShowResultV1ToJSONTyped(value?: ActionsShowResultV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': ActionV1ToJSON(value['action']),
    };
}

