/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ActionsCreatePayloadV2
 */
export interface ActionsCreatePayloadV2 {
    /**
     * ID of the user this action is assigned to
     */
    assignee_id?: string;
    /**
     * Description of the action. Supports Markdown.
     */
    description: string;
    /**
     * Unique identifier of the incident the action belongs to
     */
    incident_id: string;
}

/**
 * Check if a given object implements the ActionsCreatePayloadV2 interface.
 */
export function instanceOfActionsCreatePayloadV2(value: object): value is ActionsCreatePayloadV2 {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('incident_id' in value) || value['incident_id'] === undefined) return false;
    return true;
}

export function ActionsCreatePayloadV2FromJSON(json: any): ActionsCreatePayloadV2 {
    return ActionsCreatePayloadV2FromJSONTyped(json, false);
}

export function ActionsCreatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionsCreatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'assignee_id': json['assignee_id'] == null ? undefined : json['assignee_id'],
        'description': json['description'],
        'incident_id': json['incident_id'],
    };
}

export function ActionsCreatePayloadV2ToJSON(json: any): ActionsCreatePayloadV2 {
    return ActionsCreatePayloadV2ToJSONTyped(json, false);
}

export function ActionsCreatePayloadV2ToJSONTyped(value?: ActionsCreatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignee_id': value['assignee_id'],
        'description': value['description'],
        'incident_id': value['incident_id'],
    };
}

