/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UserV2 } from './UserV2.js';
import {
    UserV2FromJSON,
    UserV2FromJSONTyped,
    UserV2ToJSON,
    UserV2ToJSONTyped,
} from './UserV2.js';

/**
 * 
 * @export
 * @interface ActivityEscalationAcknowledgedV2
 */
export interface ActivityEscalationAcknowledgedV2 {
    /**
     * 
     */
    acknowledger?: UserV2;
    /**
     * The escalation that was acknowledged
     */
    escalation_id: string;
}

/**
 * Check if a given object implements the ActivityEscalationAcknowledgedV2 interface.
 */
export function instanceOfActivityEscalationAcknowledgedV2(value: object): value is ActivityEscalationAcknowledgedV2 {
    if (!('escalation_id' in value) || value['escalation_id'] === undefined) return false;
    return true;
}

export function ActivityEscalationAcknowledgedV2FromJSON(json: any): ActivityEscalationAcknowledgedV2 {
    return ActivityEscalationAcknowledgedV2FromJSONTyped(json, false);
}

export function ActivityEscalationAcknowledgedV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityEscalationAcknowledgedV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'acknowledger': json['acknowledger'] == null ? undefined : UserV2FromJSON(json['acknowledger']),
        'escalation_id': json['escalation_id'],
    };
}

export function ActivityEscalationAcknowledgedV2ToJSON(json: any): ActivityEscalationAcknowledgedV2 {
    return ActivityEscalationAcknowledgedV2ToJSONTyped(json, false);
}

export function ActivityEscalationAcknowledgedV2ToJSONTyped(value?: ActivityEscalationAcknowledgedV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acknowledger': UserV2ToJSON(value['acknowledger']),
        'escalation_id': value['escalation_id'],
    };
}

