/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ActorV2 } from './ActorV2.js';
import {
    ActorV2FromJSON,
    ActorV2FromJSONTyped,
    ActorV2ToJSON,
    ActorV2ToJSONTyped,
} from './ActorV2.js';

/**
 * 
 * @export
 * @interface ActivitySummaryUpdateV2
 */
export interface ActivitySummaryUpdateV2 {
    /**
     * The summary after this change, in markdown
     */
    new_summary?: string;
    /**
     * The summary before this change, in markdown
     */
    previous_summary?: string;
    /**
     * 
     */
    updater?: ActorV2;
}

/**
 * Check if a given object implements the ActivitySummaryUpdateV2 interface.
 */
export function instanceOfActivitySummaryUpdateV2(value: object): value is ActivitySummaryUpdateV2 {
    return true;
}

export function ActivitySummaryUpdateV2FromJSON(json: any): ActivitySummaryUpdateV2 {
    return ActivitySummaryUpdateV2FromJSONTyped(json, false);
}

export function ActivitySummaryUpdateV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivitySummaryUpdateV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'new_summary': json['new_summary'] == null ? undefined : json['new_summary'],
        'previous_summary': json['previous_summary'] == null ? undefined : json['previous_summary'],
        'updater': json['updater'] == null ? undefined : ActorV2FromJSON(json['updater']),
    };
}

export function ActivitySummaryUpdateV2ToJSON(json: any): ActivitySummaryUpdateV2 {
    return ActivitySummaryUpdateV2ToJSONTyped(json, false);
}

export function ActivitySummaryUpdateV2ToJSONTyped(value?: ActivitySummaryUpdateV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_summary': value['new_summary'],
        'previous_summary': value['previous_summary'],
        'updater': ActorV2ToJSON(value['updater']),
    };
}

