/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AlertSourceV2 } from './AlertSourceV2.js';
import {
    AlertSourceV2FromJSON,
    AlertSourceV2FromJSONTyped,
    AlertSourceV2ToJSON,
    AlertSourceV2ToJSONTyped,
} from './AlertSourceV2.js';

/**
 * 
 * @export
 * @interface AlertSourcesShowResultV2
 */
export interface AlertSourcesShowResultV2 {
    /**
     * 
     */
    alert_source: AlertSourceV2;
}

/**
 * Check if a given object implements the AlertSourcesShowResultV2 interface.
 */
export function instanceOfAlertSourcesShowResultV2(value: object): value is AlertSourcesShowResultV2 {
    if (!('alert_source' in value) || value['alert_source'] === undefined) return false;
    return true;
}

export function AlertSourcesShowResultV2FromJSON(json: any): AlertSourcesShowResultV2 {
    return AlertSourcesShowResultV2FromJSONTyped(json, false);
}

export function AlertSourcesShowResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertSourcesShowResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'alert_source': AlertSourceV2FromJSON(json['alert_source']),
    };
}

export function AlertSourcesShowResultV2ToJSON(json: any): AlertSourcesShowResultV2 {
    return AlertSourcesShowResultV2ToJSONTyped(json, false);
}

export function AlertSourcesShowResultV2ToJSONTyped(value?: AlertSourcesShowResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_source': AlertSourceV2ToJSON(value['alert_source']),
    };
}

