/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PaginationMetaResultV2 } from './PaginationMetaResultV2.js';
import {
    PaginationMetaResultV2FromJSON,
    PaginationMetaResultV2FromJSONTyped,
    PaginationMetaResultV2ToJSON,
    PaginationMetaResultV2ToJSONTyped,
} from './PaginationMetaResultV2.js';
import type { AlertTagV2 } from './AlertTagV2.js';
import {
    AlertTagV2FromJSON,
    AlertTagV2FromJSONTyped,
    AlertTagV2ToJSON,
    AlertTagV2ToJSONTyped,
} from './AlertTagV2.js';

/**
 * 
 * @export
 * @interface AlertsListAlertTagsResultV2
 */
export interface AlertsListAlertTagsResultV2 {
    /**
     * 
     */
    alert_tags: Array<AlertTagV2>;
    /**
     * 
     */
    pagination_meta: PaginationMetaResultV2;
}

/**
 * Check if a given object implements the AlertsListAlertTagsResultV2 interface.
 */
export function instanceOfAlertsListAlertTagsResultV2(value: object): value is AlertsListAlertTagsResultV2 {
    if (!('alert_tags' in value) || value['alert_tags'] === undefined) return false;
    if (!('pagination_meta' in value) || value['pagination_meta'] === undefined) return false;
    return true;
}

export function AlertsListAlertTagsResultV2FromJSON(json: any): AlertsListAlertTagsResultV2 {
    return AlertsListAlertTagsResultV2FromJSONTyped(json, false);
}

export function AlertsListAlertTagsResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertsListAlertTagsResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'alert_tags': ((json['alert_tags'] as Array<any>).map(AlertTagV2FromJSON)),
        'pagination_meta': PaginationMetaResultV2FromJSON(json['pagination_meta']),
    };
}

export function AlertsListAlertTagsResultV2ToJSON(json: any): AlertsListAlertTagsResultV2 {
    return AlertsListAlertTagsResultV2ToJSONTyped(json, false);
}

export function AlertsListAlertTagsResultV2ToJSONTyped(value?: AlertsListAlertTagsResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_tags': ((value['alert_tags'] as Array<any>).map(AlertTagV2ToJSON)),
        'pagination_meta': PaginationMetaResultV2ToJSON(value['pagination_meta']),
    };
}

