/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AlertTemplatePayloadV2 } from './AlertTemplatePayloadV2.js';
import {
    AlertTemplatePayloadV2FromJSON,
    AlertTemplatePayloadV2FromJSONTyped,
    AlertTemplatePayloadV2ToJSON,
    AlertTemplatePayloadV2ToJSONTyped,
} from './AlertTemplatePayloadV2.js';

/**
 * 
 * @export
 * @interface AlertSourcesValidatePayloadV2
 */
export interface AlertSourcesValidatePayloadV2 {
    /**
     * IDs of teams that own this alert source
     */
    owning_team_ids?: Array<string>;
    /**
     * Type of alert source
     */
    source_type: AlertSourcesValidatePayloadV2SourceTypeEnum;
    /**
     * 
     */
    template: AlertTemplatePayloadV2;
}


/**
 * @export
 */
export const AlertSourcesValidatePayloadV2SourceTypeEnum = {
    Alertmanager: 'alertmanager',
    AppOptics: 'app_optics',
    AzureMonitor: 'azure_monitor',
    AzureDevops: 'azure_devops',
    BigPanda: 'big_panda',
    Bugsnag: 'bugsnag',
    Checkly: 'checkly',
    Chronosphere: 'chronosphere',
    Cloudwatch: 'cloudwatch',
    Cloudflare: 'cloudflare',
    Coralogix: 'coralogix',
    Cronitor: 'cronitor',
    CrowdstrikeFalcon: 'crowdstrike_falcon',
    Dash0: 'dash0',
    Datadog: 'datadog',
    Dynatrace: 'dynatrace',
    Elasticsearch: 'elasticsearch',
    Email: 'email',
    Expel: 'expel',
    GithubIssue: 'github_issue',
    GoogleCloud: 'google_cloud',
    GoogleSecops: 'google_secops',
    Grafana: 'grafana',
    Heartbeat: 'heartbeat',
    Http: 'http',
    HttpCustom: 'http_custom',
    Honeycomb: 'honeycomb',
    Icinga2: 'icinga2',
    IncomingCalls: 'incoming_calls',
    Jira: 'jira',
    Jsm: 'jsm',
    Logzio: 'logzio',
    MonteCarlo: 'monte_carlo',
    Nagios: 'nagios',
    NewRelic: 'new_relic',
    Opsgenie: 'opsgenie',
    Prtg: 'prtg',
    PagerDuty: 'pager_duty',
    Panther: 'panther',
    Pingdom: 'pingdom',
    Posthog: 'posthog',
    Runscope: 'runscope',
    Sns: 'sns',
    SalesforceCase: 'salesforce_case',
    Sentry: 'sentry',
    SentryMetric: 'sentry_metric',
    ServiceNow: 'service_now',
    Splunk: 'splunk',
    StatusCake: 'status_cake',
    StatusPageViews: 'status_page_views',
    SumoLogic: 'sumo_logic',
    Uptime: 'uptime',
    Vercel: 'vercel',
    Wiz: 'wiz',
    Zendesk: 'zendesk',
} as const;
export type AlertSourcesValidatePayloadV2SourceTypeEnum = typeof AlertSourcesValidatePayloadV2SourceTypeEnum[keyof typeof AlertSourcesValidatePayloadV2SourceTypeEnum];


/**
 * Check if a given object implements the AlertSourcesValidatePayloadV2 interface.
 */
export function instanceOfAlertSourcesValidatePayloadV2(value: object): value is AlertSourcesValidatePayloadV2 {
    if (!('source_type' in value) || value['source_type'] === undefined) return false;
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function AlertSourcesValidatePayloadV2FromJSON(json: any): AlertSourcesValidatePayloadV2 {
    return AlertSourcesValidatePayloadV2FromJSONTyped(json, false);
}

export function AlertSourcesValidatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertSourcesValidatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'owning_team_ids': json['owning_team_ids'] == null ? undefined : json['owning_team_ids'],
        'source_type': json['source_type'],
        'template': AlertTemplatePayloadV2FromJSON(json['template']),
    };
}

export function AlertSourcesValidatePayloadV2ToJSON(json: any): AlertSourcesValidatePayloadV2 {
    return AlertSourcesValidatePayloadV2ToJSONTyped(json, false);
}

export function AlertSourcesValidatePayloadV2ToJSONTyped(value?: AlertSourcesValidatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'owning_team_ids': value['owning_team_ids'],
        'source_type': value['source_type'],
        'template': AlertTemplatePayloadV2ToJSON(value['template']),
    };
}

