/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExpressionPayloadV2 } from './ExpressionPayloadV2.js';
import {
    ExpressionPayloadV2FromJSON,
    ExpressionPayloadV2FromJSONTyped,
    ExpressionPayloadV2ToJSON,
    ExpressionPayloadV2ToJSONTyped,
} from './ExpressionPayloadV2.js';
import type { EngineParamBindingPayloadV2 } from './EngineParamBindingPayloadV2.js';
import {
    EngineParamBindingPayloadV2FromJSON,
    EngineParamBindingPayloadV2FromJSONTyped,
    EngineParamBindingPayloadV2ToJSON,
    EngineParamBindingPayloadV2ToJSONTyped,
} from './EngineParamBindingPayloadV2.js';
import type { AlertTemplateAttributePayloadV2 } from './AlertTemplateAttributePayloadV2.js';
import {
    AlertTemplateAttributePayloadV2FromJSON,
    AlertTemplateAttributePayloadV2FromJSONTyped,
    AlertTemplateAttributePayloadV2ToJSON,
    AlertTemplateAttributePayloadV2ToJSONTyped,
} from './AlertTemplateAttributePayloadV2.js';
import type { EngineParamBindingValuePayloadV2 } from './EngineParamBindingValuePayloadV2.js';
import {
    EngineParamBindingValuePayloadV2FromJSON,
    EngineParamBindingValuePayloadV2FromJSONTyped,
    EngineParamBindingValuePayloadV2ToJSON,
    EngineParamBindingValuePayloadV2ToJSONTyped,
} from './EngineParamBindingValuePayloadV2.js';

/**
 * 
 * @export
 * @interface AlertTemplatePayloadV2
 */
export interface AlertTemplatePayloadV2 {
    /**
     * Attributes to set on alerts coming from this source, with a binding describing how to set them.
     */
    attributes: Array<AlertTemplateAttributePayloadV2>;
    /**
     * 
     */
    description: EngineParamBindingValuePayloadV2;
    /**
     * Expressions available for use in bindings within this template
     */
    expressions: Array<ExpressionPayloadV2>;
    /**
     * Whether or not alerts produced by this source should be private
     */
    is_private?: boolean;
    /**
     * 
     */
    title: EngineParamBindingValuePayloadV2;
    /**
     * 
     */
    visible_to_teams?: EngineParamBindingPayloadV2;
}

/**
 * Check if a given object implements the AlertTemplatePayloadV2 interface.
 */
export function instanceOfAlertTemplatePayloadV2(value: object): value is AlertTemplatePayloadV2 {
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('expressions' in value) || value['expressions'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function AlertTemplatePayloadV2FromJSON(json: any): AlertTemplatePayloadV2 {
    return AlertTemplatePayloadV2FromJSONTyped(json, false);
}

export function AlertTemplatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertTemplatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': ((json['attributes'] as Array<any>).map(AlertTemplateAttributePayloadV2FromJSON)),
        'description': EngineParamBindingValuePayloadV2FromJSON(json['description']),
        'expressions': ((json['expressions'] as Array<any>).map(ExpressionPayloadV2FromJSON)),
        'is_private': json['is_private'] == null ? undefined : json['is_private'],
        'title': EngineParamBindingValuePayloadV2FromJSON(json['title']),
        'visible_to_teams': json['visible_to_teams'] == null ? undefined : EngineParamBindingPayloadV2FromJSON(json['visible_to_teams']),
    };
}

export function AlertTemplatePayloadV2ToJSON(json: any): AlertTemplatePayloadV2 {
    return AlertTemplatePayloadV2ToJSONTyped(json, false);
}

export function AlertTemplatePayloadV2ToJSONTyped(value?: AlertTemplatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': ((value['attributes'] as Array<any>).map(AlertTemplateAttributePayloadV2ToJSON)),
        'description': EngineParamBindingValuePayloadV2ToJSON(value['description']),
        'expressions': ((value['expressions'] as Array<any>).map(ExpressionPayloadV2ToJSON)),
        'is_private': value['is_private'],
        'title': EngineParamBindingValuePayloadV2ToJSON(value['title']),
        'visible_to_teams': EngineParamBindingPayloadV2ToJSON(value['visible_to_teams']),
    };
}

