/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EngineParamBindingValuePayloadV2 } from './EngineParamBindingValuePayloadV2.js';
import {
    EngineParamBindingValuePayloadV2FromJSON,
    EngineParamBindingValuePayloadV2FromJSONTyped,
    EngineParamBindingValuePayloadV2ToJSON,
    EngineParamBindingValuePayloadV2ToJSONTyped,
} from './EngineParamBindingValuePayloadV2.js';

/**
 * 
 * @export
 * @interface AlertTemplateAttributeBindingPayloadV2
 */
export interface AlertTemplateAttributeBindingPayloadV2 {
    /**
     * If set, this is the array value of the step parameter
     */
    array_value?: Array<EngineParamBindingValuePayloadV2>;
    /**
     * Merge strategy for this attribute when alert updates
     */
    merge_strategy?: AlertTemplateAttributeBindingPayloadV2MergeStrategyEnum;
    /**
     * 
     */
    value?: EngineParamBindingValuePayloadV2;
}


/**
 * @export
 */
export const AlertTemplateAttributeBindingPayloadV2MergeStrategyEnum = {
    FirstWins: 'first_wins',
    LastWins: 'last_wins',
    Append: 'append',
    Max: 'max',
    Min: 'min',
} as const;
export type AlertTemplateAttributeBindingPayloadV2MergeStrategyEnum = typeof AlertTemplateAttributeBindingPayloadV2MergeStrategyEnum[keyof typeof AlertTemplateAttributeBindingPayloadV2MergeStrategyEnum];


/**
 * Check if a given object implements the AlertTemplateAttributeBindingPayloadV2 interface.
 */
export function instanceOfAlertTemplateAttributeBindingPayloadV2(value: object): value is AlertTemplateAttributeBindingPayloadV2 {
    return true;
}

export function AlertTemplateAttributeBindingPayloadV2FromJSON(json: any): AlertTemplateAttributeBindingPayloadV2 {
    return AlertTemplateAttributeBindingPayloadV2FromJSONTyped(json, false);
}

export function AlertTemplateAttributeBindingPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertTemplateAttributeBindingPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'array_value': json['array_value'] == null ? undefined : ((json['array_value'] as Array<any>).map(EngineParamBindingValuePayloadV2FromJSON)),
        'merge_strategy': json['merge_strategy'] == null ? undefined : json['merge_strategy'],
        'value': json['value'] == null ? undefined : EngineParamBindingValuePayloadV2FromJSON(json['value']),
    };
}

export function AlertTemplateAttributeBindingPayloadV2ToJSON(json: any): AlertTemplateAttributeBindingPayloadV2 {
    return AlertTemplateAttributeBindingPayloadV2ToJSONTyped(json, false);
}

export function AlertTemplateAttributeBindingPayloadV2ToJSONTyped(value?: AlertTemplateAttributeBindingPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'array_value': value['array_value'] == null ? undefined : ((value['array_value'] as Array<any>).map(EngineParamBindingValuePayloadV2ToJSON)),
        'merge_strategy': value['merge_strategy'],
        'value': EngineParamBindingValuePayloadV2ToJSON(value['value']),
    };
}

