/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EngineParamBindingPayloadV3 } from './EngineParamBindingPayloadV3.js';
import {
    EngineParamBindingPayloadV3FromJSON,
    EngineParamBindingPayloadV3FromJSONTyped,
    EngineParamBindingPayloadV3ToJSON,
    EngineParamBindingPayloadV3ToJSONTyped,
} from './EngineParamBindingPayloadV3.js';

/**
 * 
 * @export
 * @interface AlertRouteAutoGeneratedTemplateBindingPayloadV3
 */
export interface AlertRouteAutoGeneratedTemplateBindingPayloadV3 {
    /**
     * Whether this attribute is autogenerated using AI or not
     */
    autogenerated?: boolean;
    /**
     * 
     */
    binding?: EngineParamBindingPayloadV3;
}

/**
 * Check if a given object implements the AlertRouteAutoGeneratedTemplateBindingPayloadV3 interface.
 */
export function instanceOfAlertRouteAutoGeneratedTemplateBindingPayloadV3(value: object): value is AlertRouteAutoGeneratedTemplateBindingPayloadV3 {
    return true;
}

export function AlertRouteAutoGeneratedTemplateBindingPayloadV3FromJSON(json: any): AlertRouteAutoGeneratedTemplateBindingPayloadV3 {
    return AlertRouteAutoGeneratedTemplateBindingPayloadV3FromJSONTyped(json, false);
}

export function AlertRouteAutoGeneratedTemplateBindingPayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertRouteAutoGeneratedTemplateBindingPayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'autogenerated': json['autogenerated'] == null ? undefined : json['autogenerated'],
        'binding': json['binding'] == null ? undefined : EngineParamBindingPayloadV3FromJSON(json['binding']),
    };
}

export function AlertRouteAutoGeneratedTemplateBindingPayloadV3ToJSON(json: any): AlertRouteAutoGeneratedTemplateBindingPayloadV3 {
    return AlertRouteAutoGeneratedTemplateBindingPayloadV3ToJSONTyped(json, false);
}

export function AlertRouteAutoGeneratedTemplateBindingPayloadV3ToJSONTyped(value?: AlertRouteAutoGeneratedTemplateBindingPayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'autogenerated': value['autogenerated'],
        'binding': EngineParamBindingPayloadV3ToJSON(value['binding']),
    };
}

