/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface AlertSlimV2
 */
export interface AlertSlimV2 {
    /**
     * The IDs of every alert group this alert belongs to. Empty when the alert is not part of any group.
     */
    alert_group_ids?: Array<string>;
    /**
     * The ID of the alert source this alert fired on
     */
    alert_source_id: string;
    /**
     * When this entry was created
     */
    created_at: Date;
    /**
     * A deduplication key which uniquely references this alert from your alert source. For newly created HTTP sources, this field is required.
     * If you send an event with the same deduplication_key multiple times, only one alert will be created in incident.io for this alert source config.
     * You can filter on this field to find the alert created by an event you've sent us.
     */
    deduplication_key: string;
    /**
     * The description of the alert
     */
    description?: string;
    /**
     * The ID of this alert
     */
    id: string;
    /**
     * When this alert was resolved
     */
    resolved_at?: Date;
    /**
     * If applicable, a link to the alert in the upstream system
     */
    source_url?: string;
    /**
     * Statuses of an alert
     */
    status: AlertSlimV2StatusEnum;
    /**
     * The title of the alert, parsed from the alert payload according to the alert source configuration
     */
    title: string;
    /**
     * When this alert was last updated
     */
    updated_at: Date;
}


/**
 * @export
 */
export const AlertSlimV2StatusEnum = {
    Firing: 'firing',
    Resolved: 'resolved',
} as const;
export type AlertSlimV2StatusEnum = typeof AlertSlimV2StatusEnum[keyof typeof AlertSlimV2StatusEnum];


/**
 * Check if a given object implements the AlertSlimV2 interface.
 */
export function instanceOfAlertSlimV2(value: object): value is AlertSlimV2 {
    if (!('alert_source_id' in value) || value['alert_source_id'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('deduplication_key' in value) || value['deduplication_key'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function AlertSlimV2FromJSON(json: any): AlertSlimV2 {
    return AlertSlimV2FromJSONTyped(json, false);
}

export function AlertSlimV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertSlimV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'alert_group_ids': json['alert_group_ids'] == null ? undefined : json['alert_group_ids'],
        'alert_source_id': json['alert_source_id'],
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'deduplication_key': json['deduplication_key'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'resolved_at': json['resolved_at'] == null ? undefined : (parseDateTime(json['resolved_at'])),
        'source_url': json['source_url'] == null ? undefined : json['source_url'],
        'status': json['status'],
        'title': json['title'],
        'updated_at': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function AlertSlimV2ToJSON(json: any): AlertSlimV2 {
    return AlertSlimV2ToJSONTyped(json, false);
}

export function AlertSlimV2ToJSONTyped(value?: AlertSlimV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_group_ids': value['alert_group_ids'],
        'alert_source_id': value['alert_source_id'],
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'deduplication_key': value['deduplication_key'],
        'description': value['description'],
        'id': value['id'],
        'resolved_at': value['resolved_at'] == null ? value['resolved_at'] : serializeDateTime(value['resolved_at']),
        'source_url': value['source_url'],
        'status': value['status'],
        'title': value['title'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
    };
}

