/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EngineParamBindingPayloadV2 } from './EngineParamBindingPayloadV2.js';
import {
    EngineParamBindingPayloadV2FromJSON,
    EngineParamBindingPayloadV2FromJSONTyped,
    EngineParamBindingPayloadV2ToJSON,
    EngineParamBindingPayloadV2ToJSONTyped,
} from './EngineParamBindingPayloadV2.js';

/**
 * 
 * @export
 * @interface AlertRouteChannelTargetPayloadV2
 */
export interface AlertRouteChannelTargetPayloadV2 {
    /**
     * 
     */
    binding: EngineParamBindingPayloadV2;
    /**
     * The visibility of the channel
     */
    channel_visibility: string;
}

/**
 * Check if a given object implements the AlertRouteChannelTargetPayloadV2 interface.
 */
export function instanceOfAlertRouteChannelTargetPayloadV2(value: object): value is AlertRouteChannelTargetPayloadV2 {
    if (!('binding' in value) || value['binding'] === undefined) return false;
    if (!('channel_visibility' in value) || value['channel_visibility'] === undefined) return false;
    return true;
}

export function AlertRouteChannelTargetPayloadV2FromJSON(json: any): AlertRouteChannelTargetPayloadV2 {
    return AlertRouteChannelTargetPayloadV2FromJSONTyped(json, false);
}

export function AlertRouteChannelTargetPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertRouteChannelTargetPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'binding': EngineParamBindingPayloadV2FromJSON(json['binding']),
        'channel_visibility': json['channel_visibility'],
    };
}

export function AlertRouteChannelTargetPayloadV2ToJSON(json: any): AlertRouteChannelTargetPayloadV2 {
    return AlertRouteChannelTargetPayloadV2ToJSONTyped(json, false);
}

export function AlertRouteChannelTargetPayloadV2ToJSONTyped(value?: AlertRouteChannelTargetPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'binding': EngineParamBindingPayloadV2ToJSON(value['binding']),
        'channel_visibility': value['channel_visibility'],
    };
}

