/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExpressionPayloadV3 } from './ExpressionPayloadV3.js';
import {
    ExpressionPayloadV3FromJSON,
    ExpressionPayloadV3FromJSONTyped,
    ExpressionPayloadV3ToJSON,
    ExpressionPayloadV3ToJSONTyped,
} from './ExpressionPayloadV3.js';
import type { AlertGroupingConfigV3 } from './AlertGroupingConfigV3.js';
import {
    AlertGroupingConfigV3FromJSON,
    AlertGroupingConfigV3FromJSONTyped,
    AlertGroupingConfigV3ToJSON,
    AlertGroupingConfigV3ToJSONTyped,
} from './AlertGroupingConfigV3.js';
import type { AlertRouteEscalationConfigPayloadV3 } from './AlertRouteEscalationConfigPayloadV3.js';
import {
    AlertRouteEscalationConfigPayloadV3FromJSON,
    AlertRouteEscalationConfigPayloadV3FromJSONTyped,
    AlertRouteEscalationConfigPayloadV3ToJSON,
    AlertRouteEscalationConfigPayloadV3ToJSONTyped,
} from './AlertRouteEscalationConfigPayloadV3.js';
import type { AlertMessageConfigPayloadV3 } from './AlertMessageConfigPayloadV3.js';
import {
    AlertMessageConfigPayloadV3FromJSON,
    AlertMessageConfigPayloadV3FromJSONTyped,
    AlertMessageConfigPayloadV3ToJSON,
    AlertMessageConfigPayloadV3ToJSONTyped,
} from './AlertMessageConfigPayloadV3.js';
import type { ConditionGroupPayloadV3 } from './ConditionGroupPayloadV3.js';
import {
    ConditionGroupPayloadV3FromJSON,
    ConditionGroupPayloadV3FromJSONTyped,
    ConditionGroupPayloadV3ToJSON,
    ConditionGroupPayloadV3ToJSONTyped,
} from './ConditionGroupPayloadV3.js';
import type { AlertRouteAlertSourcePayloadV3 } from './AlertRouteAlertSourcePayloadV3.js';
import {
    AlertRouteAlertSourcePayloadV3FromJSON,
    AlertRouteAlertSourcePayloadV3FromJSONTyped,
    AlertRouteAlertSourcePayloadV3ToJSON,
    AlertRouteAlertSourcePayloadV3ToJSONTyped,
} from './AlertRouteAlertSourcePayloadV3.js';
import type { AlertRouteIncidentConfigPayloadV3 } from './AlertRouteIncidentConfigPayloadV3.js';
import {
    AlertRouteIncidentConfigPayloadV3FromJSON,
    AlertRouteIncidentConfigPayloadV3FromJSONTyped,
    AlertRouteIncidentConfigPayloadV3ToJSON,
    AlertRouteIncidentConfigPayloadV3ToJSONTyped,
} from './AlertRouteIncidentConfigPayloadV3.js';

/**
 * 
 * @export
 * @interface AlertRoutesUpdatePayloadV3
 */
export interface AlertRoutesUpdatePayloadV3 {
    /**
     * Which alert sources this route matches
     */
    alert_sources: Array<AlertRouteAlertSourcePayloadV3>;
    /**
     * Filter: the condition groups that must be true for this route to fire
     */
    condition_groups: Array<ConditionGroupPayloadV3>;
    /**
     * Whether this alert route is enabled
     */
    enabled: boolean;
    /**
     * 
     */
    escalation_config: AlertRouteEscalationConfigPayloadV3;
    /**
     * The expressions used by bindings in this route
     */
    expressions: Array<ExpressionPayloadV3>;
    /**
     * 
     */
    grouping_config: AlertGroupingConfigV3;
    /**
     * 
     */
    incident_config: AlertRouteIncidentConfigPayloadV3;
    /**
     * Whether this alert route is private. Private alert routes only create private incidents from alerts.
     */
    is_private: boolean;
    /**
     * 
     */
    message_config: AlertMessageConfigPayloadV3;
    /**
     * The name of this alert route, for the user's reference
     */
    name: string;
    /**
     * IDs of teams that own this alert route
     */
    owning_team_ids?: Array<string>;
    /**
     * The version this update will create. It must be one more than the route's latest version, otherwise the update is rejected - guarding against concurrent edits.
     */
    version: number;
}

/**
 * Check if a given object implements the AlertRoutesUpdatePayloadV3 interface.
 */
export function instanceOfAlertRoutesUpdatePayloadV3(value: object): value is AlertRoutesUpdatePayloadV3 {
    if (!('alert_sources' in value) || value['alert_sources'] === undefined) return false;
    if (!('condition_groups' in value) || value['condition_groups'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('escalation_config' in value) || value['escalation_config'] === undefined) return false;
    if (!('expressions' in value) || value['expressions'] === undefined) return false;
    if (!('grouping_config' in value) || value['grouping_config'] === undefined) return false;
    if (!('incident_config' in value) || value['incident_config'] === undefined) return false;
    if (!('is_private' in value) || value['is_private'] === undefined) return false;
    if (!('message_config' in value) || value['message_config'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function AlertRoutesUpdatePayloadV3FromJSON(json: any): AlertRoutesUpdatePayloadV3 {
    return AlertRoutesUpdatePayloadV3FromJSONTyped(json, false);
}

export function AlertRoutesUpdatePayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertRoutesUpdatePayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'alert_sources': ((json['alert_sources'] as Array<any>).map(AlertRouteAlertSourcePayloadV3FromJSON)),
        'condition_groups': ((json['condition_groups'] as Array<any>).map(ConditionGroupPayloadV3FromJSON)),
        'enabled': json['enabled'],
        'escalation_config': AlertRouteEscalationConfigPayloadV3FromJSON(json['escalation_config']),
        'expressions': ((json['expressions'] as Array<any>).map(ExpressionPayloadV3FromJSON)),
        'grouping_config': AlertGroupingConfigV3FromJSON(json['grouping_config']),
        'incident_config': AlertRouteIncidentConfigPayloadV3FromJSON(json['incident_config']),
        'is_private': json['is_private'],
        'message_config': AlertMessageConfigPayloadV3FromJSON(json['message_config']),
        'name': json['name'],
        'owning_team_ids': json['owning_team_ids'] == null ? undefined : json['owning_team_ids'],
        'version': json['version'],
    };
}

export function AlertRoutesUpdatePayloadV3ToJSON(json: any): AlertRoutesUpdatePayloadV3 {
    return AlertRoutesUpdatePayloadV3ToJSONTyped(json, false);
}

export function AlertRoutesUpdatePayloadV3ToJSONTyped(value?: AlertRoutesUpdatePayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_sources': ((value['alert_sources'] as Array<any>).map(AlertRouteAlertSourcePayloadV3ToJSON)),
        'condition_groups': ((value['condition_groups'] as Array<any>).map(ConditionGroupPayloadV3ToJSON)),
        'enabled': value['enabled'],
        'escalation_config': AlertRouteEscalationConfigPayloadV3ToJSON(value['escalation_config']),
        'expressions': ((value['expressions'] as Array<any>).map(ExpressionPayloadV3ToJSON)),
        'grouping_config': AlertGroupingConfigV3ToJSON(value['grouping_config']),
        'incident_config': AlertRouteIncidentConfigPayloadV3ToJSON(value['incident_config']),
        'is_private': value['is_private'],
        'message_config': AlertMessageConfigPayloadV3ToJSON(value['message_config']),
        'name': value['name'],
        'owning_team_ids': value['owning_team_ids'],
        'version': value['version'],
    };
}

