/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AlertRouteEscalationTargetPayloadV2 } from './AlertRouteEscalationTargetPayloadV2.js';
import {
    AlertRouteEscalationTargetPayloadV2FromJSON,
    AlertRouteEscalationTargetPayloadV2FromJSONTyped,
    AlertRouteEscalationTargetPayloadV2ToJSON,
    AlertRouteEscalationTargetPayloadV2ToJSONTyped,
} from './AlertRouteEscalationTargetPayloadV2.js';

/**
 * 
 * @export
 * @interface AlertRouteEscalationConfigPayloadV2
 */
export interface AlertRouteEscalationConfigPayloadV2 {
    /**
     * Should we auto cancel escalations when all alerts are resolved?
     */
    auto_cancel_escalations: boolean;
    /**
     * Targets for escalation
     */
    escalation_targets: Array<AlertRouteEscalationTargetPayloadV2>;
}

/**
 * Check if a given object implements the AlertRouteEscalationConfigPayloadV2 interface.
 */
export function instanceOfAlertRouteEscalationConfigPayloadV2(value: object): value is AlertRouteEscalationConfigPayloadV2 {
    if (!('auto_cancel_escalations' in value) || value['auto_cancel_escalations'] === undefined) return false;
    if (!('escalation_targets' in value) || value['escalation_targets'] === undefined) return false;
    return true;
}

export function AlertRouteEscalationConfigPayloadV2FromJSON(json: any): AlertRouteEscalationConfigPayloadV2 {
    return AlertRouteEscalationConfigPayloadV2FromJSONTyped(json, false);
}

export function AlertRouteEscalationConfigPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertRouteEscalationConfigPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'auto_cancel_escalations': json['auto_cancel_escalations'],
        'escalation_targets': ((json['escalation_targets'] as Array<any>).map(AlertRouteEscalationTargetPayloadV2FromJSON)),
    };
}

export function AlertRouteEscalationConfigPayloadV2ToJSON(json: any): AlertRouteEscalationConfigPayloadV2 {
    return AlertRouteEscalationConfigPayloadV2ToJSONTyped(json, false);
}

export function AlertRouteEscalationConfigPayloadV2ToJSONTyped(value?: AlertRouteEscalationConfigPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auto_cancel_escalations': value['auto_cancel_escalations'],
        'escalation_targets': ((value['escalation_targets'] as Array<any>).map(AlertRouteEscalationTargetPayloadV2ToJSON)),
    };
}

