/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EngineParamBindingPayloadV3 } from './EngineParamBindingPayloadV3.js';
import {
    EngineParamBindingPayloadV3FromJSON,
    EngineParamBindingPayloadV3FromJSONTyped,
    EngineParamBindingPayloadV3ToJSON,
    EngineParamBindingPayloadV3ToJSONTyped,
} from './EngineParamBindingPayloadV3.js';

/**
 * 
 * @export
 * @interface AlertRouteEscalationTargetPayloadV3
 */
export interface AlertRouteEscalationTargetPayloadV3 {
    /**
     * 
     */
    escalation_paths?: EngineParamBindingPayloadV3;
    /**
     * 
     */
    users?: EngineParamBindingPayloadV3;
}

/**
 * Check if a given object implements the AlertRouteEscalationTargetPayloadV3 interface.
 */
export function instanceOfAlertRouteEscalationTargetPayloadV3(value: object): value is AlertRouteEscalationTargetPayloadV3 {
    return true;
}

export function AlertRouteEscalationTargetPayloadV3FromJSON(json: any): AlertRouteEscalationTargetPayloadV3 {
    return AlertRouteEscalationTargetPayloadV3FromJSONTyped(json, false);
}

export function AlertRouteEscalationTargetPayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertRouteEscalationTargetPayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'escalation_paths': json['escalation_paths'] == null ? undefined : EngineParamBindingPayloadV3FromJSON(json['escalation_paths']),
        'users': json['users'] == null ? undefined : EngineParamBindingPayloadV3FromJSON(json['users']),
    };
}

export function AlertRouteEscalationTargetPayloadV3ToJSON(json: any): AlertRouteEscalationTargetPayloadV3 {
    return AlertRouteEscalationTargetPayloadV3ToJSONTyped(json, false);
}

export function AlertRouteEscalationTargetPayloadV3ToJSONTyped(value?: AlertRouteEscalationTargetPayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'escalation_paths': EngineParamBindingPayloadV3ToJSON(value['escalation_paths']),
        'users': EngineParamBindingPayloadV3ToJSON(value['users']),
    };
}

