/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { AlertRouteChannelConfigV2 } from './AlertRouteChannelConfigV2.js';
import {
    AlertRouteChannelConfigV2FromJSON,
    AlertRouteChannelConfigV2FromJSONTyped,
    AlertRouteChannelConfigV2ToJSON,
    AlertRouteChannelConfigV2ToJSONTyped,
} from './AlertRouteChannelConfigV2.js';
import type { AlertRouteAlertSourceV2 } from './AlertRouteAlertSourceV2.js';
import {
    AlertRouteAlertSourceV2FromJSON,
    AlertRouteAlertSourceV2FromJSONTyped,
    AlertRouteAlertSourceV2ToJSON,
    AlertRouteAlertSourceV2ToJSONTyped,
} from './AlertRouteAlertSourceV2.js';
import type { AlertRouteEscalationConfigV2 } from './AlertRouteEscalationConfigV2.js';
import {
    AlertRouteEscalationConfigV2FromJSON,
    AlertRouteEscalationConfigV2FromJSONTyped,
    AlertRouteEscalationConfigV2ToJSON,
    AlertRouteEscalationConfigV2ToJSONTyped,
} from './AlertRouteEscalationConfigV2.js';
import type { AlertRouteIncidentConfigV2 } from './AlertRouteIncidentConfigV2.js';
import {
    AlertRouteIncidentConfigV2FromJSON,
    AlertRouteIncidentConfigV2FromJSONTyped,
    AlertRouteIncidentConfigV2ToJSON,
    AlertRouteIncidentConfigV2ToJSONTyped,
} from './AlertRouteIncidentConfigV2.js';
import type { AlertRouteIncidentTemplateV2 } from './AlertRouteIncidentTemplateV2.js';
import {
    AlertRouteIncidentTemplateV2FromJSON,
    AlertRouteIncidentTemplateV2FromJSONTyped,
    AlertRouteIncidentTemplateV2ToJSON,
    AlertRouteIncidentTemplateV2ToJSONTyped,
} from './AlertRouteIncidentTemplateV2.js';
import type { ExpressionV2 } from './ExpressionV2.js';
import {
    ExpressionV2FromJSON,
    ExpressionV2FromJSONTyped,
    ExpressionV2ToJSON,
    ExpressionV2ToJSONTyped,
} from './ExpressionV2.js';
import type { ConditionGroupV2 } from './ConditionGroupV2.js';
import {
    ConditionGroupV2FromJSON,
    ConditionGroupV2FromJSONTyped,
    ConditionGroupV2ToJSON,
    ConditionGroupV2ToJSONTyped,
} from './ConditionGroupV2.js';
import type { EngineParamBindingV2 } from './EngineParamBindingV2.js';
import {
    EngineParamBindingV2FromJSON,
    EngineParamBindingV2FromJSONTyped,
    EngineParamBindingV2ToJSON,
    EngineParamBindingV2ToJSONTyped,
} from './EngineParamBindingV2.js';

/**
 * 
 * @export
 * @interface AlertRouteV2
 */
export interface AlertRouteV2 {
    /**
     * Which alert sources should this alert route match?
     */
    alert_sources: Array<AlertRouteAlertSourceV2>;
    /**
     * The channel configuration for this alert route
     */
    channel_config: Array<AlertRouteChannelConfigV2>;
    /**
     * What condition groups must be true for this alert route to fire?
     */
    condition_groups: Array<ConditionGroupV2>;
    /**
     * The time of creation of this alert route
     */
    created_at?: Date;
    /**
     * Whether this alert route is enabled or not
     */
    enabled: boolean;
    /**
     * 
     */
    escalation_config: AlertRouteEscalationConfigV2;
    /**
     * The expressions used in this template
     */
    expressions: Array<ExpressionV2>;
    /**
     * Unique identifier for this alert route config
     */
    id: string;
    /**
     * 
     */
    incident_config: AlertRouteIncidentConfigV2;
    /**
     * 
     */
    incident_template: AlertRouteIncidentTemplateV2;
    /**
     * Whether this alert route is private. Private alert routes will only create private incidents from alerts.
     */
    is_private: boolean;
    /**
     * 
     */
    message_template?: EngineParamBindingV2;
    /**
     * The name of this alert route config, for the user's reference
     */
    name: string;
    /**
     * IDs of teams that own this alert route
     */
    owning_team_ids?: Array<string>;
    /**
     * The time of last update of this alert route
     */
    updated_at?: Date;
    /**
     * The version of this alert route config
     */
    version: number;
}

/**
 * Check if a given object implements the AlertRouteV2 interface.
 */
export function instanceOfAlertRouteV2(value: object): value is AlertRouteV2 {
    if (!('alert_sources' in value) || value['alert_sources'] === undefined) return false;
    if (!('channel_config' in value) || value['channel_config'] === undefined) return false;
    if (!('condition_groups' in value) || value['condition_groups'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('escalation_config' in value) || value['escalation_config'] === undefined) return false;
    if (!('expressions' in value) || value['expressions'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incident_config' in value) || value['incident_config'] === undefined) return false;
    if (!('incident_template' in value) || value['incident_template'] === undefined) return false;
    if (!('is_private' in value) || value['is_private'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function AlertRouteV2FromJSON(json: any): AlertRouteV2 {
    return AlertRouteV2FromJSONTyped(json, false);
}

export function AlertRouteV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertRouteV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'alert_sources': ((json['alert_sources'] as Array<any>).map(AlertRouteAlertSourceV2FromJSON)),
        'channel_config': ((json['channel_config'] as Array<any>).map(AlertRouteChannelConfigV2FromJSON)),
        'condition_groups': ((json['condition_groups'] as Array<any>).map(ConditionGroupV2FromJSON)),
        'created_at': json['created_at'] == null ? undefined : (parseDateTime(json['created_at'])),
        'enabled': json['enabled'],
        'escalation_config': AlertRouteEscalationConfigV2FromJSON(json['escalation_config']),
        'expressions': ((json['expressions'] as Array<any>).map(ExpressionV2FromJSON)),
        'id': json['id'],
        'incident_config': AlertRouteIncidentConfigV2FromJSON(json['incident_config']),
        'incident_template': AlertRouteIncidentTemplateV2FromJSON(json['incident_template']),
        'is_private': json['is_private'],
        'message_template': json['message_template'] == null ? undefined : EngineParamBindingV2FromJSON(json['message_template']),
        'name': json['name'],
        'owning_team_ids': json['owning_team_ids'] == null ? undefined : json['owning_team_ids'],
        'updated_at': json['updated_at'] == null ? undefined : (parseDateTime(json['updated_at'])),
        'version': json['version'],
    };
}

export function AlertRouteV2ToJSON(json: any): AlertRouteV2 {
    return AlertRouteV2ToJSONTyped(json, false);
}

export function AlertRouteV2ToJSONTyped(value?: AlertRouteV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_sources': ((value['alert_sources'] as Array<any>).map(AlertRouteAlertSourceV2ToJSON)),
        'channel_config': ((value['channel_config'] as Array<any>).map(AlertRouteChannelConfigV2ToJSON)),
        'condition_groups': ((value['condition_groups'] as Array<any>).map(ConditionGroupV2ToJSON)),
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'enabled': value['enabled'],
        'escalation_config': AlertRouteEscalationConfigV2ToJSON(value['escalation_config']),
        'expressions': ((value['expressions'] as Array<any>).map(ExpressionV2ToJSON)),
        'id': value['id'],
        'incident_config': AlertRouteIncidentConfigV2ToJSON(value['incident_config']),
        'incident_template': AlertRouteIncidentTemplateV2ToJSON(value['incident_template']),
        'is_private': value['is_private'],
        'message_template': EngineParamBindingV2ToJSON(value['message_template']),
        'name': value['name'],
        'owning_team_ids': value['owning_team_ids'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
        'version': value['version'],
    };
}

