/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AlertTemplateAttributeBindingPayloadV2 } from './AlertTemplateAttributeBindingPayloadV2.js';
import {
    AlertTemplateAttributeBindingPayloadV2FromJSON,
    AlertTemplateAttributeBindingPayloadV2FromJSONTyped,
    AlertTemplateAttributeBindingPayloadV2ToJSON,
    AlertTemplateAttributeBindingPayloadV2ToJSONTyped,
} from './AlertTemplateAttributeBindingPayloadV2.js';

/**
 * 
 * @export
 * @interface AlertTemplateAttributePayloadV2
 */
export interface AlertTemplateAttributePayloadV2 {
    /**
     * ID of the alert attribute to set with this binding
     */
    alert_attribute_id: string;
    /**
     * 
     */
    binding: AlertTemplateAttributeBindingPayloadV2;
}

/**
 * Check if a given object implements the AlertTemplateAttributePayloadV2 interface.
 */
export function instanceOfAlertTemplateAttributePayloadV2(value: object): value is AlertTemplateAttributePayloadV2 {
    if (!('alert_attribute_id' in value) || value['alert_attribute_id'] === undefined) return false;
    if (!('binding' in value) || value['binding'] === undefined) return false;
    return true;
}

export function AlertTemplateAttributePayloadV2FromJSON(json: any): AlertTemplateAttributePayloadV2 {
    return AlertTemplateAttributePayloadV2FromJSONTyped(json, false);
}

export function AlertTemplateAttributePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertTemplateAttributePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'alert_attribute_id': json['alert_attribute_id'],
        'binding': AlertTemplateAttributeBindingPayloadV2FromJSON(json['binding']),
    };
}

export function AlertTemplateAttributePayloadV2ToJSON(json: any): AlertTemplateAttributePayloadV2 {
    return AlertTemplateAttributePayloadV2ToJSONTyped(json, false);
}

export function AlertTemplateAttributePayloadV2ToJSONTyped(value?: AlertTemplateAttributePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alert_attribute_id': value['alert_attribute_id'],
        'binding': AlertTemplateAttributeBindingPayloadV2ToJSON(value['binding']),
    };
}

