/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AnnouncementTemplateActionPayloadV2 } from './AnnouncementTemplateActionPayloadV2.js';
import {
    AnnouncementTemplateActionPayloadV2FromJSON,
    AnnouncementTemplateActionPayloadV2FromJSONTyped,
    AnnouncementTemplateActionPayloadV2ToJSON,
    AnnouncementTemplateActionPayloadV2ToJSONTyped,
} from './AnnouncementTemplateActionPayloadV2.js';
import type { AnnouncementTemplateFieldPayloadV2 } from './AnnouncementTemplateFieldPayloadV2.js';
import {
    AnnouncementTemplateFieldPayloadV2FromJSON,
    AnnouncementTemplateFieldPayloadV2FromJSONTyped,
    AnnouncementTemplateFieldPayloadV2ToJSON,
    AnnouncementTemplateFieldPayloadV2ToJSONTyped,
} from './AnnouncementTemplateFieldPayloadV2.js';

/**
 * 
 * @export
 * @interface AnnouncementTemplatesUpdatePayloadV2
 */
export interface AnnouncementTemplatesUpdatePayloadV2 {
    /**
     * Actions shown on the announcement post. Send an empty array to remove them all.
     */
    actions: Array<AnnouncementTemplateActionPayloadV2>;
    /**
     * Fields shown on the announcement post. Send an empty array to remove them all.
     */
    fields: Array<AnnouncementTemplateFieldPayloadV2>;
    /**
     * Name of this announcement template, unique within the organisation
     */
    name: string;
    /**
     * IDs of the teams that own this template. The existing owning teams are kept when omitted.
     */
    owning_team_ids?: Array<string>;
}

/**
 * Check if a given object implements the AnnouncementTemplatesUpdatePayloadV2 interface.
 */
export function instanceOfAnnouncementTemplatesUpdatePayloadV2(value: object): value is AnnouncementTemplatesUpdatePayloadV2 {
    if (!('actions' in value) || value['actions'] === undefined) return false;
    if (!('fields' in value) || value['fields'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AnnouncementTemplatesUpdatePayloadV2FromJSON(json: any): AnnouncementTemplatesUpdatePayloadV2 {
    return AnnouncementTemplatesUpdatePayloadV2FromJSONTyped(json, false);
}

export function AnnouncementTemplatesUpdatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementTemplatesUpdatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'actions': ((json['actions'] as Array<any>).map(AnnouncementTemplateActionPayloadV2FromJSON)),
        'fields': ((json['fields'] as Array<any>).map(AnnouncementTemplateFieldPayloadV2FromJSON)),
        'name': json['name'],
        'owning_team_ids': json['owning_team_ids'] == null ? undefined : json['owning_team_ids'],
    };
}

export function AnnouncementTemplatesUpdatePayloadV2ToJSON(json: any): AnnouncementTemplatesUpdatePayloadV2 {
    return AnnouncementTemplatesUpdatePayloadV2ToJSONTyped(json, false);
}

export function AnnouncementTemplatesUpdatePayloadV2ToJSONTyped(value?: AnnouncementTemplatesUpdatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actions': ((value['actions'] as Array<any>).map(AnnouncementTemplateActionPayloadV2ToJSON)),
        'fields': ((value['fields'] as Array<any>).map(AnnouncementTemplateFieldPayloadV2ToJSON)),
        'name': value['name'],
        'owning_team_ids': value['owning_team_ids'],
    };
}

