/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AnnouncementTemplateRichTextV2 } from './AnnouncementTemplateRichTextV2.js';
import {
    AnnouncementTemplateRichTextV2FromJSON,
    AnnouncementTemplateRichTextV2FromJSONTyped,
    AnnouncementTemplateRichTextV2ToJSON,
    AnnouncementTemplateRichTextV2ToJSONTyped,
} from './AnnouncementTemplateRichTextV2.js';

/**
 * 
 * @export
 * @interface AnnouncementTemplateFieldPayloadV2
 */
export interface AnnouncementTemplateFieldPayloadV2 {
    /**
     * ID of the custom field to show. Required for custom field fields.
     */
    custom_field_id?: string;
    /**
     * Emoji shown next to this field, as a Slack emoji name
     */
    emoji?: string;
    /**
     * Type of this field
     */
    field_type: AnnouncementTemplateFieldPayloadV2FieldTypeEnum;
    /**
     * ID of the incident role to show. Required for incident role fields.
     */
    incident_role_id?: string;
    /**
     * ID of the incident timestamp to show. Required for incident timestamp fields.
     */
    incident_timestamp_id?: string;
    /**
     * Position of this field on the post, lowest first
     */
    rank: number;
    /**
     * 
     */
    rich_text?: AnnouncementTemplateRichTextV2;
}


/**
 * @export
 */
export const AnnouncementTemplateFieldPayloadV2FieldTypeEnum = {
    AnnouncementPostFieldsStatus: 'announcement_post_fields_status',
    AnnouncementPostFieldsIncidentType: 'announcement_post_fields_incident_type',
    AnnouncementPostFieldsSeverity: 'announcement_post_fields_severity',
    AnnouncementPostFieldsRole: 'announcement_post_fields_role',
    AnnouncementPostFieldsDescription: 'announcement_post_fields_description',
    AnnouncementPostFieldsCustomField: 'announcement_post_fields_custom_field',
    AnnouncementPostFieldsTimestamp: 'announcement_post_fields_timestamp',
    AnnouncementPostFieldsCreator: 'announcement_post_fields_creator',
    AnnouncementPostFieldsSlack: 'announcement_post_fields_slack',
    AnnouncementPostFieldsRichText: 'announcement_post_fields_rich_text',
} as const;
export type AnnouncementTemplateFieldPayloadV2FieldTypeEnum = typeof AnnouncementTemplateFieldPayloadV2FieldTypeEnum[keyof typeof AnnouncementTemplateFieldPayloadV2FieldTypeEnum];


/**
 * Check if a given object implements the AnnouncementTemplateFieldPayloadV2 interface.
 */
export function instanceOfAnnouncementTemplateFieldPayloadV2(value: object): value is AnnouncementTemplateFieldPayloadV2 {
    if (!('field_type' in value) || value['field_type'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    return true;
}

export function AnnouncementTemplateFieldPayloadV2FromJSON(json: any): AnnouncementTemplateFieldPayloadV2 {
    return AnnouncementTemplateFieldPayloadV2FromJSONTyped(json, false);
}

export function AnnouncementTemplateFieldPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementTemplateFieldPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'custom_field_id': json['custom_field_id'] == null ? undefined : json['custom_field_id'],
        'emoji': json['emoji'] == null ? undefined : json['emoji'],
        'field_type': json['field_type'],
        'incident_role_id': json['incident_role_id'] == null ? undefined : json['incident_role_id'],
        'incident_timestamp_id': json['incident_timestamp_id'] == null ? undefined : json['incident_timestamp_id'],
        'rank': json['rank'],
        'rich_text': json['rich_text'] == null ? undefined : AnnouncementTemplateRichTextV2FromJSON(json['rich_text']),
    };
}

export function AnnouncementTemplateFieldPayloadV2ToJSON(json: any): AnnouncementTemplateFieldPayloadV2 {
    return AnnouncementTemplateFieldPayloadV2ToJSONTyped(json, false);
}

export function AnnouncementTemplateFieldPayloadV2ToJSONTyped(value?: AnnouncementTemplateFieldPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_field_id': value['custom_field_id'],
        'emoji': value['emoji'],
        'field_type': value['field_type'],
        'incident_role_id': value['incident_role_id'],
        'incident_timestamp_id': value['incident_timestamp_id'],
        'rank': value['rank'],
        'rich_text': AnnouncementTemplateRichTextV2ToJSON(value['rich_text']),
    };
}

