/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AnnouncementTemplateActionV2
 */
export interface AnnouncementTemplateActionV2 {
    /**
     * Type of this action
     */
    action_type: AnnouncementTemplateActionV2ActionTypeEnum;
    /**
     * Emoji shown on this action's button
     */
    emoji?: string;
    /**
     * Position of this action on the post, lowest first
     */
    rank: number;
    /**
     * Label shown on this action's button, derived from its type
     */
    title: string;
}


/**
 * @export
 */
export const AnnouncementTemplateActionV2ActionTypeEnum = {
    AnnouncementPostActionsHomepage: 'announcement_post_actions_homepage',
    AnnouncementPostActionsSubscribe: 'announcement_post_actions_subscribe',
    AnnouncementPostActionsJoinCall: 'announcement_post_actions_join_call',
    AnnouncementPostActionsJiraTicket: 'announcement_post_actions_jira_ticket',
    AnnouncementPostActionsInternalStatusPage: 'announcement_post_actions_internal_status_page',
    AnnouncementPostActionsPublicStatusPage: 'announcement_post_actions_public_status_page',
    AnnouncementPostActionsPostmortem: 'announcement_post_actions_postmortem',
    AnnouncementPostActionsCreateChannel: 'announcement_post_actions_create_channel',
    AnnouncementPostActionsViewAlert: 'announcement_post_actions_view_alert',
    AnnouncementPostActionsTriage: 'announcement_post_actions_triage',
    AnnouncementPostActionsEscalate: 'announcement_post_actions_escalate',
    AnnouncementPostActionsShareUpdate: 'announcement_post_actions_share_update',
    AnnouncementPostActionsUpdateStatus: 'announcement_post_actions_update_status',
    AnnouncementPostActionsRequestAccess: 'announcement_post_actions_request_access',
} as const;
export type AnnouncementTemplateActionV2ActionTypeEnum = typeof AnnouncementTemplateActionV2ActionTypeEnum[keyof typeof AnnouncementTemplateActionV2ActionTypeEnum];


/**
 * Check if a given object implements the AnnouncementTemplateActionV2 interface.
 */
export function instanceOfAnnouncementTemplateActionV2(value: object): value is AnnouncementTemplateActionV2 {
    if (!('action_type' in value) || value['action_type'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function AnnouncementTemplateActionV2FromJSON(json: any): AnnouncementTemplateActionV2 {
    return AnnouncementTemplateActionV2FromJSONTyped(json, false);
}

export function AnnouncementTemplateActionV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementTemplateActionV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'action_type': json['action_type'],
        'emoji': json['emoji'] == null ? undefined : json['emoji'],
        'rank': json['rank'],
        'title': json['title'],
    };
}

export function AnnouncementTemplateActionV2ToJSON(json: any): AnnouncementTemplateActionV2 {
    return AnnouncementTemplateActionV2ToJSONTyped(json, false);
}

export function AnnouncementTemplateActionV2ToJSONTyped(value?: AnnouncementTemplateActionV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action_type': value['action_type'],
        'emoji': value['emoji'],
        'rank': value['rank'],
        'title': value['title'],
    };
}

