/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AnnouncementTemplateActionPayloadV2 } from './AnnouncementTemplateActionPayloadV2.js';
import {
    AnnouncementTemplateActionPayloadV2FromJSON,
    AnnouncementTemplateActionPayloadV2FromJSONTyped,
    AnnouncementTemplateActionPayloadV2ToJSON,
    AnnouncementTemplateActionPayloadV2ToJSONTyped,
} from './AnnouncementTemplateActionPayloadV2.js';
import type { AnnouncementTemplateFieldPayloadV2 } from './AnnouncementTemplateFieldPayloadV2.js';
import {
    AnnouncementTemplateFieldPayloadV2FromJSON,
    AnnouncementTemplateFieldPayloadV2FromJSONTyped,
    AnnouncementTemplateFieldPayloadV2ToJSON,
    AnnouncementTemplateFieldPayloadV2ToJSONTyped,
} from './AnnouncementTemplateFieldPayloadV2.js';

/**
 * 
 * @export
 * @interface AnnouncementTemplatesCreatePayloadV2
 */
export interface AnnouncementTemplatesCreatePayloadV2 {
    /**
     * Actions shown on the announcement post
     */
    actions?: Array<AnnouncementTemplateActionPayloadV2>;
    /**
     * Fields shown on the announcement post
     */
    fields?: Array<AnnouncementTemplateFieldPayloadV2>;
    /**
     * Name of this announcement template, unique within the organisation
     */
    name: string;
    /**
     * IDs of the teams that own this template
     */
    owning_team_ids?: Array<string>;
}

/**
 * Check if a given object implements the AnnouncementTemplatesCreatePayloadV2 interface.
 */
export function instanceOfAnnouncementTemplatesCreatePayloadV2(value: object): value is AnnouncementTemplatesCreatePayloadV2 {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AnnouncementTemplatesCreatePayloadV2FromJSON(json: any): AnnouncementTemplatesCreatePayloadV2 {
    return AnnouncementTemplatesCreatePayloadV2FromJSONTyped(json, false);
}

export function AnnouncementTemplatesCreatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementTemplatesCreatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'actions': json['actions'] == null ? undefined : ((json['actions'] as Array<any>).map(AnnouncementTemplateActionPayloadV2FromJSON)),
        'fields': json['fields'] == null ? undefined : ((json['fields'] as Array<any>).map(AnnouncementTemplateFieldPayloadV2FromJSON)),
        'name': json['name'],
        'owning_team_ids': json['owning_team_ids'] == null ? undefined : json['owning_team_ids'],
    };
}

export function AnnouncementTemplatesCreatePayloadV2ToJSON(json: any): AnnouncementTemplatesCreatePayloadV2 {
    return AnnouncementTemplatesCreatePayloadV2ToJSONTyped(json, false);
}

export function AnnouncementTemplatesCreatePayloadV2ToJSONTyped(value?: AnnouncementTemplatesCreatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actions': value['actions'] == null ? undefined : ((value['actions'] as Array<any>).map(AnnouncementTemplateActionPayloadV2ToJSON)),
        'fields': value['fields'] == null ? undefined : ((value['fields'] as Array<any>).map(AnnouncementTemplateFieldPayloadV2ToJSON)),
        'name': value['name'],
        'owning_team_ids': value['owning_team_ids'],
    };
}

