/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AuditLogExtensionConnectorCalledMetadataV2
 */
export interface AuditLogExtensionConnectorCalledMetadataV2 {
    /**
     * How the call ended (success, error)
     */
    outcome: string;
    /**
     * The kind of connector that was called (mcp, http)
     */
    source_kind: string;
    /**
     * The product surface the call ran from (chat, investigation, explore, mcp_client, verify), or internal for system paths with no surface
     */
    surface: string;
    /**
     * ID of our stored record of this call
     */
    telemetry_query_id?: string;
    /**
     * Whether the call was permitted to change the connected system (true, false)
     */
    write: string;
}

/**
 * Check if a given object implements the AuditLogExtensionConnectorCalledMetadataV2 interface.
 */
export function instanceOfAuditLogExtensionConnectorCalledMetadataV2(value: object): value is AuditLogExtensionConnectorCalledMetadataV2 {
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('source_kind' in value) || value['source_kind'] === undefined) return false;
    if (!('surface' in value) || value['surface'] === undefined) return false;
    if (!('write' in value) || value['write'] === undefined) return false;
    return true;
}

export function AuditLogExtensionConnectorCalledMetadataV2FromJSON(json: any): AuditLogExtensionConnectorCalledMetadataV2 {
    return AuditLogExtensionConnectorCalledMetadataV2FromJSONTyped(json, false);
}

export function AuditLogExtensionConnectorCalledMetadataV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLogExtensionConnectorCalledMetadataV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'outcome': json['outcome'],
        'source_kind': json['source_kind'],
        'surface': json['surface'],
        'telemetry_query_id': json['telemetry_query_id'] == null ? undefined : json['telemetry_query_id'],
        'write': json['write'],
    };
}

export function AuditLogExtensionConnectorCalledMetadataV2ToJSON(json: any): AuditLogExtensionConnectorCalledMetadataV2 {
    return AuditLogExtensionConnectorCalledMetadataV2ToJSONTyped(json, false);
}

export function AuditLogExtensionConnectorCalledMetadataV2ToJSONTyped(value?: AuditLogExtensionConnectorCalledMetadataV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outcome': value['outcome'],
        'source_kind': value['source_kind'],
        'surface': value['surface'],
        'telemetry_query_id': value['telemetry_query_id'],
        'write': value['write'],
    };
}

