/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AuditLogOrganisationSettingsUpdatedMetadataV2
 */
export interface AuditLogOrganisationSettingsUpdatedMetadataV2 {
    /**
     * The organisation name after the change
     */
    after_organisation_name?: string;
    /**
     * The organisation name before the change
     */
    before_organisation_name?: string;
    /**
     * The default timezone that was set
     */
    default_timezone?: string;
}

/**
 * Check if a given object implements the AuditLogOrganisationSettingsUpdatedMetadataV2 interface.
 */
export function instanceOfAuditLogOrganisationSettingsUpdatedMetadataV2(value: object): value is AuditLogOrganisationSettingsUpdatedMetadataV2 {
    return true;
}

export function AuditLogOrganisationSettingsUpdatedMetadataV2FromJSON(json: any): AuditLogOrganisationSettingsUpdatedMetadataV2 {
    return AuditLogOrganisationSettingsUpdatedMetadataV2FromJSONTyped(json, false);
}

export function AuditLogOrganisationSettingsUpdatedMetadataV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLogOrganisationSettingsUpdatedMetadataV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'after_organisation_name': json['after_organisation_name'] == null ? undefined : json['after_organisation_name'],
        'before_organisation_name': json['before_organisation_name'] == null ? undefined : json['before_organisation_name'],
        'default_timezone': json['default_timezone'] == null ? undefined : json['default_timezone'],
    };
}

export function AuditLogOrganisationSettingsUpdatedMetadataV2ToJSON(json: any): AuditLogOrganisationSettingsUpdatedMetadataV2 {
    return AuditLogOrganisationSettingsUpdatedMetadataV2ToJSONTyped(json, false);
}

export function AuditLogOrganisationSettingsUpdatedMetadataV2ToJSONTyped(value?: AuditLogOrganisationSettingsUpdatedMetadataV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'after_organisation_name': value['after_organisation_name'],
        'before_organisation_name': value['before_organisation_name'],
        'default_timezone': value['default_timezone'],
    };
}

