/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AuditLogPrivateInsightsMeasureQueriedMetadataV2
 */
export interface AuditLogPrivateInsightsMeasureQueriedMetadataV2 {
    /**
     * Name of the Insights measure
     */
    measure?: string;
    /**
     * Whether or not the user was able to access private Insights data
     */
    outcome?: AuditLogPrivateInsightsMeasureQueriedMetadataV2OutcomeEnum;
}


/**
 * @export
 */
export const AuditLogPrivateInsightsMeasureQueriedMetadataV2OutcomeEnum = {
    Granted: 'granted',
    Denied: 'denied',
} as const;
export type AuditLogPrivateInsightsMeasureQueriedMetadataV2OutcomeEnum = typeof AuditLogPrivateInsightsMeasureQueriedMetadataV2OutcomeEnum[keyof typeof AuditLogPrivateInsightsMeasureQueriedMetadataV2OutcomeEnum];


/**
 * Check if a given object implements the AuditLogPrivateInsightsMeasureQueriedMetadataV2 interface.
 */
export function instanceOfAuditLogPrivateInsightsMeasureQueriedMetadataV2(value: object): value is AuditLogPrivateInsightsMeasureQueriedMetadataV2 {
    return true;
}

export function AuditLogPrivateInsightsMeasureQueriedMetadataV2FromJSON(json: any): AuditLogPrivateInsightsMeasureQueriedMetadataV2 {
    return AuditLogPrivateInsightsMeasureQueriedMetadataV2FromJSONTyped(json, false);
}

export function AuditLogPrivateInsightsMeasureQueriedMetadataV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLogPrivateInsightsMeasureQueriedMetadataV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'measure': json['measure'] == null ? undefined : json['measure'],
        'outcome': json['outcome'] == null ? undefined : json['outcome'],
    };
}

export function AuditLogPrivateInsightsMeasureQueriedMetadataV2ToJSON(json: any): AuditLogPrivateInsightsMeasureQueriedMetadataV2 {
    return AuditLogPrivateInsightsMeasureQueriedMetadataV2ToJSONTyped(json, false);
}

export function AuditLogPrivateInsightsMeasureQueriedMetadataV2ToJSONTyped(value?: AuditLogPrivateInsightsMeasureQueriedMetadataV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'measure': value['measure'],
        'outcome': value['outcome'],
    };
}

