/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PaginationMetaResultV2 } from './PaginationMetaResultV2.js';
import {
    PaginationMetaResultV2FromJSON,
    PaginationMetaResultV2FromJSONTyped,
    PaginationMetaResultV2ToJSON,
    PaginationMetaResultV2ToJSONTyped,
} from './PaginationMetaResultV2.js';
import type { CallSessionV2 } from './CallSessionV2.js';
import {
    CallSessionV2FromJSON,
    CallSessionV2FromJSONTyped,
    CallSessionV2ToJSON,
    CallSessionV2ToJSONTyped,
} from './CallSessionV2.js';

/**
 * 
 * @export
 * @interface CallSessionsListResultV2
 */
export interface CallSessionsListResultV2 {
    /**
     * 
     */
    call_sessions: Array<CallSessionV2>;
    /**
     * 
     */
    pagination_meta?: PaginationMetaResultV2;
}

/**
 * Check if a given object implements the CallSessionsListResultV2 interface.
 */
export function instanceOfCallSessionsListResultV2(value: object): value is CallSessionsListResultV2 {
    if (!('call_sessions' in value) || value['call_sessions'] === undefined) return false;
    return true;
}

export function CallSessionsListResultV2FromJSON(json: any): CallSessionsListResultV2 {
    return CallSessionsListResultV2FromJSONTyped(json, false);
}

export function CallSessionsListResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CallSessionsListResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'call_sessions': ((json['call_sessions'] as Array<any>).map(CallSessionV2FromJSON)),
        'pagination_meta': json['pagination_meta'] == null ? undefined : PaginationMetaResultV2FromJSON(json['pagination_meta']),
    };
}

export function CallSessionsListResultV2ToJSON(json: any): CallSessionsListResultV2 {
    return CallSessionsListResultV2ToJSONTyped(json, false);
}

export function CallSessionsListResultV2ToJSONTyped(value?: CallSessionsListResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'call_sessions': ((value['call_sessions'] as Array<any>).map(CallSessionV2ToJSON)),
        'pagination_meta': PaginationMetaResultV2ToJSON(value['pagination_meta']),
    };
}

