/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * A single entry of a Scribe call transcript: one contiguous run of
 * speech, or one in-call chat message, from one participant.
 * @export
 * @interface CallTranscriptEntryV2
 */
export interface CallTranscriptEntryV2 {
    /**
     * What was said
     */
    content: string;
    /**
     * Unique identifier for this transcript entry
     */
    id: string;
    /**
     * Whether this entry was spoken aloud or sent as an in-call chat message
     */
    medium: CallTranscriptEntryV2MediumEnum;
    /**
     * Name of the participant who spoke or sent the message, as reported by the call provider
     */
    participant_name: string;
    /**
     * When the participant started speaking
     */
    timestamp: Date;
}


/**
 * @export
 */
export const CallTranscriptEntryV2MediumEnum = {
    Spoken: 'spoken',
    CallChat: 'call_chat',
} as const;
export type CallTranscriptEntryV2MediumEnum = typeof CallTranscriptEntryV2MediumEnum[keyof typeof CallTranscriptEntryV2MediumEnum];


/**
 * Check if a given object implements the CallTranscriptEntryV2 interface.
 */
export function instanceOfCallTranscriptEntryV2(value: object): value is CallTranscriptEntryV2 {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('medium' in value) || value['medium'] === undefined) return false;
    if (!('participant_name' in value) || value['participant_name'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function CallTranscriptEntryV2FromJSON(json: any): CallTranscriptEntryV2 {
    return CallTranscriptEntryV2FromJSONTyped(json, false);
}

export function CallTranscriptEntryV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CallTranscriptEntryV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'id': json['id'],
        'medium': json['medium'],
        'participant_name': json['participant_name'],
        'timestamp': (json['timestamp'] == null ? json['timestamp'] : parseDateTime(json['timestamp'])),
    };
}

export function CallTranscriptEntryV2ToJSON(json: any): CallTranscriptEntryV2 {
    return CallTranscriptEntryV2ToJSONTyped(json, false);
}

export function CallTranscriptEntryV2ToJSONTyped(value?: CallTranscriptEntryV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'id': value['id'],
        'medium': value['medium'],
        'participant_name': value['participant_name'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : serializeDateTime(value['timestamp']),
    };
}

