/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { CallRouteOptionV2 } from './CallRouteOptionV2.js';
import {
    CallRouteOptionV2FromJSON,
    CallRouteOptionV2FromJSONTyped,
    CallRouteOptionV2ToJSON,
    CallRouteOptionV2ToJSONTyped,
} from './CallRouteOptionV2.js';
import type { CallRoutePathNodeV2 } from './CallRoutePathNodeV2.js';
import {
    CallRoutePathNodeV2FromJSON,
    CallRoutePathNodeV2FromJSONTyped,
    CallRoutePathNodeV2ToJSON,
    CallRoutePathNodeV2ToJSONTyped,
} from './CallRoutePathNodeV2.js';
import type { CallRouteAllowedCallerV2 } from './CallRouteAllowedCallerV2.js';
import {
    CallRouteAllowedCallerV2FromJSON,
    CallRouteAllowedCallerV2FromJSONTyped,
    CallRouteAllowedCallerV2ToJSON,
    CallRouteAllowedCallerV2ToJSONTyped,
} from './CallRouteAllowedCallerV2.js';

/**
 * A call route is a phone number your customers can call to reach whoever is
 * on call, for an urgent support line or a regulator hotline.
 * 
 * When a call comes in we work down the route's path, ringing each level's targets
 * in turn until someone answers, then connect them to the caller. A trailing
 * voicemail node records a message instead. Every call raises an alert, so calls
 * can open incidents through an alert route.
 * 
 * List and edit call routes here. Create and delete them in the dashboard.
 * @export
 * @interface CallRouteV2
 */
export interface CallRouteV2 {
    /**
     * The numbers allowed to call this route. Only enforced when use_caller_allowlist is true.
     */
    allowed_callers: Array<CallRouteAllowedCallerV2>;
    /**
     * The country this route's number belongs to
     */
    country_code?: string;
    /**
     * 
     */
    created_at: Date;
    /**
     * Where this route is in provisioning. Only an active route answers calls:
     * * pending: created, and awaiting manual work from us
     * * pending_regulatory_information: awaiting regulatory compliance information, collected in the dashboard
     * * pending_number: compliance is settled, and we're provisioning a number
     * * active: fully provisioned, and answering calls
     */
    current_state: CallRouteV2CurrentStateEnum;
    /**
     * The language we speak voice prompts in, via text-to-speech
     */
    custom_language: CallRouteV2CustomLanguageEnum;
    /**
     * Unique identifier for this call route
     */
    id: string;
    /**
     * Name for this call route
     */
    name: string;
    /**
     * The phone-tree menu this route presents. Empty when callers are routed down the route's path.
     */
    options: Array<CallRouteOptionV2>;
    /**
     * Who we page when a call comes in. Empty when this route presents a phone-tree menu, in which case each menu option carries its own path.
     */
    path: Array<CallRoutePathNodeV2>;
    /**
     * The number your customers call to reach this route, once one has been provisioned
     */
    phone_number?: string;
    /**
     * The type of phone number, which determines the regulatory requirements for provisioning it
     */
    phone_number_type?: CallRouteV2PhoneNumberTypeEnum;
    /**
     * Which number responders see when we call them:
     * * route_number: this route's own number
     * * oncall_number: an incident.io on-call number
     */
    responder_caller_id: CallRouteV2ResponderCallerIdEnum;
    /**
     * 
     */
    updated_at: Date;
    /**
     * Whether this route only answers calls from its allowed callers
     */
    use_caller_allowlist: boolean;
}


/**
 * @export
 */
export const CallRouteV2CurrentStateEnum = {
    Pending: 'pending',
    PendingRegulatoryInformation: 'pending_regulatory_information',
    PendingNumber: 'pending_number',
    Active: 'active',
} as const;
export type CallRouteV2CurrentStateEnum = typeof CallRouteV2CurrentStateEnum[keyof typeof CallRouteV2CurrentStateEnum];

/**
 * @export
 */
export const CallRouteV2CustomLanguageEnum = {
    EnUs: 'en-US',
    EnGb: 'en-GB',
    FrFr: 'fr-FR',
    EsEs: 'es-ES',
    PtPt: 'pt-PT',
    PtBr: 'pt-BR',
    DeDe: 'de-DE',
    NlNl: 'nl-NL',
} as const;
export type CallRouteV2CustomLanguageEnum = typeof CallRouteV2CustomLanguageEnum[keyof typeof CallRouteV2CustomLanguageEnum];

/**
 * @export
 */
export const CallRouteV2PhoneNumberTypeEnum = {
    TollFree: 'toll_free',
    Mobile: 'mobile',
    National: 'national',
    Local: 'local',
} as const;
export type CallRouteV2PhoneNumberTypeEnum = typeof CallRouteV2PhoneNumberTypeEnum[keyof typeof CallRouteV2PhoneNumberTypeEnum];

/**
 * @export
 */
export const CallRouteV2ResponderCallerIdEnum = {
    RouteNumber: 'route_number',
    OncallNumber: 'oncall_number',
} as const;
export type CallRouteV2ResponderCallerIdEnum = typeof CallRouteV2ResponderCallerIdEnum[keyof typeof CallRouteV2ResponderCallerIdEnum];


/**
 * Check if a given object implements the CallRouteV2 interface.
 */
export function instanceOfCallRouteV2(value: object): value is CallRouteV2 {
    if (!('allowed_callers' in value) || value['allowed_callers'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('current_state' in value) || value['current_state'] === undefined) return false;
    if (!('custom_language' in value) || value['custom_language'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('responder_caller_id' in value) || value['responder_caller_id'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    if (!('use_caller_allowlist' in value) || value['use_caller_allowlist'] === undefined) return false;
    return true;
}

export function CallRouteV2FromJSON(json: any): CallRouteV2 {
    return CallRouteV2FromJSONTyped(json, false);
}

export function CallRouteV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CallRouteV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'allowed_callers': ((json['allowed_callers'] as Array<any>).map(CallRouteAllowedCallerV2FromJSON)),
        'country_code': json['country_code'] == null ? undefined : json['country_code'],
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'current_state': json['current_state'],
        'custom_language': json['custom_language'],
        'id': json['id'],
        'name': json['name'],
        'options': ((json['options'] as Array<any>).map(CallRouteOptionV2FromJSON)),
        'path': ((json['path'] as Array<any>).map(CallRoutePathNodeV2FromJSON)),
        'phone_number': json['phone_number'] == null ? undefined : json['phone_number'],
        'phone_number_type': json['phone_number_type'] == null ? undefined : json['phone_number_type'],
        'responder_caller_id': json['responder_caller_id'],
        'updated_at': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'use_caller_allowlist': json['use_caller_allowlist'],
    };
}

export function CallRouteV2ToJSON(json: any): CallRouteV2 {
    return CallRouteV2ToJSONTyped(json, false);
}

export function CallRouteV2ToJSONTyped(value?: CallRouteV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed_callers': ((value['allowed_callers'] as Array<any>).map(CallRouteAllowedCallerV2ToJSON)),
        'country_code': value['country_code'],
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'current_state': value['current_state'],
        'custom_language': value['custom_language'],
        'id': value['id'],
        'name': value['name'],
        'options': ((value['options'] as Array<any>).map(CallRouteOptionV2ToJSON)),
        'path': ((value['path'] as Array<any>).map(CallRoutePathNodeV2ToJSON)),
        'phone_number': value['phone_number'],
        'phone_number_type': value['phone_number_type'],
        'responder_caller_id': value['responder_caller_id'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
        'use_caller_allowlist': value['use_caller_allowlist'],
    };
}

