/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CatalogTypeAttributePathItemPayloadV3
 */
export interface CatalogTypeAttributePathItemPayloadV3 {
    /**
     * the ID of the attribute to use
     */
    attribute_id: string;
}

/**
 * Check if a given object implements the CatalogTypeAttributePathItemPayloadV3 interface.
 */
export function instanceOfCatalogTypeAttributePathItemPayloadV3(value: object): value is CatalogTypeAttributePathItemPayloadV3 {
    if (!('attribute_id' in value) || value['attribute_id'] === undefined) return false;
    return true;
}

export function CatalogTypeAttributePathItemPayloadV3FromJSON(json: any): CatalogTypeAttributePathItemPayloadV3 {
    return CatalogTypeAttributePathItemPayloadV3FromJSONTyped(json, false);
}

export function CatalogTypeAttributePathItemPayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogTypeAttributePathItemPayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'attribute_id': json['attribute_id'],
    };
}

export function CatalogTypeAttributePathItemPayloadV3ToJSON(json: any): CatalogTypeAttributePathItemPayloadV3 {
    return CatalogTypeAttributePathItemPayloadV3ToJSONTyped(json, false);
}

export function CatalogTypeAttributePathItemPayloadV3ToJSONTyped(value?: CatalogTypeAttributePathItemPayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute_id': value['attribute_id'],
    };
}

