/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CatalogEngineParamBindingValuePayloadV3 } from './CatalogEngineParamBindingValuePayloadV3.js';
import {
    CatalogEngineParamBindingValuePayloadV3FromJSON,
    CatalogEngineParamBindingValuePayloadV3FromJSONTyped,
    CatalogEngineParamBindingValuePayloadV3ToJSON,
    CatalogEngineParamBindingValuePayloadV3ToJSONTyped,
} from './CatalogEngineParamBindingValuePayloadV3.js';

/**
 * 
 * @export
 * @interface CatalogEngineParamBindingPayloadV3
 */
export interface CatalogEngineParamBindingPayloadV3 {
    /**
     * If set, this is the array value of the step parameter
     */
    array_value?: Array<CatalogEngineParamBindingValuePayloadV3>;
    /**
     * 
     */
    value?: CatalogEngineParamBindingValuePayloadV3;
}

/**
 * Check if a given object implements the CatalogEngineParamBindingPayloadV3 interface.
 */
export function instanceOfCatalogEngineParamBindingPayloadV3(value: object): value is CatalogEngineParamBindingPayloadV3 {
    return true;
}

export function CatalogEngineParamBindingPayloadV3FromJSON(json: any): CatalogEngineParamBindingPayloadV3 {
    return CatalogEngineParamBindingPayloadV3FromJSONTyped(json, false);
}

export function CatalogEngineParamBindingPayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogEngineParamBindingPayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'array_value': json['array_value'] == null ? undefined : ((json['array_value'] as Array<any>).map(CatalogEngineParamBindingValuePayloadV3FromJSON)),
        'value': json['value'] == null ? undefined : CatalogEngineParamBindingValuePayloadV3FromJSON(json['value']),
    };
}

export function CatalogEngineParamBindingPayloadV3ToJSON(json: any): CatalogEngineParamBindingPayloadV3 {
    return CatalogEngineParamBindingPayloadV3ToJSONTyped(json, false);
}

export function CatalogEngineParamBindingPayloadV3ToJSONTyped(value?: CatalogEngineParamBindingPayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'array_value': value['array_value'] == null ? undefined : ((value['array_value'] as Array<any>).map(CatalogEngineParamBindingValuePayloadV3ToJSON)),
        'value': CatalogEngineParamBindingValuePayloadV3ToJSON(value['value']),
    };
}

