/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CatalogTypeAttributePathItemV2 } from './CatalogTypeAttributePathItemV2.js';
import {
    CatalogTypeAttributePathItemV2FromJSON,
    CatalogTypeAttributePathItemV2FromJSONTyped,
    CatalogTypeAttributePathItemV2ToJSON,
    CatalogTypeAttributePathItemV2ToJSONTyped,
} from './CatalogTypeAttributePathItemV2.js';

/**
 * 
 * @export
 * @interface CatalogTypeAttributeV2
 */
export interface CatalogTypeAttributeV2 {
    /**
     * Whether this attribute is an array
     */
    array: boolean;
    /**
     * The attribute to use (if this is a backlink)
     */
    backlink_attribute?: string;
    /**
     * The ID of this attribute
     */
    id: string;
    /**
     * Controls how this attribute is modified
     */
    mode: CatalogTypeAttributeV2ModeEnum;
    /**
     * Unique name of this attribute
     */
    name: string;
    /**
     * The path to use (if this is a path attribute)
     */
    path?: Array<CatalogTypeAttributePathItemV2>;
    /**
     * Catalog type name for this attribute
     */
    type: string;
}


/**
 * @export
 */
export const CatalogTypeAttributeV2ModeEnum = {
    Empty: '',
    Manual: 'manual',
    External: 'external',
    Internal: 'internal',
    Dynamic: 'dynamic',
    Backlink: 'backlink',
    Path: 'path',
} as const;
export type CatalogTypeAttributeV2ModeEnum = typeof CatalogTypeAttributeV2ModeEnum[keyof typeof CatalogTypeAttributeV2ModeEnum];


/**
 * Check if a given object implements the CatalogTypeAttributeV2 interface.
 */
export function instanceOfCatalogTypeAttributeV2(value: object): value is CatalogTypeAttributeV2 {
    if (!('array' in value) || value['array'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CatalogTypeAttributeV2FromJSON(json: any): CatalogTypeAttributeV2 {
    return CatalogTypeAttributeV2FromJSONTyped(json, false);
}

export function CatalogTypeAttributeV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogTypeAttributeV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'array': json['array'],
        'backlink_attribute': json['backlink_attribute'] == null ? undefined : json['backlink_attribute'],
        'id': json['id'],
        'mode': json['mode'],
        'name': json['name'],
        'path': json['path'] == null ? undefined : ((json['path'] as Array<any>).map(CatalogTypeAttributePathItemV2FromJSON)),
        'type': json['type'],
    };
}

export function CatalogTypeAttributeV2ToJSON(json: any): CatalogTypeAttributeV2 {
    return CatalogTypeAttributeV2ToJSONTyped(json, false);
}

export function CatalogTypeAttributeV2ToJSONTyped(value?: CatalogTypeAttributeV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'array': value['array'],
        'backlink_attribute': value['backlink_attribute'],
        'id': value['id'],
        'mode': value['mode'],
        'name': value['name'],
        'path': value['path'] == null ? undefined : ((value['path'] as Array<any>).map(CatalogTypeAttributePathItemV2ToJSON)),
        'type': value['type'],
    };
}

