/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CatalogEntryV2 } from './CatalogEntryV2.js';
import {
    CatalogEntryV2FromJSON,
    CatalogEntryV2FromJSONTyped,
    CatalogEntryV2ToJSON,
    CatalogEntryV2ToJSONTyped,
} from './CatalogEntryV2.js';
import type { CatalogTypeV2 } from './CatalogTypeV2.js';
import {
    CatalogTypeV2FromJSON,
    CatalogTypeV2FromJSONTyped,
    CatalogTypeV2ToJSON,
    CatalogTypeV2ToJSONTyped,
} from './CatalogTypeV2.js';

/**
 * 
 * @export
 * @interface CatalogUpdateEntryResultV2
 */
export interface CatalogUpdateEntryResultV2 {
    /**
     * 
     */
    catalog_entry: CatalogEntryV2;
    /**
     * 
     */
    catalog_type: CatalogTypeV2;
}

/**
 * Check if a given object implements the CatalogUpdateEntryResultV2 interface.
 */
export function instanceOfCatalogUpdateEntryResultV2(value: object): value is CatalogUpdateEntryResultV2 {
    if (!('catalog_entry' in value) || value['catalog_entry'] === undefined) return false;
    if (!('catalog_type' in value) || value['catalog_type'] === undefined) return false;
    return true;
}

export function CatalogUpdateEntryResultV2FromJSON(json: any): CatalogUpdateEntryResultV2 {
    return CatalogUpdateEntryResultV2FromJSONTyped(json, false);
}

export function CatalogUpdateEntryResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogUpdateEntryResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'catalog_entry': CatalogEntryV2FromJSON(json['catalog_entry']),
        'catalog_type': CatalogTypeV2FromJSON(json['catalog_type']),
    };
}

export function CatalogUpdateEntryResultV2ToJSON(json: any): CatalogUpdateEntryResultV2 {
    return CatalogUpdateEntryResultV2ToJSONTyped(json, false);
}

export function CatalogUpdateEntryResultV2ToJSONTyped(value?: CatalogUpdateEntryResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catalog_entry': CatalogEntryV2ToJSON(value['catalog_entry']),
        'catalog_type': CatalogTypeV2ToJSON(value['catalog_type']),
    };
}

