/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CatalogCreateTypePayloadV3
 */
export interface CatalogCreateTypePayloadV3 {
    /**
     * Annotations that can track metadata about this type
     */
    annotations?: { [key: string]: string; };
    /**
     * What categories is this type considered part of
     */
    categories?: Array<CatalogCreateTypePayloadV3CategoriesEnum>;
    /**
     * Sets the display color of this type in the dashboard
     */
    color?: CatalogCreateTypePayloadV3ColorEnum;
    /**
     * Human readble description of this type
     */
    description: string;
    /**
     * Sets the display icon of this type in the dashboard
     */
    icon?: CatalogCreateTypePayloadV3IconEnum;
    /**
     * Name is the human readable name of this type
     */
    name: string;
    /**
     * IDs of the teams that own this catalog type
     */
    owning_team_ids?: Array<string>;
    /**
     * If this type should be ranked
     */
    ranked?: boolean;
    /**
     * The url of the external repository where this type is managed
     */
    source_repo_url?: string;
    /**
     * The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"]
     */
    type_name?: string;
    /**
     * If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
     */
    use_name_as_identifier?: boolean;
}


/**
 * @export
 */
export const CatalogCreateTypePayloadV3CategoriesEnum = {
    Customer: 'customer',
    IssueTracker: 'issue-tracker',
    ProductFeature: 'product-feature',
    Service: 'service',
    OnCall: 'on-call',
    Team: 'team',
    User: 'user',
} as const;
export type CatalogCreateTypePayloadV3CategoriesEnum = typeof CatalogCreateTypePayloadV3CategoriesEnum[keyof typeof CatalogCreateTypePayloadV3CategoriesEnum];

/**
 * @export
 */
export const CatalogCreateTypePayloadV3ColorEnum = {
    Yellow: 'yellow',
    Green: 'green',
    Blue: 'blue',
    Violet: 'violet',
    Pink: 'pink',
    Cyan: 'cyan',
    Orange: 'orange',
} as const;
export type CatalogCreateTypePayloadV3ColorEnum = typeof CatalogCreateTypePayloadV3ColorEnum[keyof typeof CatalogCreateTypePayloadV3ColorEnum];

/**
 * @export
 */
export const CatalogCreateTypePayloadV3IconEnum = {
    Alert: 'alert',
    Bolt: 'bolt',
    Box: 'box',
    Briefcase: 'briefcase',
    Browser: 'browser',
    Bulb: 'bulb',
    Calendar: 'calendar',
    Clock: 'clock',
    Cog: 'cog',
    Components: 'components',
    Database: 'database',
    Doc: 'doc',
    Email: 'email',
    EscalationPath: 'escalation-path',
    Files: 'files',
    Flag: 'flag',
    Folder: 'folder',
    Globe: 'globe',
    IncidentTemplate: 'incident-template',
    Money: 'money',
    Server: 'server',
    Severity: 'severity',
    StatusPage: 'status-page',
    Store: 'store',
    Star: 'star',
    Tag: 'tag',
    User: 'user',
    Users: 'users',
} as const;
export type CatalogCreateTypePayloadV3IconEnum = typeof CatalogCreateTypePayloadV3IconEnum[keyof typeof CatalogCreateTypePayloadV3IconEnum];


/**
 * Check if a given object implements the CatalogCreateTypePayloadV3 interface.
 */
export function instanceOfCatalogCreateTypePayloadV3(value: object): value is CatalogCreateTypePayloadV3 {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CatalogCreateTypePayloadV3FromJSON(json: any): CatalogCreateTypePayloadV3 {
    return CatalogCreateTypePayloadV3FromJSONTyped(json, false);
}

export function CatalogCreateTypePayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogCreateTypePayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'annotations': json['annotations'] == null ? undefined : json['annotations'],
        'categories': json['categories'] == null ? undefined : json['categories'],
        'color': json['color'] == null ? undefined : json['color'],
        'description': json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'name': json['name'],
        'owning_team_ids': json['owning_team_ids'] == null ? undefined : json['owning_team_ids'],
        'ranked': json['ranked'] == null ? undefined : json['ranked'],
        'source_repo_url': json['source_repo_url'] == null ? undefined : json['source_repo_url'],
        'type_name': json['type_name'] == null ? undefined : json['type_name'],
        'use_name_as_identifier': json['use_name_as_identifier'] == null ? undefined : json['use_name_as_identifier'],
    };
}

export function CatalogCreateTypePayloadV3ToJSON(json: any): CatalogCreateTypePayloadV3 {
    return CatalogCreateTypePayloadV3ToJSONTyped(json, false);
}

export function CatalogCreateTypePayloadV3ToJSONTyped(value?: CatalogCreateTypePayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'annotations': value['annotations'],
        'categories': value['categories'],
        'color': value['color'],
        'description': value['description'],
        'icon': value['icon'],
        'name': value['name'],
        'owning_team_ids': value['owning_team_ids'],
        'ranked': value['ranked'],
        'source_repo_url': value['source_repo_url'],
        'type_name': value['type_name'],
        'use_name_as_identifier': value['use_name_as_identifier'],
    };
}

