/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CatalogEngineParamBindingValuePayloadV3
 */
export interface CatalogEngineParamBindingValuePayloadV3 {
    /**
     * If set, this is the literal value of the step parameter
     */
    literal?: string;
}

/**
 * Check if a given object implements the CatalogEngineParamBindingValuePayloadV3 interface.
 */
export function instanceOfCatalogEngineParamBindingValuePayloadV3(value: object): value is CatalogEngineParamBindingValuePayloadV3 {
    return true;
}

export function CatalogEngineParamBindingValuePayloadV3FromJSON(json: any): CatalogEngineParamBindingValuePayloadV3 {
    return CatalogEngineParamBindingValuePayloadV3FromJSONTyped(json, false);
}

export function CatalogEngineParamBindingValuePayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogEngineParamBindingValuePayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'literal': json['literal'] == null ? undefined : json['literal'],
    };
}

export function CatalogEngineParamBindingValuePayloadV3ToJSON(json: any): CatalogEngineParamBindingValuePayloadV3 {
    return CatalogEngineParamBindingValuePayloadV3ToJSONTyped(json, false);
}

export function CatalogEngineParamBindingValuePayloadV3ToJSONTyped(value?: CatalogEngineParamBindingValuePayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'literal': value['literal'],
    };
}

