/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CustomFieldFixedFilterOptionsV2
 */
export interface CustomFieldFixedFilterOptionsV2 {
    /**
     * This must be an attribute of the catalog type of this custom field. It must be an attribute that points to another catalog type (so not a plain string, number, or boolean attribute).
     */
    catalog_attribute_id: string;
    /**
     * The catalog entry IDs (of the type the attribute points at) that the attribute must reference. The options for this custom field are restricted to entries matching one of these values.
     */
    values: Array<string>;
}

/**
 * Check if a given object implements the CustomFieldFixedFilterOptionsV2 interface.
 */
export function instanceOfCustomFieldFixedFilterOptionsV2(value: object): value is CustomFieldFixedFilterOptionsV2 {
    if (!('catalog_attribute_id' in value) || value['catalog_attribute_id'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function CustomFieldFixedFilterOptionsV2FromJSON(json: any): CustomFieldFixedFilterOptionsV2 {
    return CustomFieldFixedFilterOptionsV2FromJSONTyped(json, false);
}

export function CustomFieldFixedFilterOptionsV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomFieldFixedFilterOptionsV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'catalog_attribute_id': json['catalog_attribute_id'],
        'values': json['values'],
    };
}

export function CustomFieldFixedFilterOptionsV2ToJSON(json: any): CustomFieldFixedFilterOptionsV2 {
    return CustomFieldFixedFilterOptionsV2ToJSONTyped(json, false);
}

export function CustomFieldFixedFilterOptionsV2ToJSONTyped(value?: CustomFieldFixedFilterOptionsV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catalog_attribute_id': value['catalog_attribute_id'],
        'values': value['values'],
    };
}

