/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CustomFieldV2 } from './CustomFieldV2.js';
import {
    CustomFieldV2FromJSON,
    CustomFieldV2FromJSONTyped,
    CustomFieldV2ToJSON,
    CustomFieldV2ToJSONTyped,
} from './CustomFieldV2.js';

/**
 * 
 * @export
 * @interface CustomFieldsListResultV2
 */
export interface CustomFieldsListResultV2 {
    /**
     * 
     */
    custom_fields: Array<CustomFieldV2>;
}

/**
 * Check if a given object implements the CustomFieldsListResultV2 interface.
 */
export function instanceOfCustomFieldsListResultV2(value: object): value is CustomFieldsListResultV2 {
    if (!('custom_fields' in value) || value['custom_fields'] === undefined) return false;
    return true;
}

export function CustomFieldsListResultV2FromJSON(json: any): CustomFieldsListResultV2 {
    return CustomFieldsListResultV2FromJSONTyped(json, false);
}

export function CustomFieldsListResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomFieldsListResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'custom_fields': ((json['custom_fields'] as Array<any>).map(CustomFieldV2FromJSON)),
    };
}

export function CustomFieldsListResultV2ToJSON(json: any): CustomFieldsListResultV2 {
    return CustomFieldsListResultV2ToJSONTyped(json, false);
}

export function CustomFieldsListResultV2ToJSONTyped(value?: CustomFieldsListResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_fields': ((value['custom_fields'] as Array<any>).map(CustomFieldV2ToJSON)),
    };
}

