/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EscalationPathV2 } from './EscalationPathV2.js';
import {
    EscalationPathV2FromJSON,
    EscalationPathV2FromJSONTyped,
    EscalationPathV2ToJSON,
    EscalationPathV2ToJSONTyped,
} from './EscalationPathV2.js';

/**
 * 
 * @export
 * @interface EscalationsUpdatePathResultV2
 */
export interface EscalationsUpdatePathResultV2 {
    /**
     * 
     */
    escalation_path: EscalationPathV2;
}

/**
 * Check if a given object implements the EscalationsUpdatePathResultV2 interface.
 */
export function instanceOfEscalationsUpdatePathResultV2(value: object): value is EscalationsUpdatePathResultV2 {
    if (!('escalation_path' in value) || value['escalation_path'] === undefined) return false;
    return true;
}

export function EscalationsUpdatePathResultV2FromJSON(json: any): EscalationsUpdatePathResultV2 {
    return EscalationsUpdatePathResultV2FromJSONTyped(json, false);
}

export function EscalationsUpdatePathResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): EscalationsUpdatePathResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'escalation_path': EscalationPathV2FromJSON(json['escalation_path']),
    };
}

export function EscalationsUpdatePathResultV2ToJSON(json: any): EscalationsUpdatePathResultV2 {
    return EscalationsUpdatePathResultV2ToJSONTyped(json, false);
}

export function EscalationsUpdatePathResultV2ToJSONTyped(value?: EscalationsUpdatePathResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'escalation_path': EscalationPathV2ToJSON(value['escalation_path']),
    };
}

