/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EscalationPathRoundRobinConfigV2 } from './EscalationPathRoundRobinConfigV2.js';
import {
    EscalationPathRoundRobinConfigV2FromJSON,
    EscalationPathRoundRobinConfigV2FromJSONTyped,
    EscalationPathRoundRobinConfigV2ToJSON,
    EscalationPathRoundRobinConfigV2ToJSONTyped,
} from './EscalationPathRoundRobinConfigV2.js';
import type { EscalationPathRetryConfigV2 } from './EscalationPathRetryConfigV2.js';
import {
    EscalationPathRetryConfigV2FromJSON,
    EscalationPathRetryConfigV2FromJSONTyped,
    EscalationPathRetryConfigV2ToJSON,
    EscalationPathRetryConfigV2ToJSONTyped,
} from './EscalationPathRetryConfigV2.js';
import type { EscalationPathTargetWithBindingPayloadV2 } from './EscalationPathTargetWithBindingPayloadV2.js';
import {
    EscalationPathTargetWithBindingPayloadV2FromJSON,
    EscalationPathTargetWithBindingPayloadV2FromJSONTyped,
    EscalationPathTargetWithBindingPayloadV2ToJSON,
    EscalationPathTargetWithBindingPayloadV2ToJSONTyped,
} from './EscalationPathTargetWithBindingPayloadV2.js';

/**
 * 
 * @export
 * @interface EscalationPathNodeLevelWithBindingPayloadV2
 */
export interface EscalationPathNodeLevelWithBindingPayloadV2 {
    /**
     * Controls the behaviour of acknowledgements for this level, with 'first' cancelling all other escalations on the same level when someone acks
     */
    ack_mode?: EscalationPathNodeLevelWithBindingPayloadV2AckModeEnum;
    /**
     * 
     */
    retry_config?: EscalationPathRetryConfigV2;
    /**
     * 
     */
    round_robin_config?: EscalationPathRoundRobinConfigV2;
    /**
     * The targets (users or schedules), each concrete or a parameter binding.
     */
    targets: Array<EscalationPathTargetWithBindingPayloadV2>;
    /**
     * If the time to ack is relative to a time window, this defines whether we move when the window is active or inactive
     */
    time_to_ack_interval_condition?: EscalationPathNodeLevelWithBindingPayloadV2TimeToAckIntervalConditionEnum;
    /**
     * How long should we wait for this level to acknowledge before proceeding to the next node in the path?
     */
    time_to_ack_seconds?: number;
    /**
     * If the time to ack is relative to a time window, this identifies which window it is relative to
     */
    time_to_ack_weekday_interval_config_id?: string;
}


/**
 * @export
 */
export const EscalationPathNodeLevelWithBindingPayloadV2AckModeEnum = {
    All: 'all',
    First: 'first',
} as const;
export type EscalationPathNodeLevelWithBindingPayloadV2AckModeEnum = typeof EscalationPathNodeLevelWithBindingPayloadV2AckModeEnum[keyof typeof EscalationPathNodeLevelWithBindingPayloadV2AckModeEnum];

/**
 * @export
 */
export const EscalationPathNodeLevelWithBindingPayloadV2TimeToAckIntervalConditionEnum = {
    Active: 'active',
    Inactive: 'inactive',
} as const;
export type EscalationPathNodeLevelWithBindingPayloadV2TimeToAckIntervalConditionEnum = typeof EscalationPathNodeLevelWithBindingPayloadV2TimeToAckIntervalConditionEnum[keyof typeof EscalationPathNodeLevelWithBindingPayloadV2TimeToAckIntervalConditionEnum];


/**
 * Check if a given object implements the EscalationPathNodeLevelWithBindingPayloadV2 interface.
 */
export function instanceOfEscalationPathNodeLevelWithBindingPayloadV2(value: object): value is EscalationPathNodeLevelWithBindingPayloadV2 {
    if (!('targets' in value) || value['targets'] === undefined) return false;
    return true;
}

export function EscalationPathNodeLevelWithBindingPayloadV2FromJSON(json: any): EscalationPathNodeLevelWithBindingPayloadV2 {
    return EscalationPathNodeLevelWithBindingPayloadV2FromJSONTyped(json, false);
}

export function EscalationPathNodeLevelWithBindingPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): EscalationPathNodeLevelWithBindingPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'ack_mode': json['ack_mode'] == null ? undefined : json['ack_mode'],
        'retry_config': json['retry_config'] == null ? undefined : EscalationPathRetryConfigV2FromJSON(json['retry_config']),
        'round_robin_config': json['round_robin_config'] == null ? undefined : EscalationPathRoundRobinConfigV2FromJSON(json['round_robin_config']),
        'targets': ((json['targets'] as Array<any>).map(EscalationPathTargetWithBindingPayloadV2FromJSON)),
        'time_to_ack_interval_condition': json['time_to_ack_interval_condition'] == null ? undefined : json['time_to_ack_interval_condition'],
        'time_to_ack_seconds': json['time_to_ack_seconds'] == null ? undefined : json['time_to_ack_seconds'],
        'time_to_ack_weekday_interval_config_id': json['time_to_ack_weekday_interval_config_id'] == null ? undefined : json['time_to_ack_weekday_interval_config_id'],
    };
}

export function EscalationPathNodeLevelWithBindingPayloadV2ToJSON(json: any): EscalationPathNodeLevelWithBindingPayloadV2 {
    return EscalationPathNodeLevelWithBindingPayloadV2ToJSONTyped(json, false);
}

export function EscalationPathNodeLevelWithBindingPayloadV2ToJSONTyped(value?: EscalationPathNodeLevelWithBindingPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ack_mode': value['ack_mode'],
        'retry_config': EscalationPathRetryConfigV2ToJSON(value['retry_config']),
        'round_robin_config': EscalationPathRoundRobinConfigV2ToJSON(value['round_robin_config']),
        'targets': ((value['targets'] as Array<any>).map(EscalationPathTargetWithBindingPayloadV2ToJSON)),
        'time_to_ack_interval_condition': value['time_to_ack_interval_condition'],
        'time_to_ack_seconds': value['time_to_ack_seconds'],
        'time_to_ack_weekday_interval_config_id': value['time_to_ack_weekday_interval_config_id'],
    };
}

