/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EscalationPathRepeatConfigV2
 */
export interface EscalationPathRepeatConfigV2 {
    /**
     * When true, incident activity resets the repeat timer.
     */
    delay_repeat_on_activity: boolean;
    /**
     * Number of seconds we'll wait before repeating an escalation.
     */
    repeat_after_seconds: number;
}

/**
 * Check if a given object implements the EscalationPathRepeatConfigV2 interface.
 */
export function instanceOfEscalationPathRepeatConfigV2(value: object): value is EscalationPathRepeatConfigV2 {
    if (!('delay_repeat_on_activity' in value) || value['delay_repeat_on_activity'] === undefined) return false;
    if (!('repeat_after_seconds' in value) || value['repeat_after_seconds'] === undefined) return false;
    return true;
}

export function EscalationPathRepeatConfigV2FromJSON(json: any): EscalationPathRepeatConfigV2 {
    return EscalationPathRepeatConfigV2FromJSONTyped(json, false);
}

export function EscalationPathRepeatConfigV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): EscalationPathRepeatConfigV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'delay_repeat_on_activity': json['delay_repeat_on_activity'],
        'repeat_after_seconds': json['repeat_after_seconds'],
    };
}

export function EscalationPathRepeatConfigV2ToJSON(json: any): EscalationPathRepeatConfigV2 {
    return EscalationPathRepeatConfigV2ToJSONTyped(json, false);
}

export function EscalationPathRepeatConfigV2ToJSONTyped(value?: EscalationPathRepeatConfigV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delay_repeat_on_activity': value['delay_repeat_on_activity'],
        'repeat_after_seconds': value['repeat_after_seconds'],
    };
}

