/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface EscalationRespondSnoozeDetailsPayloadV2
 */
export interface EscalationRespondSnoozeDetailsPayloadV2 {
    /**
     * Optional reason for snoozing the escalation
     */
    reason?: string;
    /**
     * The time at which the snooze should end
     */
    snooze_until: Date;
}

/**
 * Check if a given object implements the EscalationRespondSnoozeDetailsPayloadV2 interface.
 */
export function instanceOfEscalationRespondSnoozeDetailsPayloadV2(value: object): value is EscalationRespondSnoozeDetailsPayloadV2 {
    if (!('snooze_until' in value) || value['snooze_until'] === undefined) return false;
    return true;
}

export function EscalationRespondSnoozeDetailsPayloadV2FromJSON(json: any): EscalationRespondSnoozeDetailsPayloadV2 {
    return EscalationRespondSnoozeDetailsPayloadV2FromJSONTyped(json, false);
}

export function EscalationRespondSnoozeDetailsPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): EscalationRespondSnoozeDetailsPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
        'snooze_until': (json['snooze_until'] == null ? json['snooze_until'] : parseDateTime(json['snooze_until'])),
    };
}

export function EscalationRespondSnoozeDetailsPayloadV2ToJSON(json: any): EscalationRespondSnoozeDetailsPayloadV2 {
    return EscalationRespondSnoozeDetailsPayloadV2ToJSONTyped(json, false);
}

export function EscalationRespondSnoozeDetailsPayloadV2ToJSONTyped(value?: EscalationRespondSnoozeDetailsPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'snooze_until': value['snooze_until'] == null ? value['snooze_until'] : serializeDateTime(value['snooze_until']),
    };
}

