/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExpressionElseBranchPayloadV2 } from './ExpressionElseBranchPayloadV2.js';
import {
    ExpressionElseBranchPayloadV2FromJSON,
    ExpressionElseBranchPayloadV2FromJSONTyped,
    ExpressionElseBranchPayloadV2ToJSON,
    ExpressionElseBranchPayloadV2ToJSONTyped,
} from './ExpressionElseBranchPayloadV2.js';
import type { ExpressionOperationPayloadV2 } from './ExpressionOperationPayloadV2.js';
import {
    ExpressionOperationPayloadV2FromJSON,
    ExpressionOperationPayloadV2FromJSONTyped,
    ExpressionOperationPayloadV2ToJSON,
    ExpressionOperationPayloadV2ToJSONTyped,
} from './ExpressionOperationPayloadV2.js';

/**
 * 
 * @export
 * @interface ExpressionPayloadV2
 */
export interface ExpressionPayloadV2 {
    /**
     * 
     */
    else_branch?: ExpressionElseBranchPayloadV2;
    /**
     * The human readable label of the expression
     */
    label: string;
    /**
     * 
     */
    operations: Array<ExpressionOperationPayloadV2>;
    /**
     * A short ID that can be used to reference the expression
     */
    reference: string;
    /**
     * The root reference for this expression (i.e. where the expression starts)
     */
    root_reference: string;
}

/**
 * Check if a given object implements the ExpressionPayloadV2 interface.
 */
export function instanceOfExpressionPayloadV2(value: object): value is ExpressionPayloadV2 {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('operations' in value) || value['operations'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('root_reference' in value) || value['root_reference'] === undefined) return false;
    return true;
}

export function ExpressionPayloadV2FromJSON(json: any): ExpressionPayloadV2 {
    return ExpressionPayloadV2FromJSONTyped(json, false);
}

export function ExpressionPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'else_branch': json['else_branch'] == null ? undefined : ExpressionElseBranchPayloadV2FromJSON(json['else_branch']),
        'label': json['label'],
        'operations': ((json['operations'] as Array<any>).map(ExpressionOperationPayloadV2FromJSON)),
        'reference': json['reference'],
        'root_reference': json['root_reference'],
    };
}

export function ExpressionPayloadV2ToJSON(json: any): ExpressionPayloadV2 {
    return ExpressionPayloadV2ToJSONTyped(json, false);
}

export function ExpressionPayloadV2ToJSONTyped(value?: ExpressionPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'else_branch': ExpressionElseBranchPayloadV2ToJSON(value['else_branch']),
        'label': value['label'],
        'operations': ((value['operations'] as Array<any>).map(ExpressionOperationPayloadV2ToJSON)),
        'reference': value['reference'],
        'root_reference': value['root_reference'],
    };
}

