/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConditionGroupV2 } from './ConditionGroupV2.js';
import {
    ConditionGroupV2FromJSON,
    ConditionGroupV2FromJSONTyped,
    ConditionGroupV2ToJSON,
    ConditionGroupV2ToJSONTyped,
} from './ConditionGroupV2.js';
import type { EngineParamBindingV2 } from './EngineParamBindingV2.js';
import {
    EngineParamBindingV2FromJSON,
    EngineParamBindingV2FromJSONTyped,
    EngineParamBindingV2ToJSON,
    EngineParamBindingV2ToJSONTyped,
} from './EngineParamBindingV2.js';

/**
 * 
 * @export
 * @interface ExpressionBranchV2
 */
export interface ExpressionBranchV2 {
    /**
     * When one of these condition groups are satisfied, this branch will be evaluated
     */
    condition_groups: Array<ConditionGroupV2>;
    /**
     * 
     */
    result: EngineParamBindingV2;
}

/**
 * Check if a given object implements the ExpressionBranchV2 interface.
 */
export function instanceOfExpressionBranchV2(value: object): value is ExpressionBranchV2 {
    if (!('condition_groups' in value) || value['condition_groups'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ExpressionBranchV2FromJSON(json: any): ExpressionBranchV2 {
    return ExpressionBranchV2FromJSONTyped(json, false);
}

export function ExpressionBranchV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionBranchV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'condition_groups': ((json['condition_groups'] as Array<any>).map(ConditionGroupV2FromJSON)),
        'result': EngineParamBindingV2FromJSON(json['result']),
    };
}

export function ExpressionBranchV2ToJSON(json: any): ExpressionBranchV2 {
    return ExpressionBranchV2ToJSONTyped(json, false);
}

export function ExpressionBranchV2ToJSONTyped(value?: ExpressionBranchV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condition_groups': ((value['condition_groups'] as Array<any>).map(ConditionGroupV2ToJSON)),
        'result': EngineParamBindingV2ToJSON(value['result']),
    };
}

