/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConditionGroupV2 } from './ConditionGroupV2.js';
import {
    ConditionGroupV2FromJSON,
    ConditionGroupV2FromJSONTyped,
    ConditionGroupV2ToJSON,
    ConditionGroupV2ToJSONTyped,
} from './ConditionGroupV2.js';

/**
 * 
 * @export
 * @interface ExpressionFilterOptsV2
 */
export interface ExpressionFilterOptsV2 {
    /**
     * The condition groups to apply in this filter. Only one group needs to be satisfied for the filter to pass.
     */
    condition_groups: Array<ConditionGroupV2>;
}

/**
 * Check if a given object implements the ExpressionFilterOptsV2 interface.
 */
export function instanceOfExpressionFilterOptsV2(value: object): value is ExpressionFilterOptsV2 {
    if (!('condition_groups' in value) || value['condition_groups'] === undefined) return false;
    return true;
}

export function ExpressionFilterOptsV2FromJSON(json: any): ExpressionFilterOptsV2 {
    return ExpressionFilterOptsV2FromJSONTyped(json, false);
}

export function ExpressionFilterOptsV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionFilterOptsV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'condition_groups': ((json['condition_groups'] as Array<any>).map(ConditionGroupV2FromJSON)),
    };
}

export function ExpressionFilterOptsV2ToJSON(json: any): ExpressionFilterOptsV2 {
    return ExpressionFilterOptsV2ToJSONTyped(json, false);
}

export function ExpressionFilterOptsV2ToJSONTyped(value?: ExpressionFilterOptsV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condition_groups': ((value['condition_groups'] as Array<any>).map(ConditionGroupV2ToJSON)),
    };
}

