/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExpressionBranchPayloadV3 } from './ExpressionBranchPayloadV3.js';
import {
    ExpressionBranchPayloadV3FromJSON,
    ExpressionBranchPayloadV3FromJSONTyped,
    ExpressionBranchPayloadV3ToJSON,
    ExpressionBranchPayloadV3ToJSONTyped,
} from './ExpressionBranchPayloadV3.js';
import type { ReturnsMetaV3 } from './ReturnsMetaV3.js';
import {
    ReturnsMetaV3FromJSON,
    ReturnsMetaV3FromJSONTyped,
    ReturnsMetaV3ToJSON,
    ReturnsMetaV3ToJSONTyped,
} from './ReturnsMetaV3.js';

/**
 * 
 * @export
 * @interface ExpressionBranchesOptsPayloadV3
 */
export interface ExpressionBranchesOptsPayloadV3 {
    /**
     * The branches to apply for this operation
     */
    branches: Array<ExpressionBranchPayloadV3>;
    /**
     * 
     */
    returns: ReturnsMetaV3;
}

/**
 * Check if a given object implements the ExpressionBranchesOptsPayloadV3 interface.
 */
export function instanceOfExpressionBranchesOptsPayloadV3(value: object): value is ExpressionBranchesOptsPayloadV3 {
    if (!('branches' in value) || value['branches'] === undefined) return false;
    if (!('returns' in value) || value['returns'] === undefined) return false;
    return true;
}

export function ExpressionBranchesOptsPayloadV3FromJSON(json: any): ExpressionBranchesOptsPayloadV3 {
    return ExpressionBranchesOptsPayloadV3FromJSONTyped(json, false);
}

export function ExpressionBranchesOptsPayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionBranchesOptsPayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'branches': ((json['branches'] as Array<any>).map(ExpressionBranchPayloadV3FromJSON)),
        'returns': ReturnsMetaV3FromJSON(json['returns']),
    };
}

export function ExpressionBranchesOptsPayloadV3ToJSON(json: any): ExpressionBranchesOptsPayloadV3 {
    return ExpressionBranchesOptsPayloadV3ToJSONTyped(json, false);
}

export function ExpressionBranchesOptsPayloadV3ToJSONTyped(value?: ExpressionBranchesOptsPayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branches': ((value['branches'] as Array<any>).map(ExpressionBranchPayloadV3ToJSON)),
        'returns': ReturnsMetaV3ToJSON(value['returns']),
    };
}

