/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConditionGroupPayloadV2 } from './ConditionGroupPayloadV2.js';
import {
    ConditionGroupPayloadV2FromJSON,
    ConditionGroupPayloadV2FromJSONTyped,
    ConditionGroupPayloadV2ToJSON,
    ConditionGroupPayloadV2ToJSONTyped,
} from './ConditionGroupPayloadV2.js';

/**
 * 
 * @export
 * @interface ExpressionFilterOptsPayloadV2
 */
export interface ExpressionFilterOptsPayloadV2 {
    /**
     * The condition groups to apply in this filter. Only one group needs to be satisfied for the filter to pass.
     */
    condition_groups: Array<ConditionGroupPayloadV2>;
}

/**
 * Check if a given object implements the ExpressionFilterOptsPayloadV2 interface.
 */
export function instanceOfExpressionFilterOptsPayloadV2(value: object): value is ExpressionFilterOptsPayloadV2 {
    if (!('condition_groups' in value) || value['condition_groups'] === undefined) return false;
    return true;
}

export function ExpressionFilterOptsPayloadV2FromJSON(json: any): ExpressionFilterOptsPayloadV2 {
    return ExpressionFilterOptsPayloadV2FromJSONTyped(json, false);
}

export function ExpressionFilterOptsPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionFilterOptsPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'condition_groups': ((json['condition_groups'] as Array<any>).map(ConditionGroupPayloadV2FromJSON)),
    };
}

export function ExpressionFilterOptsPayloadV2ToJSON(json: any): ExpressionFilterOptsPayloadV2 {
    return ExpressionFilterOptsPayloadV2ToJSONTyped(json, false);
}

export function ExpressionFilterOptsPayloadV2ToJSONTyped(value?: ExpressionFilterOptsPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condition_groups': ((value['condition_groups'] as Array<any>).map(ConditionGroupPayloadV2ToJSON)),
    };
}

