/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EngineParamBindingV2 } from './EngineParamBindingV2.js';
import {
    EngineParamBindingV2FromJSON,
    EngineParamBindingV2FromJSONTyped,
    EngineParamBindingV2ToJSON,
    EngineParamBindingV2ToJSONTyped,
} from './EngineParamBindingV2.js';

/**
 * 
 * @export
 * @interface ExpressionElseBranchV2
 */
export interface ExpressionElseBranchV2 {
    /**
     * 
     */
    result: EngineParamBindingV2;
}

/**
 * Check if a given object implements the ExpressionElseBranchV2 interface.
 */
export function instanceOfExpressionElseBranchV2(value: object): value is ExpressionElseBranchV2 {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ExpressionElseBranchV2FromJSON(json: any): ExpressionElseBranchV2 {
    return ExpressionElseBranchV2FromJSONTyped(json, false);
}

export function ExpressionElseBranchV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionElseBranchV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'result': EngineParamBindingV2FromJSON(json['result']),
    };
}

export function ExpressionElseBranchV2ToJSON(json: any): ExpressionElseBranchV2 {
    return ExpressionElseBranchV2ToJSONTyped(json, false);
}

export function ExpressionElseBranchV2ToJSONTyped(value?: ExpressionElseBranchV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': EngineParamBindingV2ToJSON(value['result']),
    };
}

