/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ExpressionNavigateOptsV2
 */
export interface ExpressionNavigateOptsV2 {
    /**
     * The reference within the scope to navigate to
     */
    reference: string;
    /**
     * The name of the reference to navigate to
     */
    reference_label: string;
}

/**
 * Check if a given object implements the ExpressionNavigateOptsV2 interface.
 */
export function instanceOfExpressionNavigateOptsV2(value: object): value is ExpressionNavigateOptsV2 {
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('reference_label' in value) || value['reference_label'] === undefined) return false;
    return true;
}

export function ExpressionNavigateOptsV2FromJSON(json: any): ExpressionNavigateOptsV2 {
    return ExpressionNavigateOptsV2FromJSONTyped(json, false);
}

export function ExpressionNavigateOptsV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionNavigateOptsV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'reference': json['reference'],
        'reference_label': json['reference_label'],
    };
}

export function ExpressionNavigateOptsV2ToJSON(json: any): ExpressionNavigateOptsV2 {
    return ExpressionNavigateOptsV2ToJSONTyped(json, false);
}

export function ExpressionNavigateOptsV2ToJSONTyped(value?: ExpressionNavigateOptsV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference': value['reference'],
        'reference_label': value['reference_label'],
    };
}

