/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EngineParamBindingPayloadV2 } from './EngineParamBindingPayloadV2.js';
import {
    EngineParamBindingPayloadV2FromJSON,
    EngineParamBindingPayloadV2FromJSONTyped,
    EngineParamBindingPayloadV2ToJSON,
    EngineParamBindingPayloadV2ToJSONTyped,
} from './EngineParamBindingPayloadV2.js';

/**
 * 
 * @export
 * @interface ExpressionElseBranchPayloadV2
 */
export interface ExpressionElseBranchPayloadV2 {
    /**
     * 
     */
    result: EngineParamBindingPayloadV2;
}

/**
 * Check if a given object implements the ExpressionElseBranchPayloadV2 interface.
 */
export function instanceOfExpressionElseBranchPayloadV2(value: object): value is ExpressionElseBranchPayloadV2 {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ExpressionElseBranchPayloadV2FromJSON(json: any): ExpressionElseBranchPayloadV2 {
    return ExpressionElseBranchPayloadV2FromJSONTyped(json, false);
}

export function ExpressionElseBranchPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionElseBranchPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'result': EngineParamBindingPayloadV2FromJSON(json['result']),
    };
}

export function ExpressionElseBranchPayloadV2ToJSON(json: any): ExpressionElseBranchPayloadV2 {
    return ExpressionElseBranchPayloadV2ToJSONTyped(json, false);
}

export function ExpressionElseBranchPayloadV2ToJSONTyped(value?: ExpressionElseBranchPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': EngineParamBindingPayloadV2ToJSON(value['result']),
    };
}

