/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ExpressionConcatenateOptsPayloadV2
 */
export interface ExpressionConcatenateOptsPayloadV2 {
    /**
     * The reference that you want to concatenate with
     */
    reference: string;
}

/**
 * Check if a given object implements the ExpressionConcatenateOptsPayloadV2 interface.
 */
export function instanceOfExpressionConcatenateOptsPayloadV2(value: object): value is ExpressionConcatenateOptsPayloadV2 {
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function ExpressionConcatenateOptsPayloadV2FromJSON(json: any): ExpressionConcatenateOptsPayloadV2 {
    return ExpressionConcatenateOptsPayloadV2FromJSONTyped(json, false);
}

export function ExpressionConcatenateOptsPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionConcatenateOptsPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'reference': json['reference'],
    };
}

export function ExpressionConcatenateOptsPayloadV2ToJSON(json: any): ExpressionConcatenateOptsPayloadV2 {
    return ExpressionConcatenateOptsPayloadV2ToJSONTyped(json, false);
}

export function ExpressionConcatenateOptsPayloadV2ToJSONTyped(value?: ExpressionConcatenateOptsPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference': value['reference'],
    };
}

