/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { FollowUpV2 } from './FollowUpV2.js';
import {
    FollowUpV2FromJSON,
    FollowUpV2FromJSONTyped,
    FollowUpV2ToJSON,
    FollowUpV2ToJSONTyped,
} from './FollowUpV2.js';

/**
 * 
 * @export
 * @interface FollowUpsShowResultV2
 */
export interface FollowUpsShowResultV2 {
    /**
     * 
     */
    follow_up: FollowUpV2;
}

/**
 * Check if a given object implements the FollowUpsShowResultV2 interface.
 */
export function instanceOfFollowUpsShowResultV2(value: object): value is FollowUpsShowResultV2 {
    if (!('follow_up' in value) || value['follow_up'] === undefined) return false;
    return true;
}

export function FollowUpsShowResultV2FromJSON(json: any): FollowUpsShowResultV2 {
    return FollowUpsShowResultV2FromJSONTyped(json, false);
}

export function FollowUpsShowResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpsShowResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'follow_up': FollowUpV2FromJSON(json['follow_up']),
    };
}

export function FollowUpsShowResultV2ToJSON(json: any): FollowUpsShowResultV2 {
    return FollowUpsShowResultV2ToJSONTyped(json, false);
}

export function FollowUpsShowResultV2ToJSONTyped(value?: FollowUpsShowResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'follow_up': FollowUpV2ToJSON(value['follow_up']),
    };
}

