/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { UserV1 } from './UserV1.js';
import {
    UserV1FromJSON,
    UserV1FromJSONTyped,
    UserV1ToJSON,
    UserV1ToJSONTyped,
} from './UserV1.js';

/**
 * 
 * @export
 * @interface IncidentMembershipV1
 */
export interface IncidentMembershipV1 {
    /**
     * When the membership was created
     */
    created_at: Date;
    /**
     * Unique identifier of this incident membership
     */
    id: string;
    /**
     * Unique identifier of the incident
     */
    incident_id: string;
    /**
     * When the membership was last updated
     */
    updated_at: Date;
    /**
     * 
     */
    user: UserV1;
}

/**
 * Check if a given object implements the IncidentMembershipV1 interface.
 */
export function instanceOfIncidentMembershipV1(value: object): value is IncidentMembershipV1 {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incident_id' in value) || value['incident_id'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function IncidentMembershipV1FromJSON(json: any): IncidentMembershipV1 {
    return IncidentMembershipV1FromJSONTyped(json, false);
}

export function IncidentMembershipV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentMembershipV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'id': json['id'],
        'incident_id': json['incident_id'],
        'updated_at': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'user': UserV1FromJSON(json['user']),
    };
}

export function IncidentMembershipV1ToJSON(json: any): IncidentMembershipV1 {
    return IncidentMembershipV1ToJSONTyped(json, false);
}

export function IncidentMembershipV1ToJSONTyped(value?: IncidentMembershipV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'id': value['id'],
        'incident_id': value['incident_id'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
        'user': UserV1ToJSON(value['user']),
    };
}

