/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { ExternalIssueReferenceV2 } from './ExternalIssueReferenceV2.js';
import {
    ExternalIssueReferenceV2FromJSON,
    ExternalIssueReferenceV2FromJSONTyped,
    ExternalIssueReferenceV2ToJSON,
    ExternalIssueReferenceV2ToJSONTyped,
} from './ExternalIssueReferenceV2.js';
import type { IncidentDurationMetricWithValueV2 } from './IncidentDurationMetricWithValueV2.js';
import {
    IncidentDurationMetricWithValueV2FromJSON,
    IncidentDurationMetricWithValueV2FromJSONTyped,
    IncidentDurationMetricWithValueV2ToJSON,
    IncidentDurationMetricWithValueV2ToJSONTyped,
} from './IncidentDurationMetricWithValueV2.js';
import type { CustomFieldEntryV2 } from './CustomFieldEntryV2.js';
import {
    CustomFieldEntryV2FromJSON,
    CustomFieldEntryV2FromJSONTyped,
    CustomFieldEntryV2ToJSON,
    CustomFieldEntryV2ToJSONTyped,
} from './CustomFieldEntryV2.js';
import type { IncidentStatusV2 } from './IncidentStatusV2.js';
import {
    IncidentStatusV2FromJSON,
    IncidentStatusV2FromJSONTyped,
    IncidentStatusV2ToJSON,
    IncidentStatusV2ToJSONTyped,
} from './IncidentStatusV2.js';
import type { IncidentTimestampWithValueV2 } from './IncidentTimestampWithValueV2.js';
import {
    IncidentTimestampWithValueV2FromJSON,
    IncidentTimestampWithValueV2FromJSONTyped,
    IncidentTimestampWithValueV2ToJSON,
    IncidentTimestampWithValueV2ToJSONTyped,
} from './IncidentTimestampWithValueV2.js';
import type { ActorV2 } from './ActorV2.js';
import {
    ActorV2FromJSON,
    ActorV2FromJSONTyped,
    ActorV2ToJSON,
    ActorV2ToJSONTyped,
} from './ActorV2.js';
import type { IncidentTypeV2 } from './IncidentTypeV2.js';
import {
    IncidentTypeV2FromJSON,
    IncidentTypeV2FromJSONTyped,
    IncidentTypeV2ToJSON,
    IncidentTypeV2ToJSONTyped,
} from './IncidentTypeV2.js';
import type { IncidentRoleAssignmentV2 } from './IncidentRoleAssignmentV2.js';
import {
    IncidentRoleAssignmentV2FromJSON,
    IncidentRoleAssignmentV2FromJSONTyped,
    IncidentRoleAssignmentV2ToJSON,
    IncidentRoleAssignmentV2ToJSONTyped,
} from './IncidentRoleAssignmentV2.js';
import type { SeverityV2 } from './SeverityV2.js';
import {
    SeverityV2FromJSON,
    SeverityV2FromJSONTyped,
    SeverityV2ToJSON,
    SeverityV2ToJSONTyped,
} from './SeverityV2.js';

/**
 * 
 * @export
 * @interface IncidentV2
 */
export interface IncidentV2 {
    /**
     * The call URL attached to this incident
     */
    call_url?: string;
    /**
     * When the incident was created
     */
    created_at: Date;
    /**
     * 
     */
    creator: ActorV2;
    /**
     * Custom field entries for this incident
     */
    custom_field_entries: Array<CustomFieldEntryV2>;
    /**
     * Incident duration metrics and their measurements for this incident
     */
    duration_metrics?: Array<IncidentDurationMetricWithValueV2>;
    /**
     * 
     */
    external_issue_reference?: ExternalIssueReferenceV2;
    /**
     * If this incident has a debrief attached
     */
    has_debrief?: boolean;
    /**
     * Unique identifier for the incident
     */
    id: string;
    /**
     * A list of who is assigned to each role for this incident
     */
    incident_role_assignments: Array<IncidentRoleAssignmentV2>;
    /**
     * 
     */
    incident_status: IncidentStatusV2;
    /**
     * Incident lifecycle events and when they occurred
     */
    incident_timestamp_values?: Array<IncidentTimestampWithValueV2>;
    /**
     * 
     */
    incident_type?: IncidentTypeV2;
    /**
     * When the incident last recorded 'activity'
     */
    last_activity_at: Date;
    /**
     * Whether the incident is real, a test, a tutorial, or importing as a retrospective incident
     */
    mode: IncidentV2ModeEnum;
    /**
     * URL to link to the Microsoft Teams channel
     */
    ms_teams_channel_url?: string;
    /**
     * Explanation of the incident
     */
    name: string;
    /**
     * A permanent link to the homepage for this incident
     */
    permalink?: string;
    /**
     * An array of IDs of postmortem documents for this incident
     */
    postmortem_document_ids?: Array<string>;
    /**
     * The URL of the incident post-mortem document
     */
    postmortem_document_url?: string;
    /**
     * Reference to this incident, as displayed across the product
     */
    reference: string;
    /**
     * 
     */
    severity?: SeverityV2;
    /**
     * ID of the Slack channel in the organisation Slack workspace. Note that the channel is sometimes created asynchronously, so may not be present when the incident is just created.
     */
    slack_channel_id: string;
    /**
     * Name of the slack channel
     */
    slack_channel_name?: string;
    /**
     * URL to link to the slack channel
     */
    slack_channel_url?: string;
    /**
     * ID of the Slack team / workspace. This is only required if you are using a Slack Enterprise Grid with multiple teams.
     */
    slack_team_id: string;
    /**
     * Detailed description of the incident
     */
    summary?: string;
    /**
     * IDs of the teams that own this incident, resolved from your team settings. Empty when no teams match.
     */
    team_ids: Array<string>;
    /**
     * When the incident was last updated
     */
    updated_at: Date;
    /**
     * Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [docs](https://docs.incident.io/incidents/sensitive-incidents).
     */
    visibility: IncidentV2VisibilityEnum;
    /**
     * Amount of time spent on the incident in late hours
     */
    workload_minutes_late?: number;
    /**
     * Amount of time spent on the incident in sleeping hours
     */
    workload_minutes_sleeping?: number;
    /**
     * Amount of time spent on the incident in total
     */
    workload_minutes_total?: number;
    /**
     * Amount of time spent on the incident in working hours
     */
    workload_minutes_working?: number;
}


/**
 * @export
 */
export const IncidentV2ModeEnum = {
    Standard: 'standard',
    Retrospective: 'retrospective',
    Test: 'test',
    Tutorial: 'tutorial',
} as const;
export type IncidentV2ModeEnum = typeof IncidentV2ModeEnum[keyof typeof IncidentV2ModeEnum];

/**
 * @export
 */
export const IncidentV2VisibilityEnum = {
    Public: 'public',
    Private: 'private',
} as const;
export type IncidentV2VisibilityEnum = typeof IncidentV2VisibilityEnum[keyof typeof IncidentV2VisibilityEnum];


/**
 * Check if a given object implements the IncidentV2 interface.
 */
export function instanceOfIncidentV2(value: object): value is IncidentV2 {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('custom_field_entries' in value) || value['custom_field_entries'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incident_role_assignments' in value) || value['incident_role_assignments'] === undefined) return false;
    if (!('incident_status' in value) || value['incident_status'] === undefined) return false;
    if (!('last_activity_at' in value) || value['last_activity_at'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('slack_channel_id' in value) || value['slack_channel_id'] === undefined) return false;
    if (!('slack_team_id' in value) || value['slack_team_id'] === undefined) return false;
    if (!('team_ids' in value) || value['team_ids'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function IncidentV2FromJSON(json: any): IncidentV2 {
    return IncidentV2FromJSONTyped(json, false);
}

export function IncidentV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'call_url': json['call_url'] == null ? undefined : json['call_url'],
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'creator': ActorV2FromJSON(json['creator']),
        'custom_field_entries': ((json['custom_field_entries'] as Array<any>).map(CustomFieldEntryV2FromJSON)),
        'duration_metrics': json['duration_metrics'] == null ? undefined : ((json['duration_metrics'] as Array<any>).map(IncidentDurationMetricWithValueV2FromJSON)),
        'external_issue_reference': json['external_issue_reference'] == null ? undefined : ExternalIssueReferenceV2FromJSON(json['external_issue_reference']),
        'has_debrief': json['has_debrief'] == null ? undefined : json['has_debrief'],
        'id': json['id'],
        'incident_role_assignments': ((json['incident_role_assignments'] as Array<any>).map(IncidentRoleAssignmentV2FromJSON)),
        'incident_status': IncidentStatusV2FromJSON(json['incident_status']),
        'incident_timestamp_values': json['incident_timestamp_values'] == null ? undefined : ((json['incident_timestamp_values'] as Array<any>).map(IncidentTimestampWithValueV2FromJSON)),
        'incident_type': json['incident_type'] == null ? undefined : IncidentTypeV2FromJSON(json['incident_type']),
        'last_activity_at': (json['last_activity_at'] == null ? json['last_activity_at'] : parseDateTime(json['last_activity_at'])),
        'mode': json['mode'],
        'ms_teams_channel_url': json['ms_teams_channel_url'] == null ? undefined : json['ms_teams_channel_url'],
        'name': json['name'],
        'permalink': json['permalink'] == null ? undefined : json['permalink'],
        'postmortem_document_ids': json['postmortem_document_ids'] == null ? undefined : json['postmortem_document_ids'],
        'postmortem_document_url': json['postmortem_document_url'] == null ? undefined : json['postmortem_document_url'],
        'reference': json['reference'],
        'severity': json['severity'] == null ? undefined : SeverityV2FromJSON(json['severity']),
        'slack_channel_id': json['slack_channel_id'],
        'slack_channel_name': json['slack_channel_name'] == null ? undefined : json['slack_channel_name'],
        'slack_channel_url': json['slack_channel_url'] == null ? undefined : json['slack_channel_url'],
        'slack_team_id': json['slack_team_id'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'team_ids': json['team_ids'],
        'updated_at': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'visibility': json['visibility'],
        'workload_minutes_late': json['workload_minutes_late'] == null ? undefined : json['workload_minutes_late'],
        'workload_minutes_sleeping': json['workload_minutes_sleeping'] == null ? undefined : json['workload_minutes_sleeping'],
        'workload_minutes_total': json['workload_minutes_total'] == null ? undefined : json['workload_minutes_total'],
        'workload_minutes_working': json['workload_minutes_working'] == null ? undefined : json['workload_minutes_working'],
    };
}

export function IncidentV2ToJSON(json: any): IncidentV2 {
    return IncidentV2ToJSONTyped(json, false);
}

export function IncidentV2ToJSONTyped(value?: IncidentV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'call_url': value['call_url'],
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'creator': ActorV2ToJSON(value['creator']),
        'custom_field_entries': ((value['custom_field_entries'] as Array<any>).map(CustomFieldEntryV2ToJSON)),
        'duration_metrics': value['duration_metrics'] == null ? undefined : ((value['duration_metrics'] as Array<any>).map(IncidentDurationMetricWithValueV2ToJSON)),
        'external_issue_reference': ExternalIssueReferenceV2ToJSON(value['external_issue_reference']),
        'has_debrief': value['has_debrief'],
        'id': value['id'],
        'incident_role_assignments': ((value['incident_role_assignments'] as Array<any>).map(IncidentRoleAssignmentV2ToJSON)),
        'incident_status': IncidentStatusV2ToJSON(value['incident_status']),
        'incident_timestamp_values': value['incident_timestamp_values'] == null ? undefined : ((value['incident_timestamp_values'] as Array<any>).map(IncidentTimestampWithValueV2ToJSON)),
        'incident_type': IncidentTypeV2ToJSON(value['incident_type']),
        'last_activity_at': value['last_activity_at'] == null ? value['last_activity_at'] : serializeDateTime(value['last_activity_at']),
        'mode': value['mode'],
        'ms_teams_channel_url': value['ms_teams_channel_url'],
        'name': value['name'],
        'permalink': value['permalink'],
        'postmortem_document_ids': value['postmortem_document_ids'],
        'postmortem_document_url': value['postmortem_document_url'],
        'reference': value['reference'],
        'severity': SeverityV2ToJSON(value['severity']),
        'slack_channel_id': value['slack_channel_id'],
        'slack_channel_name': value['slack_channel_name'],
        'slack_channel_url': value['slack_channel_url'],
        'slack_team_id': value['slack_team_id'],
        'summary': value['summary'],
        'team_ids': value['team_ids'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
        'visibility': value['visibility'],
        'workload_minutes_late': value['workload_minutes_late'],
        'workload_minutes_sleeping': value['workload_minutes_sleeping'],
        'workload_minutes_total': value['workload_minutes_total'],
        'workload_minutes_working': value['workload_minutes_working'],
    };
}

