/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IncidentRoleV1 } from './IncidentRoleV1.js';
import {
    IncidentRoleV1FromJSON,
    IncidentRoleV1FromJSONTyped,
    IncidentRoleV1ToJSON,
    IncidentRoleV1ToJSONTyped,
} from './IncidentRoleV1.js';

/**
 * 
 * @export
 * @interface IncidentRolesUpdateResultV1
 */
export interface IncidentRolesUpdateResultV1 {
    /**
     * 
     */
    incident_role: IncidentRoleV1;
}

/**
 * Check if a given object implements the IncidentRolesUpdateResultV1 interface.
 */
export function instanceOfIncidentRolesUpdateResultV1(value: object): value is IncidentRolesUpdateResultV1 {
    if (!('incident_role' in value) || value['incident_role'] === undefined) return false;
    return true;
}

export function IncidentRolesUpdateResultV1FromJSON(json: any): IncidentRolesUpdateResultV1 {
    return IncidentRolesUpdateResultV1FromJSONTyped(json, false);
}

export function IncidentRolesUpdateResultV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentRolesUpdateResultV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'incident_role': IncidentRoleV1FromJSON(json['incident_role']),
    };
}

export function IncidentRolesUpdateResultV1ToJSON(json: any): IncidentRolesUpdateResultV1 {
    return IncidentRolesUpdateResultV1ToJSONTyped(json, false);
}

export function IncidentRolesUpdateResultV1ToJSONTyped(value?: IncidentRolesUpdateResultV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident_role': IncidentRoleV1ToJSON(value['incident_role']),
    };
}

