/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IncidentRelationshipDetailsV1
 */
export interface IncidentRelationshipDetailsV1 {
    /**
     * External ID of this incident often prepended with 'INC-'
     */
    external_id: number;
    /**
     * Unique identifier of this incident
     */
    id: string;
    /**
     * Name of this incident
     */
    name: string;
}

/**
 * Check if a given object implements the IncidentRelationshipDetailsV1 interface.
 */
export function instanceOfIncidentRelationshipDetailsV1(value: object): value is IncidentRelationshipDetailsV1 {
    if (!('external_id' in value) || value['external_id'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function IncidentRelationshipDetailsV1FromJSON(json: any): IncidentRelationshipDetailsV1 {
    return IncidentRelationshipDetailsV1FromJSONTyped(json, false);
}

export function IncidentRelationshipDetailsV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentRelationshipDetailsV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'external_id': json['external_id'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function IncidentRelationshipDetailsV1ToJSON(json: any): IncidentRelationshipDetailsV1 {
    return IncidentRelationshipDetailsV1ToJSONTyped(json, false);
}

export function IncidentRelationshipDetailsV1ToJSONTyped(value?: IncidentRelationshipDetailsV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_id': value['external_id'],
        'id': value['id'],
        'name': value['name'],
    };
}

