/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UserReferencePayloadV1 } from './UserReferencePayloadV1.js';
import {
    UserReferencePayloadV1FromJSON,
    UserReferencePayloadV1FromJSONTyped,
    UserReferencePayloadV1ToJSON,
    UserReferencePayloadV1ToJSONTyped,
} from './UserReferencePayloadV1.js';

/**
 * 
 * @export
 * @interface IncidentRoleAssignmentPayloadV1
 */
export interface IncidentRoleAssignmentPayloadV1 {
    /**
     * 
     */
    assignee: UserReferencePayloadV1;
    /**
     * Unique ID of an incident role. Note that the 'reporter' role can only be assigned when creating an incident.
     */
    incident_role_id: string;
}

/**
 * Check if a given object implements the IncidentRoleAssignmentPayloadV1 interface.
 */
export function instanceOfIncidentRoleAssignmentPayloadV1(value: object): value is IncidentRoleAssignmentPayloadV1 {
    if (!('assignee' in value) || value['assignee'] === undefined) return false;
    if (!('incident_role_id' in value) || value['incident_role_id'] === undefined) return false;
    return true;
}

export function IncidentRoleAssignmentPayloadV1FromJSON(json: any): IncidentRoleAssignmentPayloadV1 {
    return IncidentRoleAssignmentPayloadV1FromJSONTyped(json, false);
}

export function IncidentRoleAssignmentPayloadV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentRoleAssignmentPayloadV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'assignee': UserReferencePayloadV1FromJSON(json['assignee']),
        'incident_role_id': json['incident_role_id'],
    };
}

export function IncidentRoleAssignmentPayloadV1ToJSON(json: any): IncidentRoleAssignmentPayloadV1 {
    return IncidentRoleAssignmentPayloadV1ToJSONTyped(json, false);
}

export function IncidentRoleAssignmentPayloadV1ToJSONTyped(value?: IncidentRoleAssignmentPayloadV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignee': UserReferencePayloadV1ToJSON(value['assignee']),
        'incident_role_id': value['incident_role_id'],
    };
}

