/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IncidentTemplateV1 } from './IncidentTemplateV1.js';
import {
    IncidentTemplateV1FromJSON,
    IncidentTemplateV1FromJSONTyped,
    IncidentTemplateV1ToJSON,
    IncidentTemplateV1ToJSONTyped,
} from './IncidentTemplateV1.js';

/**
 * 
 * @export
 * @interface IncidentTemplatesShowResultV1
 */
export interface IncidentTemplatesShowResultV1 {
    /**
     * 
     */
    incident_template: IncidentTemplateV1;
}

/**
 * Check if a given object implements the IncidentTemplatesShowResultV1 interface.
 */
export function instanceOfIncidentTemplatesShowResultV1(value: object): value is IncidentTemplatesShowResultV1 {
    if (!('incident_template' in value) || value['incident_template'] === undefined) return false;
    return true;
}

export function IncidentTemplatesShowResultV1FromJSON(json: any): IncidentTemplatesShowResultV1 {
    return IncidentTemplatesShowResultV1FromJSONTyped(json, false);
}

export function IncidentTemplatesShowResultV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentTemplatesShowResultV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'incident_template': IncidentTemplateV1FromJSON(json['incident_template']),
    };
}

export function IncidentTemplatesShowResultV1ToJSON(json: any): IncidentTemplatesShowResultV1 {
    return IncidentTemplatesShowResultV1ToJSONTyped(json, false);
}

export function IncidentTemplatesShowResultV1ToJSONTyped(value?: IncidentTemplatesShowResultV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident_template': IncidentTemplateV1ToJSON(value['incident_template']),
    };
}

