/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IncidentTemplateV1 } from './IncidentTemplateV1.js';
import {
    IncidentTemplateV1FromJSON,
    IncidentTemplateV1FromJSONTyped,
    IncidentTemplateV1ToJSON,
    IncidentTemplateV1ToJSONTyped,
} from './IncidentTemplateV1.js';

/**
 * 
 * @export
 * @interface IncidentTemplatesUpdateResultV1
 */
export interface IncidentTemplatesUpdateResultV1 {
    /**
     * 
     */
    incident_template: IncidentTemplateV1;
}

/**
 * Check if a given object implements the IncidentTemplatesUpdateResultV1 interface.
 */
export function instanceOfIncidentTemplatesUpdateResultV1(value: object): value is IncidentTemplatesUpdateResultV1 {
    if (!('incident_template' in value) || value['incident_template'] === undefined) return false;
    return true;
}

export function IncidentTemplatesUpdateResultV1FromJSON(json: any): IncidentTemplatesUpdateResultV1 {
    return IncidentTemplatesUpdateResultV1FromJSONTyped(json, false);
}

export function IncidentTemplatesUpdateResultV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentTemplatesUpdateResultV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'incident_template': IncidentTemplateV1FromJSON(json['incident_template']),
    };
}

export function IncidentTemplatesUpdateResultV1ToJSON(json: any): IncidentTemplatesUpdateResultV1 {
    return IncidentTemplatesUpdateResultV1ToJSONTyped(json, false);
}

export function IncidentTemplatesUpdateResultV1ToJSONTyped(value?: IncidentTemplatesUpdateResultV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident_template': IncidentTemplateV1ToJSON(value['incident_template']),
    };
}

