/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CustomFieldEntryPayloadV2 } from './CustomFieldEntryPayloadV2.js';
import {
    CustomFieldEntryPayloadV2FromJSON,
    CustomFieldEntryPayloadV2FromJSONTyped,
    CustomFieldEntryPayloadV2ToJSON,
    CustomFieldEntryPayloadV2ToJSONTyped,
} from './CustomFieldEntryPayloadV2.js';
import type { IncidentTimestampValuePayloadV2 } from './IncidentTimestampValuePayloadV2.js';
import {
    IncidentTimestampValuePayloadV2FromJSON,
    IncidentTimestampValuePayloadV2FromJSONTyped,
    IncidentTimestampValuePayloadV2ToJSON,
    IncidentTimestampValuePayloadV2ToJSONTyped,
} from './IncidentTimestampValuePayloadV2.js';
import type { IncidentRoleAssignmentPayloadV2 } from './IncidentRoleAssignmentPayloadV2.js';
import {
    IncidentRoleAssignmentPayloadV2FromJSON,
    IncidentRoleAssignmentPayloadV2FromJSONTyped,
    IncidentRoleAssignmentPayloadV2ToJSON,
    IncidentRoleAssignmentPayloadV2ToJSONTyped,
} from './IncidentRoleAssignmentPayloadV2.js';
import type { RetrospectiveIncidentOptionsV2 } from './RetrospectiveIncidentOptionsV2.js';
import {
    RetrospectiveIncidentOptionsV2FromJSON,
    RetrospectiveIncidentOptionsV2FromJSONTyped,
    RetrospectiveIncidentOptionsV2ToJSON,
    RetrospectiveIncidentOptionsV2ToJSONTyped,
} from './RetrospectiveIncidentOptionsV2.js';

/**
 * 
 * @export
 * @interface IncidentsCreatePayloadV2
 */
export interface IncidentsCreatePayloadV2 {
    /**
     * Set the incident's custom fields to these values
     */
    custom_field_entries?: Array<CustomFieldEntryPayloadV2>;
    /**
     * Unique string used to de-duplicate incident create requests
     */
    idempotency_key: string;
    /**
     * Assign incident roles to these people
     */
    incident_role_assignments?: Array<IncidentRoleAssignmentPayloadV2>;
    /**
     * Incident status to assign to the incident
     */
    incident_status_id?: string;
    /**
     * Assign the incident's timestamps to these values
     */
    incident_timestamp_values?: Array<IncidentTimestampValuePayloadV2>;
    /**
     * Incident type to create this incident as
     */
    incident_type_id?: string;
    /**
     * Whether the incident is real, a test, a tutorial, or importing as a retrospective incident
     */
    mode?: IncidentsCreatePayloadV2ModeEnum;
    /**
     * Explanation of the incident
     */
    name?: string;
    /**
     * 
     */
    retrospective_incident_options?: RetrospectiveIncidentOptionsV2;
    /**
     * Severity to create incident as
     */
    severity_id?: string;
    /**
     * Name of the Slack channel to create for this incident
     */
    slack_channel_name_override?: string;
    /**
     * Slack Team to create the incident in
     */
    slack_team_id?: string;
    /**
     * Detailed description of the incident
     */
    summary?: string;
    /**
     * Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [docs](https://docs.incident.io/incidents/sensitive-incidents).
     */
    visibility: IncidentsCreatePayloadV2VisibilityEnum;
}


/**
 * @export
 */
export const IncidentsCreatePayloadV2ModeEnum = {
    Standard: 'standard',
    Retrospective: 'retrospective',
    Test: 'test',
    Tutorial: 'tutorial',
} as const;
export type IncidentsCreatePayloadV2ModeEnum = typeof IncidentsCreatePayloadV2ModeEnum[keyof typeof IncidentsCreatePayloadV2ModeEnum];

/**
 * @export
 */
export const IncidentsCreatePayloadV2VisibilityEnum = {
    Public: 'public',
    Private: 'private',
} as const;
export type IncidentsCreatePayloadV2VisibilityEnum = typeof IncidentsCreatePayloadV2VisibilityEnum[keyof typeof IncidentsCreatePayloadV2VisibilityEnum];


/**
 * Check if a given object implements the IncidentsCreatePayloadV2 interface.
 */
export function instanceOfIncidentsCreatePayloadV2(value: object): value is IncidentsCreatePayloadV2 {
    if (!('idempotency_key' in value) || value['idempotency_key'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function IncidentsCreatePayloadV2FromJSON(json: any): IncidentsCreatePayloadV2 {
    return IncidentsCreatePayloadV2FromJSONTyped(json, false);
}

export function IncidentsCreatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentsCreatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'custom_field_entries': json['custom_field_entries'] == null ? undefined : ((json['custom_field_entries'] as Array<any>).map(CustomFieldEntryPayloadV2FromJSON)),
        'idempotency_key': json['idempotency_key'],
        'incident_role_assignments': json['incident_role_assignments'] == null ? undefined : ((json['incident_role_assignments'] as Array<any>).map(IncidentRoleAssignmentPayloadV2FromJSON)),
        'incident_status_id': json['incident_status_id'] == null ? undefined : json['incident_status_id'],
        'incident_timestamp_values': json['incident_timestamp_values'] == null ? undefined : ((json['incident_timestamp_values'] as Array<any>).map(IncidentTimestampValuePayloadV2FromJSON)),
        'incident_type_id': json['incident_type_id'] == null ? undefined : json['incident_type_id'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'name': json['name'] == null ? undefined : json['name'],
        'retrospective_incident_options': json['retrospective_incident_options'] == null ? undefined : RetrospectiveIncidentOptionsV2FromJSON(json['retrospective_incident_options']),
        'severity_id': json['severity_id'] == null ? undefined : json['severity_id'],
        'slack_channel_name_override': json['slack_channel_name_override'] == null ? undefined : json['slack_channel_name_override'],
        'slack_team_id': json['slack_team_id'] == null ? undefined : json['slack_team_id'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'visibility': json['visibility'],
    };
}

export function IncidentsCreatePayloadV2ToJSON(json: any): IncidentsCreatePayloadV2 {
    return IncidentsCreatePayloadV2ToJSONTyped(json, false);
}

export function IncidentsCreatePayloadV2ToJSONTyped(value?: IncidentsCreatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_field_entries': value['custom_field_entries'] == null ? undefined : ((value['custom_field_entries'] as Array<any>).map(CustomFieldEntryPayloadV2ToJSON)),
        'idempotency_key': value['idempotency_key'],
        'incident_role_assignments': value['incident_role_assignments'] == null ? undefined : ((value['incident_role_assignments'] as Array<any>).map(IncidentRoleAssignmentPayloadV2ToJSON)),
        'incident_status_id': value['incident_status_id'],
        'incident_timestamp_values': value['incident_timestamp_values'] == null ? undefined : ((value['incident_timestamp_values'] as Array<any>).map(IncidentTimestampValuePayloadV2ToJSON)),
        'incident_type_id': value['incident_type_id'],
        'mode': value['mode'],
        'name': value['name'],
        'retrospective_incident_options': RetrospectiveIncidentOptionsV2ToJSON(value['retrospective_incident_options']),
        'severity_id': value['severity_id'],
        'slack_channel_name_override': value['slack_channel_name_override'],
        'slack_team_id': value['slack_team_id'],
        'summary': value['summary'],
        'visibility': value['visibility'],
    };
}

