/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { IncidentTimestampValueV1 } from './IncidentTimestampValueV1.js';
import {
    IncidentTimestampValueV1FromJSON,
    IncidentTimestampValueV1FromJSONTyped,
    IncidentTimestampValueV1ToJSON,
    IncidentTimestampValueV1ToJSONTyped,
} from './IncidentTimestampValueV1.js';
import type { IncidentTypeV1 } from './IncidentTypeV1.js';
import {
    IncidentTypeV1FromJSON,
    IncidentTypeV1FromJSONTyped,
    IncidentTypeV1ToJSON,
    IncidentTypeV1ToJSONTyped,
} from './IncidentTypeV1.js';
import type { CustomFieldEntryV1 } from './CustomFieldEntryV1.js';
import {
    CustomFieldEntryV1FromJSON,
    CustomFieldEntryV1FromJSONTyped,
    CustomFieldEntryV1ToJSON,
    CustomFieldEntryV1ToJSONTyped,
} from './CustomFieldEntryV1.js';
import type { ActorV1 } from './ActorV1.js';
import {
    ActorV1FromJSON,
    ActorV1FromJSONTyped,
    ActorV1ToJSON,
    ActorV1ToJSONTyped,
} from './ActorV1.js';
import type { IncidentRoleAssignmentV1 } from './IncidentRoleAssignmentV1.js';
import {
    IncidentRoleAssignmentV1FromJSON,
    IncidentRoleAssignmentV1FromJSONTyped,
    IncidentRoleAssignmentV1ToJSON,
    IncidentRoleAssignmentV1ToJSONTyped,
} from './IncidentRoleAssignmentV1.js';
import type { SeverityV1 } from './SeverityV1.js';
import {
    SeverityV1FromJSON,
    SeverityV1FromJSONTyped,
    SeverityV1ToJSON,
    SeverityV1ToJSONTyped,
} from './SeverityV1.js';

/**
 * 
 * @export
 * @interface IncidentV1
 */
export interface IncidentV1 {
    /**
     * The call URL attached to this incident
     */
    call_url?: string;
    /**
     * When the incident was created
     */
    created_at: Date;
    /**
     * 
     */
    creator: ActorV1;
    /**
     * Custom field entries for this incident
     */
    custom_field_entries: Array<CustomFieldEntryV1>;
    /**
     * Unique identifier for the incident
     */
    id: string;
    /**
     * A list of who is assigned to each role for this incident
     */
    incident_role_assignments: Array<IncidentRoleAssignmentV1>;
    /**
     * 
     */
    incident_type?: IncidentTypeV1;
    /**
     * Whether the incident is real, a test, a tutorial, or importing as a retrospective incident
     */
    mode: IncidentV1ModeEnum;
    /**
     * Explanation of the incident
     */
    name: string;
    /**
     * A permanent link to the homepage for this incident
     */
    permalink?: string;
    /**
     * The URL of the incident post-mortem document
     */
    postmortem_document_url?: string;
    /**
     * Reference to this incident, as displayed across the product
     */
    reference: string;
    /**
     * 
     */
    severity?: SeverityV1;
    /**
     * ID of the Slack channel in the organisation Slack workspace. Note that the channel is sometimes created asynchronously, so may not be present when the incident is just created.
     */
    slack_channel_id: string;
    /**
     * Name of the slack channel
     */
    slack_channel_name?: string;
    /**
     * ID of the Slack team / workspace. This is only required if you are using a Slack Enterprise Grid with multiple teams.
     */
    slack_team_id: string;
    /**
     * Current status of the incident
     */
    status: IncidentV1StatusEnum;
    /**
     * Detailed description of the incident
     */
    summary?: string;
    /**
     * Incident lifecycle events and when they last occurred
     */
    timestamps?: Array<IncidentTimestampValueV1>;
    /**
     * When the incident was last updated
     */
    updated_at: Date;
    /**
     * Whether the incident should be open to anyone in your Slack workspace (public), or invite-only (private). For more information on Private Incidents see our [docs](https://docs.incident.io/incidents/sensitive-incidents).
     */
    visibility: IncidentV1VisibilityEnum;
}


/**
 * @export
 */
export const IncidentV1ModeEnum = {
    Real: 'real',
    Test: 'test',
    Tutorial: 'tutorial',
} as const;
export type IncidentV1ModeEnum = typeof IncidentV1ModeEnum[keyof typeof IncidentV1ModeEnum];

/**
 * @export
 */
export const IncidentV1StatusEnum = {
    Triage: 'triage',
    Investigating: 'investigating',
    Fixing: 'fixing',
    Monitoring: 'monitoring',
    Closed: 'closed',
    Declined: 'declined',
} as const;
export type IncidentV1StatusEnum = typeof IncidentV1StatusEnum[keyof typeof IncidentV1StatusEnum];

/**
 * @export
 */
export const IncidentV1VisibilityEnum = {
    Public: 'public',
    Private: 'private',
} as const;
export type IncidentV1VisibilityEnum = typeof IncidentV1VisibilityEnum[keyof typeof IncidentV1VisibilityEnum];


/**
 * Check if a given object implements the IncidentV1 interface.
 */
export function instanceOfIncidentV1(value: object): value is IncidentV1 {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('custom_field_entries' in value) || value['custom_field_entries'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incident_role_assignments' in value) || value['incident_role_assignments'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('slack_channel_id' in value) || value['slack_channel_id'] === undefined) return false;
    if (!('slack_team_id' in value) || value['slack_team_id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function IncidentV1FromJSON(json: any): IncidentV1 {
    return IncidentV1FromJSONTyped(json, false);
}

export function IncidentV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'call_url': json['call_url'] == null ? undefined : json['call_url'],
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'creator': ActorV1FromJSON(json['creator']),
        'custom_field_entries': ((json['custom_field_entries'] as Array<any>).map(CustomFieldEntryV1FromJSON)),
        'id': json['id'],
        'incident_role_assignments': ((json['incident_role_assignments'] as Array<any>).map(IncidentRoleAssignmentV1FromJSON)),
        'incident_type': json['incident_type'] == null ? undefined : IncidentTypeV1FromJSON(json['incident_type']),
        'mode': json['mode'],
        'name': json['name'],
        'permalink': json['permalink'] == null ? undefined : json['permalink'],
        'postmortem_document_url': json['postmortem_document_url'] == null ? undefined : json['postmortem_document_url'],
        'reference': json['reference'],
        'severity': json['severity'] == null ? undefined : SeverityV1FromJSON(json['severity']),
        'slack_channel_id': json['slack_channel_id'],
        'slack_channel_name': json['slack_channel_name'] == null ? undefined : json['slack_channel_name'],
        'slack_team_id': json['slack_team_id'],
        'status': json['status'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'timestamps': json['timestamps'] == null ? undefined : ((json['timestamps'] as Array<any>).map(IncidentTimestampValueV1FromJSON)),
        'updated_at': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'visibility': json['visibility'],
    };
}

export function IncidentV1ToJSON(json: any): IncidentV1 {
    return IncidentV1ToJSONTyped(json, false);
}

export function IncidentV1ToJSONTyped(value?: IncidentV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'call_url': value['call_url'],
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'creator': ActorV1ToJSON(value['creator']),
        'custom_field_entries': ((value['custom_field_entries'] as Array<any>).map(CustomFieldEntryV1ToJSON)),
        'id': value['id'],
        'incident_role_assignments': ((value['incident_role_assignments'] as Array<any>).map(IncidentRoleAssignmentV1ToJSON)),
        'incident_type': IncidentTypeV1ToJSON(value['incident_type']),
        'mode': value['mode'],
        'name': value['name'],
        'permalink': value['permalink'],
        'postmortem_document_url': value['postmortem_document_url'],
        'reference': value['reference'],
        'severity': SeverityV1ToJSON(value['severity']),
        'slack_channel_id': value['slack_channel_id'],
        'slack_channel_name': value['slack_channel_name'],
        'slack_team_id': value['slack_team_id'],
        'status': value['status'],
        'summary': value['summary'],
        'timestamps': value['timestamps'] == null ? undefined : ((value['timestamps'] as Array<any>).map(IncidentTimestampValueV1ToJSON)),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
        'visibility': value['visibility'],
    };
}

