/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IncidentFormLifecycleElementConfigV3 } from './IncidentFormLifecycleElementConfigV3.js';
import {
    IncidentFormLifecycleElementConfigV3FromJSON,
    IncidentFormLifecycleElementConfigV3FromJSONTyped,
    IncidentFormLifecycleElementConfigV3ToJSON,
    IncidentFormLifecycleElementConfigV3ToJSONTyped,
} from './IncidentFormLifecycleElementConfigV3.js';
import type { EngineParamBindingPayloadV3 } from './EngineParamBindingPayloadV3.js';
import {
    EngineParamBindingPayloadV3FromJSON,
    EngineParamBindingPayloadV3FromJSONTyped,
    EngineParamBindingPayloadV3ToJSON,
    EngineParamBindingPayloadV3ToJSONTyped,
} from './EngineParamBindingPayloadV3.js';
import type { ConditionGroupPayloadV3 } from './ConditionGroupPayloadV3.js';
import {
    ConditionGroupPayloadV3FromJSON,
    ConditionGroupPayloadV3FromJSONTyped,
    ConditionGroupPayloadV3ToJSON,
    ConditionGroupPayloadV3ToJSONTyped,
} from './ConditionGroupPayloadV3.js';

/**
 * 
 * @export
 * @interface IncidentFormLifecycleElementPayloadV3
 */
export interface IncidentFormLifecycleElementPayloadV3 {
    /**
     * Whether the user can explicitly choose no value. Only meaningful for custom field elements.
     */
    can_select_no_value?: boolean;
    /**
     * 
     */
    config?: IncidentFormLifecycleElementConfigV3;
    /**
     * The custom field this element edits. Set only when element_type is custom_field.
     */
    custom_field_id?: string;
    /**
     * 
     */
    default_value?: EngineParamBindingPayloadV3;
    /**
     * Description shown beside this element, as markdown
     */
    description?: string;
    /**
     * What this element captures
     */
    element_type: IncidentFormLifecycleElementPayloadV3ElementTypeEnum;
    /**
     * Identifier of an existing divider or text element. Omit when adding an element.
     */
    id?: string;
    /**
     * The incident role this element assigns. Set only when element_type is incident_role.
     */
    incident_role_id?: string;
    /**
     * The incident timestamp this element sets. Set only when element_type is timestamp.
     */
    incident_timestamp_id?: string;
    /**
     * Placeholder text shown in the empty field
     */
    placeholder?: string;
    /**
     * When this element must be filled in
     */
    required_if?: IncidentFormLifecycleElementPayloadV3RequiredIfEnum;
    /**
     * Condition groups that make this element required. Used when required_if is check_engine_config.
     */
    required_if_condition_groups?: Array<ConditionGroupPayloadV3>;
    /**
     * The element is shown when any of these condition groups match. Unset means it is always shown.
     */
    show_if_condition_groups?: Array<ConditionGroupPayloadV3>;
}


/**
 * @export
 */
export const IncidentFormLifecycleElementPayloadV3ElementTypeEnum = {
    Name: 'name',
    Status: 'status',
    Severity: 'severity',
    IncidentRole: 'incident_role',
    IncidentType: 'incident_type',
    Summary: 'summary',
    CustomField: 'custom_field',
    Timestamp: 'timestamp',
    UpdateMessage: 'update_message',
    NextUpdateIn: 'next_update_in',
    Triage: 'triage',
    Visibility: 'visibility',
    Divider: 'divider',
    Text: 'text',
    IncidentAttachments: 'incident_attachments',
    SlackChannel: 'slack_channel',
    AnnounceRetroIncident: 'announce_retro_incident',
    EnterPostIncidentFlow: 'enter_post_incident_flow',
    InvestigationFeedback: 'investigation_feedback',
} as const;
export type IncidentFormLifecycleElementPayloadV3ElementTypeEnum = typeof IncidentFormLifecycleElementPayloadV3ElementTypeEnum[keyof typeof IncidentFormLifecycleElementPayloadV3ElementTypeEnum];

/**
 * @export
 */
export const IncidentFormLifecycleElementPayloadV3RequiredIfEnum = {
    CheckEngineConfig: 'check_engine_config',
    AlwaysRequire: 'always_require',
    NeverRequire: 'never_require',
} as const;
export type IncidentFormLifecycleElementPayloadV3RequiredIfEnum = typeof IncidentFormLifecycleElementPayloadV3RequiredIfEnum[keyof typeof IncidentFormLifecycleElementPayloadV3RequiredIfEnum];


/**
 * Check if a given object implements the IncidentFormLifecycleElementPayloadV3 interface.
 */
export function instanceOfIncidentFormLifecycleElementPayloadV3(value: object): value is IncidentFormLifecycleElementPayloadV3 {
    if (!('element_type' in value) || value['element_type'] === undefined) return false;
    return true;
}

export function IncidentFormLifecycleElementPayloadV3FromJSON(json: any): IncidentFormLifecycleElementPayloadV3 {
    return IncidentFormLifecycleElementPayloadV3FromJSONTyped(json, false);
}

export function IncidentFormLifecycleElementPayloadV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentFormLifecycleElementPayloadV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'can_select_no_value': json['can_select_no_value'] == null ? undefined : json['can_select_no_value'],
        'config': json['config'] == null ? undefined : IncidentFormLifecycleElementConfigV3FromJSON(json['config']),
        'custom_field_id': json['custom_field_id'] == null ? undefined : json['custom_field_id'],
        'default_value': json['default_value'] == null ? undefined : EngineParamBindingPayloadV3FromJSON(json['default_value']),
        'description': json['description'] == null ? undefined : json['description'],
        'element_type': json['element_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'incident_role_id': json['incident_role_id'] == null ? undefined : json['incident_role_id'],
        'incident_timestamp_id': json['incident_timestamp_id'] == null ? undefined : json['incident_timestamp_id'],
        'placeholder': json['placeholder'] == null ? undefined : json['placeholder'],
        'required_if': json['required_if'] == null ? undefined : json['required_if'],
        'required_if_condition_groups': json['required_if_condition_groups'] == null ? undefined : ((json['required_if_condition_groups'] as Array<any>).map(ConditionGroupPayloadV3FromJSON)),
        'show_if_condition_groups': json['show_if_condition_groups'] == null ? undefined : ((json['show_if_condition_groups'] as Array<any>).map(ConditionGroupPayloadV3FromJSON)),
    };
}

export function IncidentFormLifecycleElementPayloadV3ToJSON(json: any): IncidentFormLifecycleElementPayloadV3 {
    return IncidentFormLifecycleElementPayloadV3ToJSONTyped(json, false);
}

export function IncidentFormLifecycleElementPayloadV3ToJSONTyped(value?: IncidentFormLifecycleElementPayloadV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'can_select_no_value': value['can_select_no_value'],
        'config': IncidentFormLifecycleElementConfigV3ToJSON(value['config']),
        'custom_field_id': value['custom_field_id'],
        'default_value': EngineParamBindingPayloadV3ToJSON(value['default_value']),
        'description': value['description'],
        'element_type': value['element_type'],
        'id': value['id'],
        'incident_role_id': value['incident_role_id'],
        'incident_timestamp_id': value['incident_timestamp_id'],
        'placeholder': value['placeholder'],
        'required_if': value['required_if'],
        'required_if_condition_groups': value['required_if_condition_groups'] == null ? undefined : ((value['required_if_condition_groups'] as Array<any>).map(ConditionGroupPayloadV3ToJSON)),
        'show_if_condition_groups': value['show_if_condition_groups'] == null ? undefined : ((value['show_if_condition_groups'] as Array<any>).map(ConditionGroupPayloadV3ToJSON)),
    };
}

