/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IncidentTimestampV2 } from './IncidentTimestampV2.js';
import {
    IncidentTimestampV2FromJSON,
    IncidentTimestampV2FromJSONTyped,
    IncidentTimestampV2ToJSON,
    IncidentTimestampV2ToJSONTyped,
} from './IncidentTimestampV2.js';

/**
 * 
 * @export
 * @interface IncidentTimestampsListResultV2
 */
export interface IncidentTimestampsListResultV2 {
    /**
     * 
     */
    incident_timestamps: Array<IncidentTimestampV2>;
}

/**
 * Check if a given object implements the IncidentTimestampsListResultV2 interface.
 */
export function instanceOfIncidentTimestampsListResultV2(value: object): value is IncidentTimestampsListResultV2 {
    if (!('incident_timestamps' in value) || value['incident_timestamps'] === undefined) return false;
    return true;
}

export function IncidentTimestampsListResultV2FromJSON(json: any): IncidentTimestampsListResultV2 {
    return IncidentTimestampsListResultV2FromJSONTyped(json, false);
}

export function IncidentTimestampsListResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentTimestampsListResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'incident_timestamps': ((json['incident_timestamps'] as Array<any>).map(IncidentTimestampV2FromJSON)),
    };
}

export function IncidentTimestampsListResultV2ToJSON(json: any): IncidentTimestampsListResultV2 {
    return IncidentTimestampsListResultV2ToJSONTyped(json, false);
}

export function IncidentTimestampsListResultV2ToJSONTyped(value?: IncidentTimestampsListResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident_timestamps': ((value['incident_timestamps'] as Array<any>).map(IncidentTimestampV2ToJSON)),
    };
}

