/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IncidentV1 } from './IncidentV1.js';
import {
    IncidentV1FromJSON,
    IncidentV1FromJSONTyped,
    IncidentV1ToJSON,
    IncidentV1ToJSONTyped,
} from './IncidentV1.js';

/**
 * 
 * @export
 * @interface IncidentsCreateResultV1
 */
export interface IncidentsCreateResultV1 {
    /**
     * 
     */
    incident: IncidentV1;
}

/**
 * Check if a given object implements the IncidentsCreateResultV1 interface.
 */
export function instanceOfIncidentsCreateResultV1(value: object): value is IncidentsCreateResultV1 {
    if (!('incident' in value) || value['incident'] === undefined) return false;
    return true;
}

export function IncidentsCreateResultV1FromJSON(json: any): IncidentsCreateResultV1 {
    return IncidentsCreateResultV1FromJSONTyped(json, false);
}

export function IncidentsCreateResultV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentsCreateResultV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'incident': IncidentV1FromJSON(json['incident']),
    };
}

export function IncidentsCreateResultV1ToJSON(json: any): IncidentsCreateResultV1 {
    return IncidentsCreateResultV1ToJSONTyped(json, false);
}

export function IncidentsCreateResultV1ToJSONTyped(value?: IncidentsCreateResultV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident': IncidentV1ToJSON(value['incident']),
    };
}

