/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { IncidentActivityLogContentV2 } from './IncidentActivityLogContentV2.js';
import {
    IncidentActivityLogContentV2FromJSON,
    IncidentActivityLogContentV2FromJSONTyped,
    IncidentActivityLogContentV2ToJSON,
    IncidentActivityLogContentV2ToJSONTyped,
} from './IncidentActivityLogContentV2.js';

/**
 * One thing that happened on an incident.
 * 
 * The activity log records everything. The timeline is the narrative, made of the entries
 * someone promoted onto it and the items they wrote by hand.
 * @export
 * @interface IncidentActivityLogEntryV2
 */
export interface IncidentActivityLogEntryV2 {
    /**
     * 
     */
    content?: IncidentActivityLogContentV2;
    /**
     * When we recorded the activity
     */
    created_at: Date;
    /**
     * Unique identifier of the activity log entry
     */
    id: string;
    /**
     * ID of the incident this happened on. When the incident has streams, listing the parent also returns entries from its streams, and this is the stream's ID for those.
     */
    incident_id: string;
    /**
     * When the activity happened. This is what the log is ordered by.
     */
    occurred_at: Date;
    /**
     * Human-readable summary of what happened
     */
    title: string;
    /**
     * What kind of activity this is. Switch on this rather than title, which is display copy we reword.
     */
    type: IncidentActivityLogEntryV2TypeEnum;
}


/**
 * @export
 */
export const IncidentActivityLogEntryV2TypeEnum = {
    SlackPin: 'slack_pin',
    MicrosoftTeamsPinnedChannelMessage: 'microsoft_teams_pinned_channel_message',
    SummaryUpdate: 'summary_update',
    RoleUpdate: 'role_update',
    Handover: 'handover',
    SlackInferSentry: 'slack_infer_sentry',
    SlackImage: 'slack_image',
    MicrosoftTeamsImage: 'microsoft_teams_image',
    SlackMessage: 'slack_message',
    IncidentChannelJoin: 'incident_channel_join',
    IncidentChannelLeave: 'incident_channel_leave',
    IncidentEscalate: 'incident_escalate',
    ActionCreated: 'action_created',
    ActionUpdated: 'action_updated',
    FollowUpCreated: 'follow_up_created',
    FollowUpUpdated: 'follow_up_updated',
    ActionsSharedInChannel: 'actions_shared_in_channel',
    FollowUpsSharedInChannel: 'follow_ups_shared_in_channel',
    StatusChange: 'status_change',
    AtlassianStatuspageUpdate: 'atlassian_statuspage_update',
    IncidentUpdate: 'incident_update',
    CustomFieldValueUpdate: 'custom_field_value_update',
    IncidentMembershipRevoked: 'incident_membership_revoked',
    IncidentVisibilityChanged: 'incident_visibility_changed',
    IncidentRename: 'incident_rename',
    IncidentAttachmentAdded: 'incident_attachment_added',
    IncidentAttachmentRemoved: 'incident_attachment_removed',
    AlertAttachedToIncident: 'alert_attached_to_incident',
    AlertGroupAttachedToIncident: 'alert_group_attached_to_incident',
    AlertGroupDetachedFromIncident: 'alert_group_detached_from_incident',
    PagerdutyIncidentTriggered: 'pagerduty_incident_triggered',
    PagerdutyIncidentAcknowledged: 'pagerduty_incident_acknowledged',
    PagerdutyIncidentResolved: 'pagerduty_incident_resolved',
    IncidentTimestampSet: 'incident_timestamp_set',
    IncidentTimestampOccurred: 'incident_timestamp_occurred',
    IncidentMerged: 'incident_merged',
    IncidentTypeChanged: 'incident_type_changed',
    StatusPageIncidentLinked: 'status_page_incident_linked',
    StatusPageIncidentUpdated: 'status_page_incident_updated',
    UserIntentDeclared: 'user_intent_declared',
    CallUrlChanged: 'call_url_changed',
    PostmortemChanged: 'postmortem_changed',
    PostmortemDocumentV2Changed: 'postmortem_document_v2_changed',
    IncidentChannelCreated: 'incident_channel_created',
    Scrub: 'scrub',
    EscalationCreated: 'escalation_created',
    EscalationAcknowledged: 'escalation_acknowledged',
    IncidentCallCreated: 'incident_call_created',
    IncidentCallStarted: 'incident_call_started',
    IncidentCallEnded: 'incident_call_ended',
    IncidentCallParticipantsUpdated: 'incident_call_participants_updated',
    MicrosoftTeamsMessage: 'microsoft_teams_message',
    MicrosoftTeamsAnnouncementReply: 'microsoft_teams_announcement_reply',
    IncidentCallTranscriptMessage: 'incident_call_transcript_message',
    IncidentCallTranscriptSummaryGenerated: 'incident_call_transcript_summary_generated',
    IncidentCallTranscriptKeyMomentGenerated: 'incident_call_transcript_key_moment_generated',
    IncidentCallTranscriptCurrentTopicGenerated: 'incident_call_transcript_current_topic_generated',
    IncidentCallRecallBotStatusChanged: 'incident_call_recall_bot_status_changed',
    ScribeAdded: 'scribe_added',
    ScribeRemoved: 'scribe_removed',
    ExternalIssueCommentSynced: 'external_issue_comment_synced',
    InvestigationHypothesisUpdate: 'investigation_hypothesis_update',
    WorkflowRan: 'workflow_ran',
} as const;
export type IncidentActivityLogEntryV2TypeEnum = typeof IncidentActivityLogEntryV2TypeEnum[keyof typeof IncidentActivityLogEntryV2TypeEnum];


/**
 * Check if a given object implements the IncidentActivityLogEntryV2 interface.
 */
export function instanceOfIncidentActivityLogEntryV2(value: object): value is IncidentActivityLogEntryV2 {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('incident_id' in value) || value['incident_id'] === undefined) return false;
    if (!('occurred_at' in value) || value['occurred_at'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function IncidentActivityLogEntryV2FromJSON(json: any): IncidentActivityLogEntryV2 {
    return IncidentActivityLogEntryV2FromJSONTyped(json, false);
}

export function IncidentActivityLogEntryV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentActivityLogEntryV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : IncidentActivityLogContentV2FromJSON(json['content']),
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'id': json['id'],
        'incident_id': json['incident_id'],
        'occurred_at': (json['occurred_at'] == null ? json['occurred_at'] : parseDateTime(json['occurred_at'])),
        'title': json['title'],
        'type': json['type'],
    };
}

export function IncidentActivityLogEntryV2ToJSON(json: any): IncidentActivityLogEntryV2 {
    return IncidentActivityLogEntryV2ToJSONTyped(json, false);
}

export function IncidentActivityLogEntryV2ToJSONTyped(value?: IncidentActivityLogEntryV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': IncidentActivityLogContentV2ToJSON(value['content']),
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'id': value['id'],
        'incident_id': value['incident_id'],
        'occurred_at': value['occurred_at'] == null ? value['occurred_at'] : serializeDateTime(value['occurred_at']),
        'title': value['title'],
        'type': value['type'],
    };
}

