/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EngineParamBindingV3 } from './EngineParamBindingV3.js';
import {
    EngineParamBindingV3FromJSON,
    EngineParamBindingV3FromJSONTyped,
    EngineParamBindingV3ToJSON,
    EngineParamBindingV3ToJSONTyped,
} from './EngineParamBindingV3.js';

/**
 * 
 * @export
 * @interface IncidentTemplateCustomFieldBindingV1
 */
export interface IncidentTemplateCustomFieldBindingV1 {
    /**
     * 
     */
    binding: EngineParamBindingV3;
    /**
     * ID of the custom field
     */
    custom_field_id: string;
    /**
     * The strategy to use when multiple alerts match this route
     */
    merge_strategy: IncidentTemplateCustomFieldBindingV1MergeStrategyEnum;
}


/**
 * @export
 */
export const IncidentTemplateCustomFieldBindingV1MergeStrategyEnum = {
    FirstWins: 'first-wins',
    LastWins: 'last-wins',
    Append: 'append',
} as const;
export type IncidentTemplateCustomFieldBindingV1MergeStrategyEnum = typeof IncidentTemplateCustomFieldBindingV1MergeStrategyEnum[keyof typeof IncidentTemplateCustomFieldBindingV1MergeStrategyEnum];


/**
 * Check if a given object implements the IncidentTemplateCustomFieldBindingV1 interface.
 */
export function instanceOfIncidentTemplateCustomFieldBindingV1(value: object): value is IncidentTemplateCustomFieldBindingV1 {
    if (!('binding' in value) || value['binding'] === undefined) return false;
    if (!('custom_field_id' in value) || value['custom_field_id'] === undefined) return false;
    if (!('merge_strategy' in value) || value['merge_strategy'] === undefined) return false;
    return true;
}

export function IncidentTemplateCustomFieldBindingV1FromJSON(json: any): IncidentTemplateCustomFieldBindingV1 {
    return IncidentTemplateCustomFieldBindingV1FromJSONTyped(json, false);
}

export function IncidentTemplateCustomFieldBindingV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentTemplateCustomFieldBindingV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'binding': EngineParamBindingV3FromJSON(json['binding']),
        'custom_field_id': json['custom_field_id'],
        'merge_strategy': json['merge_strategy'],
    };
}

export function IncidentTemplateCustomFieldBindingV1ToJSON(json: any): IncidentTemplateCustomFieldBindingV1 {
    return IncidentTemplateCustomFieldBindingV1ToJSONTyped(json, false);
}

export function IncidentTemplateCustomFieldBindingV1ToJSONTyped(value?: IncidentTemplateCustomFieldBindingV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'binding': EngineParamBindingV3ToJSON(value['binding']),
        'custom_field_id': value['custom_field_id'],
        'merge_strategy': value['merge_strategy'],
    };
}

