/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IncidentTeamMembershipsRevokePayloadV1
 */
export interface IncidentTeamMembershipsRevokePayloadV1 {
    /**
     * Revoke team access to this incident
     */
    incident_id: string;
    /**
     * 
     */
    team_id: string;
}

/**
 * Check if a given object implements the IncidentTeamMembershipsRevokePayloadV1 interface.
 */
export function instanceOfIncidentTeamMembershipsRevokePayloadV1(value: object): value is IncidentTeamMembershipsRevokePayloadV1 {
    if (!('incident_id' in value) || value['incident_id'] === undefined) return false;
    if (!('team_id' in value) || value['team_id'] === undefined) return false;
    return true;
}

export function IncidentTeamMembershipsRevokePayloadV1FromJSON(json: any): IncidentTeamMembershipsRevokePayloadV1 {
    return IncidentTeamMembershipsRevokePayloadV1FromJSONTyped(json, false);
}

export function IncidentTeamMembershipsRevokePayloadV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentTeamMembershipsRevokePayloadV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'incident_id': json['incident_id'],
        'team_id': json['team_id'],
    };
}

export function IncidentTeamMembershipsRevokePayloadV1ToJSON(json: any): IncidentTeamMembershipsRevokePayloadV1 {
    return IncidentTeamMembershipsRevokePayloadV1ToJSONTyped(json, false);
}

export function IncidentTeamMembershipsRevokePayloadV1ToJSONTyped(value?: IncidentTeamMembershipsRevokePayloadV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident_id': value['incident_id'],
        'team_id': value['team_id'],
    };
}

