/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IncidentRoleV1 } from './IncidentRoleV1.js';
import {
    IncidentRoleV1FromJSON,
    IncidentRoleV1FromJSONTyped,
    IncidentRoleV1ToJSON,
    IncidentRoleV1ToJSONTyped,
} from './IncidentRoleV1.js';

/**
 * 
 * @export
 * @interface IncidentRolesListResultV1
 */
export interface IncidentRolesListResultV1 {
    /**
     * 
     */
    incident_roles: Array<IncidentRoleV1>;
}

/**
 * Check if a given object implements the IncidentRolesListResultV1 interface.
 */
export function instanceOfIncidentRolesListResultV1(value: object): value is IncidentRolesListResultV1 {
    if (!('incident_roles' in value) || value['incident_roles'] === undefined) return false;
    return true;
}

export function IncidentRolesListResultV1FromJSON(json: any): IncidentRolesListResultV1 {
    return IncidentRolesListResultV1FromJSONTyped(json, false);
}

export function IncidentRolesListResultV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentRolesListResultV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'incident_roles': ((json['incident_roles'] as Array<any>).map(IncidentRoleV1FromJSON)),
    };
}

export function IncidentRolesListResultV1ToJSON(json: any): IncidentRolesListResultV1 {
    return IncidentRolesListResultV1ToJSONTyped(json, false);
}

export function IncidentRolesListResultV1ToJSONTyped(value?: IncidentRolesListResultV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident_roles': ((value['incident_roles'] as Array<any>).map(IncidentRoleV1ToJSON)),
    };
}

