/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IncidentFormV3 } from './IncidentFormV3.js';
import {
    IncidentFormV3FromJSON,
    IncidentFormV3FromJSONTyped,
    IncidentFormV3ToJSON,
    IncidentFormV3ToJSONTyped,
} from './IncidentFormV3.js';

/**
 * 
 * @export
 * @interface IncidentFormsUpdateResultV3
 */
export interface IncidentFormsUpdateResultV3 {
    /**
     * 
     */
    incident_form: IncidentFormV3;
}

/**
 * Check if a given object implements the IncidentFormsUpdateResultV3 interface.
 */
export function instanceOfIncidentFormsUpdateResultV3(value: object): value is IncidentFormsUpdateResultV3 {
    if (!('incident_form' in value) || value['incident_form'] === undefined) return false;
    return true;
}

export function IncidentFormsUpdateResultV3FromJSON(json: any): IncidentFormsUpdateResultV3 {
    return IncidentFormsUpdateResultV3FromJSONTyped(json, false);
}

export function IncidentFormsUpdateResultV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentFormsUpdateResultV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'incident_form': IncidentFormV3FromJSON(json['incident_form']),
    };
}

export function IncidentFormsUpdateResultV3ToJSON(json: any): IncidentFormsUpdateResultV3 {
    return IncidentFormsUpdateResultV3ToJSONTyped(json, false);
}

export function IncidentFormsUpdateResultV3ToJSONTyped(value?: IncidentFormsUpdateResultV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incident_form': IncidentFormV3ToJSON(value['incident_form']),
    };
}

