/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IncidentStatusesUpdatePayloadV1
 */
export interface IncidentStatusesUpdatePayloadV1 {
    /**
     * Rich text description of the incident status
     */
    description: string;
    /**
     * Unique name of this status
     */
    name: string;
    /**
     * Where this status sits within its category, lowest rank first. No two statuses in the same category can share a rank, but ranks needn't run consecutively — leaving gaps (10, 20, 30) means you can later insert a status between two others without renumbering them. Omit it to leave this status where it is.
     */
    rank?: number;
}

/**
 * Check if a given object implements the IncidentStatusesUpdatePayloadV1 interface.
 */
export function instanceOfIncidentStatusesUpdatePayloadV1(value: object): value is IncidentStatusesUpdatePayloadV1 {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function IncidentStatusesUpdatePayloadV1FromJSON(json: any): IncidentStatusesUpdatePayloadV1 {
    return IncidentStatusesUpdatePayloadV1FromJSONTyped(json, false);
}

export function IncidentStatusesUpdatePayloadV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IncidentStatusesUpdatePayloadV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'name': json['name'],
        'rank': json['rank'] == null ? undefined : json['rank'],
    };
}

export function IncidentStatusesUpdatePayloadV1ToJSON(json: any): IncidentStatusesUpdatePayloadV1 {
    return IncidentStatusesUpdatePayloadV1ToJSONTyped(json, false);
}

export function IncidentStatusesUpdatePayloadV1ToJSONTyped(value?: IncidentStatusesUpdatePayloadV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'rank': value['rank'],
    };
}

