/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface NewSlackUserGroupPayloadV2
 */
export interface NewSlackUserGroupPayloadV2 {
    /**
     * Description of the user group
     */
    description: string;
    /**
     * Handle of the user group
     */
    handle: string;
    /**
     * Name of the user group
     */
    name: string;
    /**
     * Slack workspace ID where the user group should be created. Required for Enterprise Grid organizations with multiple workspaces.
     */
    slack_team_id?: string;
}

/**
 * Check if a given object implements the NewSlackUserGroupPayloadV2 interface.
 */
export function instanceOfNewSlackUserGroupPayloadV2(value: object): value is NewSlackUserGroupPayloadV2 {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('handle' in value) || value['handle'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NewSlackUserGroupPayloadV2FromJSON(json: any): NewSlackUserGroupPayloadV2 {
    return NewSlackUserGroupPayloadV2FromJSONTyped(json, false);
}

export function NewSlackUserGroupPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSlackUserGroupPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'handle': json['handle'],
        'name': json['name'],
        'slack_team_id': json['slack_team_id'] == null ? undefined : json['slack_team_id'],
    };
}

export function NewSlackUserGroupPayloadV2ToJSON(json: any): NewSlackUserGroupPayloadV2 {
    return NewSlackUserGroupPayloadV2ToJSONTyped(json, false);
}

export function NewSlackUserGroupPayloadV2ToJSONTyped(value?: NewSlackUserGroupPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'handle': value['handle'],
        'name': value['name'],
        'slack_team_id': value['slack_team_id'],
    };
}

