/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PayConfigsUpdatePayloadV2
 */
export interface PayConfigsUpdatePayloadV2 {
    /**
     * Rate paid for any time no rule covers, in the lowest denomination of the currency
     */
    base_rate_cents: number;
    /**
     * Currency this config pays in, in ISO 4217 format
     */
    currency: string;
    /**
     * Human readable name for this pay config
     */
    name: string;
    /**
     * The unit of time every rate on this config is quoted per. Pay is pro-rated by the second either way.
     */
    rate_time_unit: PayConfigsUpdatePayloadV2RateTimeUnitEnum;
    /**
     * IANA timezone this config's rules are interpreted in
     */
    timezone: string;
}


/**
 * @export
 */
export const PayConfigsUpdatePayloadV2RateTimeUnitEnum = {
    Hour: 'hour',
    Day: 'day',
} as const;
export type PayConfigsUpdatePayloadV2RateTimeUnitEnum = typeof PayConfigsUpdatePayloadV2RateTimeUnitEnum[keyof typeof PayConfigsUpdatePayloadV2RateTimeUnitEnum];


/**
 * Check if a given object implements the PayConfigsUpdatePayloadV2 interface.
 */
export function instanceOfPayConfigsUpdatePayloadV2(value: object): value is PayConfigsUpdatePayloadV2 {
    if (!('base_rate_cents' in value) || value['base_rate_cents'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rate_time_unit' in value) || value['rate_time_unit'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    return true;
}

export function PayConfigsUpdatePayloadV2FromJSON(json: any): PayConfigsUpdatePayloadV2 {
    return PayConfigsUpdatePayloadV2FromJSONTyped(json, false);
}

export function PayConfigsUpdatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PayConfigsUpdatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'base_rate_cents': json['base_rate_cents'],
        'currency': json['currency'],
        'name': json['name'],
        'rate_time_unit': json['rate_time_unit'],
        'timezone': json['timezone'],
    };
}

export function PayConfigsUpdatePayloadV2ToJSON(json: any): PayConfigsUpdatePayloadV2 {
    return PayConfigsUpdatePayloadV2ToJSONTyped(json, false);
}

export function PayConfigsUpdatePayloadV2ToJSONTyped(value?: PayConfigsUpdatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base_rate_cents': value['base_rate_cents'],
        'currency': value['currency'],
        'name': value['name'],
        'rate_time_unit': value['rate_time_unit'],
        'timezone': value['timezone'],
    };
}

