/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PayConfigWeeklyRuleV2 } from './PayConfigWeeklyRuleV2.js';
import {
    PayConfigWeeklyRuleV2FromJSON,
    PayConfigWeeklyRuleV2FromJSONTyped,
    PayConfigWeeklyRuleV2ToJSON,
    PayConfigWeeklyRuleV2ToJSONTyped,
} from './PayConfigWeeklyRuleV2.js';

/**
 * 
 * @export
 * @interface PayConfigsShowWeeklyRuleResultV2
 */
export interface PayConfigsShowWeeklyRuleResultV2 {
    /**
     * 
     */
    weekly_rule: PayConfigWeeklyRuleV2;
}

/**
 * Check if a given object implements the PayConfigsShowWeeklyRuleResultV2 interface.
 */
export function instanceOfPayConfigsShowWeeklyRuleResultV2(value: object): value is PayConfigsShowWeeklyRuleResultV2 {
    if (!('weekly_rule' in value) || value['weekly_rule'] === undefined) return false;
    return true;
}

export function PayConfigsShowWeeklyRuleResultV2FromJSON(json: any): PayConfigsShowWeeklyRuleResultV2 {
    return PayConfigsShowWeeklyRuleResultV2FromJSONTyped(json, false);
}

export function PayConfigsShowWeeklyRuleResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PayConfigsShowWeeklyRuleResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'weekly_rule': PayConfigWeeklyRuleV2FromJSON(json['weekly_rule']),
    };
}

export function PayConfigsShowWeeklyRuleResultV2ToJSON(json: any): PayConfigsShowWeeklyRuleResultV2 {
    return PayConfigsShowWeeklyRuleResultV2ToJSONTyped(json, false);
}

export function PayConfigsShowWeeklyRuleResultV2ToJSONTyped(value?: PayConfigsShowWeeklyRuleResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weekly_rule': PayConfigWeeklyRuleV2ToJSON(value['weekly_rule']),
    };
}

