/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PayConfigWeeklyRuleV2 } from './PayConfigWeeklyRuleV2.js';
import {
    PayConfigWeeklyRuleV2FromJSON,
    PayConfigWeeklyRuleV2FromJSONTyped,
    PayConfigWeeklyRuleV2ToJSON,
    PayConfigWeeklyRuleV2ToJSONTyped,
} from './PayConfigWeeklyRuleV2.js';

/**
 * 
 * @export
 * @interface PayConfigsListWeeklyRulesResultV2
 */
export interface PayConfigsListWeeklyRulesResultV2 {
    /**
     * 
     */
    weekly_rules: Array<PayConfigWeeklyRuleV2>;
}

/**
 * Check if a given object implements the PayConfigsListWeeklyRulesResultV2 interface.
 */
export function instanceOfPayConfigsListWeeklyRulesResultV2(value: object): value is PayConfigsListWeeklyRulesResultV2 {
    if (!('weekly_rules' in value) || value['weekly_rules'] === undefined) return false;
    return true;
}

export function PayConfigsListWeeklyRulesResultV2FromJSON(json: any): PayConfigsListWeeklyRulesResultV2 {
    return PayConfigsListWeeklyRulesResultV2FromJSONTyped(json, false);
}

export function PayConfigsListWeeklyRulesResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PayConfigsListWeeklyRulesResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'weekly_rules': ((json['weekly_rules'] as Array<any>).map(PayConfigWeeklyRuleV2FromJSON)),
    };
}

export function PayConfigsListWeeklyRulesResultV2ToJSON(json: any): PayConfigsListWeeklyRulesResultV2 {
    return PayConfigsListWeeklyRulesResultV2ToJSONTyped(json, false);
}

export function PayConfigsListWeeklyRulesResultV2ToJSONTyped(value?: PayConfigsListWeeklyRulesResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weekly_rules': ((value['weekly_rules'] as Array<any>).map(PayConfigWeeklyRuleV2ToJSON)),
    };
}

