/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Narrows one of a report's schedules to some of its rotations.
 * @export
 * @interface PayReportRotationFilterV2
 */
export interface PayReportRotationFilterV2 {
    /**
     * Which of the schedule's rotations to include. To include all of them, leave this schedule out of rotation_filters rather than listing every rotation here.
     */
    rotation_ids: Array<string>;
    /**
     * The schedule to narrow. Must also appear in schedule_ids.
     */
    schedule_id: string;
}

/**
 * Check if a given object implements the PayReportRotationFilterV2 interface.
 */
export function instanceOfPayReportRotationFilterV2(value: object): value is PayReportRotationFilterV2 {
    if (!('rotation_ids' in value) || value['rotation_ids'] === undefined) return false;
    if (!('schedule_id' in value) || value['schedule_id'] === undefined) return false;
    return true;
}

export function PayReportRotationFilterV2FromJSON(json: any): PayReportRotationFilterV2 {
    return PayReportRotationFilterV2FromJSONTyped(json, false);
}

export function PayReportRotationFilterV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PayReportRotationFilterV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'rotation_ids': json['rotation_ids'],
        'schedule_id': json['schedule_id'],
    };
}

export function PayReportRotationFilterV2ToJSON(json: any): PayReportRotationFilterV2 {
    return PayReportRotationFilterV2ToJSONTyped(json, false);
}

export function PayReportRotationFilterV2ToJSONTyped(value?: PayReportRotationFilterV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rotation_ids': value['rotation_ids'],
        'schedule_id': value['schedule_id'],
    };
}

