/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PayReportV2 } from './PayReportV2.js';
import {
    PayReportV2FromJSON,
    PayReportV2FromJSONTyped,
    PayReportV2ToJSON,
    PayReportV2ToJSONTyped,
} from './PayReportV2.js';

/**
 * 
 * @export
 * @interface PayReportsCreateResultV2
 */
export interface PayReportsCreateResultV2 {
    /**
     * 
     */
    pay_report: PayReportV2;
}

/**
 * Check if a given object implements the PayReportsCreateResultV2 interface.
 */
export function instanceOfPayReportsCreateResultV2(value: object): value is PayReportsCreateResultV2 {
    if (!('pay_report' in value) || value['pay_report'] === undefined) return false;
    return true;
}

export function PayReportsCreateResultV2FromJSON(json: any): PayReportsCreateResultV2 {
    return PayReportsCreateResultV2FromJSONTyped(json, false);
}

export function PayReportsCreateResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PayReportsCreateResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'pay_report': PayReportV2FromJSON(json['pay_report']),
    };
}

export function PayReportsCreateResultV2ToJSON(json: any): PayReportsCreateResultV2 {
    return PayReportsCreateResultV2ToJSONTyped(json, false);
}

export function PayReportsCreateResultV2ToJSONTyped(value?: PayReportsCreateResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pay_report': PayReportV2ToJSON(value['pay_report']),
    };
}

