/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PaginationMetaResultV2 } from './PaginationMetaResultV2.js';
import {
    PaginationMetaResultV2FromJSON,
    PaginationMetaResultV2FromJSONTyped,
    PaginationMetaResultV2ToJSON,
    PaginationMetaResultV2ToJSONTyped,
} from './PaginationMetaResultV2.js';
import type { PolicyFindingV2 } from './PolicyFindingV2.js';
import {
    PolicyFindingV2FromJSON,
    PolicyFindingV2FromJSONTyped,
    PolicyFindingV2ToJSON,
    PolicyFindingV2ToJSONTyped,
} from './PolicyFindingV2.js';

/**
 * 
 * @export
 * @interface PolicyFindingsListResultV2
 */
export interface PolicyFindingsListResultV2 {
    /**
     * 
     */
    pagination_meta: PaginationMetaResultV2;
    /**
     * 
     */
    policy_findings: Array<PolicyFindingV2>;
}

/**
 * Check if a given object implements the PolicyFindingsListResultV2 interface.
 */
export function instanceOfPolicyFindingsListResultV2(value: object): value is PolicyFindingsListResultV2 {
    if (!('pagination_meta' in value) || value['pagination_meta'] === undefined) return false;
    if (!('policy_findings' in value) || value['policy_findings'] === undefined) return false;
    return true;
}

export function PolicyFindingsListResultV2FromJSON(json: any): PolicyFindingsListResultV2 {
    return PolicyFindingsListResultV2FromJSONTyped(json, false);
}

export function PolicyFindingsListResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyFindingsListResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination_meta': PaginationMetaResultV2FromJSON(json['pagination_meta']),
        'policy_findings': ((json['policy_findings'] as Array<any>).map(PolicyFindingV2FromJSON)),
    };
}

export function PolicyFindingsListResultV2ToJSON(json: any): PolicyFindingsListResultV2 {
    return PolicyFindingsListResultV2ToJSONTyped(json, false);
}

export function PolicyFindingsListResultV2ToJSONTyped(value?: PolicyFindingsListResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination_meta': PaginationMetaResultV2ToJSON(value['pagination_meta']),
        'policy_findings': ((value['policy_findings'] as Array<any>).map(PolicyFindingV2ToJSON)),
    };
}

