/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { PolicyFindingScheduleImpactedUserV2 } from './PolicyFindingScheduleImpactedUserV2.js';
import {
    PolicyFindingScheduleImpactedUserV2FromJSON,
    PolicyFindingScheduleImpactedUserV2FromJSONTyped,
    PolicyFindingScheduleImpactedUserV2ToJSON,
    PolicyFindingScheduleImpactedUserV2ToJSONTyped,
} from './PolicyFindingScheduleImpactedUserV2.js';

/**
 * Set when policy_type is schedule. Describes a gap in on-call cover.
 * @export
 * @interface PolicyFindingScheduleV2
 */
export interface PolicyFindingScheduleV2 {
    /**
     * Why the gap exists
     */
    cause?: PolicyFindingScheduleV2CauseEnum;
    /**
     * When the gap ends
     */
    end_at: Date;
    /**
     * Whether part of the gap has nobody scheduled at all, so impacted_users doesn't fully explain it
     */
    has_unscheduled_time?: boolean;
    /**
     * Users scheduled across the gap whose entries don't count as cover
     */
    impacted_users?: Array<PolicyFindingScheduleImpactedUserV2>;
    /**
     * The rotation with the gap, when the policy evaluates per rotation
     */
    rotation_id?: string;
    /**
     * The schedule with the gap
     */
    schedule_id: string;
    /**
     * When the gap starts
     */
    start_at: Date;
}


/**
 * @export
 */
export const PolicyFindingScheduleV2CauseEnum = {
    NobodyScheduled: 'nobody_scheduled',
    NoOnCallSeat: 'no_on_call_seat',
    UserDeactivated: 'user_deactivated',
    NotificationsPaused: 'notifications_paused',
} as const;
export type PolicyFindingScheduleV2CauseEnum = typeof PolicyFindingScheduleV2CauseEnum[keyof typeof PolicyFindingScheduleV2CauseEnum];


/**
 * Check if a given object implements the PolicyFindingScheduleV2 interface.
 */
export function instanceOfPolicyFindingScheduleV2(value: object): value is PolicyFindingScheduleV2 {
    if (!('end_at' in value) || value['end_at'] === undefined) return false;
    if (!('schedule_id' in value) || value['schedule_id'] === undefined) return false;
    if (!('start_at' in value) || value['start_at'] === undefined) return false;
    return true;
}

export function PolicyFindingScheduleV2FromJSON(json: any): PolicyFindingScheduleV2 {
    return PolicyFindingScheduleV2FromJSONTyped(json, false);
}

export function PolicyFindingScheduleV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyFindingScheduleV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'cause': json['cause'] == null ? undefined : json['cause'],
        'end_at': (json['end_at'] == null ? json['end_at'] : parseDateTime(json['end_at'])),
        'has_unscheduled_time': json['has_unscheduled_time'] == null ? undefined : json['has_unscheduled_time'],
        'impacted_users': json['impacted_users'] == null ? undefined : ((json['impacted_users'] as Array<any>).map(PolicyFindingScheduleImpactedUserV2FromJSON)),
        'rotation_id': json['rotation_id'] == null ? undefined : json['rotation_id'],
        'schedule_id': json['schedule_id'],
        'start_at': (json['start_at'] == null ? json['start_at'] : parseDateTime(json['start_at'])),
    };
}

export function PolicyFindingScheduleV2ToJSON(json: any): PolicyFindingScheduleV2 {
    return PolicyFindingScheduleV2ToJSONTyped(json, false);
}

export function PolicyFindingScheduleV2ToJSONTyped(value?: PolicyFindingScheduleV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cause': value['cause'],
        'end_at': value['end_at'] == null ? value['end_at'] : serializeDateTime(value['end_at']),
        'has_unscheduled_time': value['has_unscheduled_time'],
        'impacted_users': value['impacted_users'] == null ? undefined : ((value['impacted_users'] as Array<any>).map(PolicyFindingScheduleImpactedUserV2ToJSON)),
        'rotation_id': value['rotation_id'],
        'schedule_id': value['schedule_id'],
        'start_at': value['start_at'] == null ? value['start_at'] : serializeDateTime(value['start_at']),
    };
}

