/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PaginationMetaResultV2 } from './PaginationMetaResultV2.js';
import {
    PaginationMetaResultV2FromJSON,
    PaginationMetaResultV2FromJSONTyped,
    PaginationMetaResultV2ToJSON,
    PaginationMetaResultV2ToJSONTyped,
} from './PaginationMetaResultV2.js';
import type { PolicyV2 } from './PolicyV2.js';
import {
    PolicyV2FromJSON,
    PolicyV2FromJSONTyped,
    PolicyV2ToJSON,
    PolicyV2ToJSONTyped,
} from './PolicyV2.js';

/**
 * 
 * @export
 * @interface PoliciesListResultV2
 */
export interface PoliciesListResultV2 {
    /**
     * 
     */
    pagination_meta: PaginationMetaResultV2;
    /**
     * 
     */
    policies: Array<PolicyV2>;
}

/**
 * Check if a given object implements the PoliciesListResultV2 interface.
 */
export function instanceOfPoliciesListResultV2(value: object): value is PoliciesListResultV2 {
    if (!('pagination_meta' in value) || value['pagination_meta'] === undefined) return false;
    if (!('policies' in value) || value['policies'] === undefined) return false;
    return true;
}

export function PoliciesListResultV2FromJSON(json: any): PoliciesListResultV2 {
    return PoliciesListResultV2FromJSONTyped(json, false);
}

export function PoliciesListResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PoliciesListResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination_meta': PaginationMetaResultV2FromJSON(json['pagination_meta']),
        'policies': ((json['policies'] as Array<any>).map(PolicyV2FromJSON)),
    };
}

export function PoliciesListResultV2ToJSON(json: any): PoliciesListResultV2 {
    return PoliciesListResultV2ToJSONTyped(json, false);
}

export function PoliciesListResultV2ToJSONTyped(value?: PoliciesListResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination_meta': PaginationMetaResultV2ToJSON(value['pagination_meta']),
        'policies': ((value['policies'] as Array<any>).map(PolicyV2ToJSON)),
    };
}

