/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PolicyFindingScheduleImpactedUserV2
 */
export interface PolicyFindingScheduleImpactedUserV2 {
    /**
     * Why this user's entries don't count as cover
     */
    cause: PolicyFindingScheduleImpactedUserV2CauseEnum;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    user_id: string;
}


/**
 * @export
 */
export const PolicyFindingScheduleImpactedUserV2CauseEnum = {
    NoOnCallSeat: 'no_on_call_seat',
    UserDeactivated: 'user_deactivated',
} as const;
export type PolicyFindingScheduleImpactedUserV2CauseEnum = typeof PolicyFindingScheduleImpactedUserV2CauseEnum[keyof typeof PolicyFindingScheduleImpactedUserV2CauseEnum];


/**
 * Check if a given object implements the PolicyFindingScheduleImpactedUserV2 interface.
 */
export function instanceOfPolicyFindingScheduleImpactedUserV2(value: object): value is PolicyFindingScheduleImpactedUserV2 {
    if (!('cause' in value) || value['cause'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function PolicyFindingScheduleImpactedUserV2FromJSON(json: any): PolicyFindingScheduleImpactedUserV2 {
    return PolicyFindingScheduleImpactedUserV2FromJSONTyped(json, false);
}

export function PolicyFindingScheduleImpactedUserV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyFindingScheduleImpactedUserV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'cause': json['cause'],
        'name': json['name'],
        'user_id': json['user_id'],
    };
}

export function PolicyFindingScheduleImpactedUserV2ToJSON(json: any): PolicyFindingScheduleImpactedUserV2 {
    return PolicyFindingScheduleImpactedUserV2ToJSONTyped(json, false);
}

export function PolicyFindingScheduleImpactedUserV2ToJSONTyped(value?: PolicyFindingScheduleImpactedUserV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cause': value['cause'],
        'name': value['name'],
        'user_id': value['user_id'],
    };
}

