/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExpressionPayloadV2 } from './ExpressionPayloadV2.js';
import {
    ExpressionPayloadV2FromJSON,
    ExpressionPayloadV2FromJSONTyped,
    ExpressionPayloadV2ToJSON,
    ExpressionPayloadV2ToJSONTyped,
} from './ExpressionPayloadV2.js';
import type { PolicyAssignmentRulesPayloadV2 } from './PolicyAssignmentRulesPayloadV2.js';
import {
    PolicyAssignmentRulesPayloadV2FromJSON,
    PolicyAssignmentRulesPayloadV2FromJSONTyped,
    PolicyAssignmentRulesPayloadV2ToJSON,
    PolicyAssignmentRulesPayloadV2ToJSONTyped,
} from './PolicyAssignmentRulesPayloadV2.js';
import type { PolicyScheduleV2 } from './PolicyScheduleV2.js';
import {
    PolicyScheduleV2FromJSON,
    PolicyScheduleV2FromJSONTyped,
    PolicyScheduleV2ToJSON,
    PolicyScheduleV2ToJSONTyped,
} from './PolicyScheduleV2.js';
import type { PolicyPostMortemPayloadV2 } from './PolicyPostMortemPayloadV2.js';
import {
    PolicyPostMortemPayloadV2FromJSON,
    PolicyPostMortemPayloadV2FromJSONTyped,
    PolicyPostMortemPayloadV2ToJSON,
    PolicyPostMortemPayloadV2ToJSONTyped,
} from './PolicyPostMortemPayloadV2.js';
import type { ConditionGroupPayloadV2 } from './ConditionGroupPayloadV2.js';
import {
    ConditionGroupPayloadV2FromJSON,
    ConditionGroupPayloadV2FromJSONTyped,
    ConditionGroupPayloadV2ToJSON,
    ConditionGroupPayloadV2ToJSONTyped,
} from './ConditionGroupPayloadV2.js';
import type { PolicyDebriefPayloadV2 } from './PolicyDebriefPayloadV2.js';
import {
    PolicyDebriefPayloadV2FromJSON,
    PolicyDebriefPayloadV2FromJSONTyped,
    PolicyDebriefPayloadV2ToJSON,
    PolicyDebriefPayloadV2ToJSONTyped,
} from './PolicyDebriefPayloadV2.js';
import type { PolicyFollowUpPayloadV2 } from './PolicyFollowUpPayloadV2.js';
import {
    PolicyFollowUpPayloadV2FromJSON,
    PolicyFollowUpPayloadV2FromJSONTyped,
    PolicyFollowUpPayloadV2ToJSON,
    PolicyFollowUpPayloadV2ToJSONTyped,
} from './PolicyFollowUpPayloadV2.js';
import type { PolicyOnCallReadinessV2 } from './PolicyOnCallReadinessV2.js';
import {
    PolicyOnCallReadinessV2FromJSON,
    PolicyOnCallReadinessV2FromJSONTyped,
    PolicyOnCallReadinessV2ToJSON,
    PolicyOnCallReadinessV2ToJSONTyped,
} from './PolicyOnCallReadinessV2.js';

/**
 * 
 * @export
 * @interface PoliciesCreatePayloadV2
 */
export interface PoliciesCreatePayloadV2 {
    /**
     * 
     */
    assignment_rules?: PolicyAssignmentRulesPayloadV2;
    /**
     * Conditions which determine which resources are in scope for this policy
     */
    conditions: Array<ConditionGroupPayloadV2>;
    /**
     * 
     */
    debrief?: PolicyDebriefPayloadV2;
    /**
     * Human readable description of the policy
     */
    description: string;
    /**
     * The expressions to use in this policy
     */
    expressions?: Array<ExpressionPayloadV2>;
    /**
     * 
     */
    follow_up?: PolicyFollowUpPayloadV2;
    /**
     * Human readable name of the policy
     */
    name: string;
    /**
     * 
     */
    on_call_readiness?: PolicyOnCallReadinessV2;
    /**
     * Type of the policy, specifying what this applies to. Cannot be changed after the policy is created.
     */
    policy_type: PoliciesCreatePayloadV2PolicyTypeEnum;
    /**
     * 
     */
    post_mortem?: PolicyPostMortemPayloadV2;
    /**
     * 
     */
    schedule?: PolicyScheduleV2;
    /**
     * Defaults to enabled on create. Settable on update — there is no separate disable endpoint.
     */
    status?: PoliciesCreatePayloadV2StatusEnum;
}


/**
 * @export
 */
export const PoliciesCreatePayloadV2PolicyTypeEnum = {
    Debrief: 'debrief',
    FollowUp: 'follow_up',
    OnCallReadiness: 'on_call_readiness',
    PostMortem: 'post_mortem',
    Schedule: 'schedule',
    ShiftConflict: 'shift_conflict',
    VacationConflict: 'vacation_conflict',
} as const;
export type PoliciesCreatePayloadV2PolicyTypeEnum = typeof PoliciesCreatePayloadV2PolicyTypeEnum[keyof typeof PoliciesCreatePayloadV2PolicyTypeEnum];

/**
 * @export
 */
export const PoliciesCreatePayloadV2StatusEnum = {
    Enabled: 'enabled',
    Disabled: 'disabled',
} as const;
export type PoliciesCreatePayloadV2StatusEnum = typeof PoliciesCreatePayloadV2StatusEnum[keyof typeof PoliciesCreatePayloadV2StatusEnum];


/**
 * Check if a given object implements the PoliciesCreatePayloadV2 interface.
 */
export function instanceOfPoliciesCreatePayloadV2(value: object): value is PoliciesCreatePayloadV2 {
    if (!('conditions' in value) || value['conditions'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('policy_type' in value) || value['policy_type'] === undefined) return false;
    return true;
}

export function PoliciesCreatePayloadV2FromJSON(json: any): PoliciesCreatePayloadV2 {
    return PoliciesCreatePayloadV2FromJSONTyped(json, false);
}

export function PoliciesCreatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PoliciesCreatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'assignment_rules': json['assignment_rules'] == null ? undefined : PolicyAssignmentRulesPayloadV2FromJSON(json['assignment_rules']),
        'conditions': ((json['conditions'] as Array<any>).map(ConditionGroupPayloadV2FromJSON)),
        'debrief': json['debrief'] == null ? undefined : PolicyDebriefPayloadV2FromJSON(json['debrief']),
        'description': json['description'],
        'expressions': json['expressions'] == null ? undefined : ((json['expressions'] as Array<any>).map(ExpressionPayloadV2FromJSON)),
        'follow_up': json['follow_up'] == null ? undefined : PolicyFollowUpPayloadV2FromJSON(json['follow_up']),
        'name': json['name'],
        'on_call_readiness': json['on_call_readiness'] == null ? undefined : PolicyOnCallReadinessV2FromJSON(json['on_call_readiness']),
        'policy_type': json['policy_type'],
        'post_mortem': json['post_mortem'] == null ? undefined : PolicyPostMortemPayloadV2FromJSON(json['post_mortem']),
        'schedule': json['schedule'] == null ? undefined : PolicyScheduleV2FromJSON(json['schedule']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PoliciesCreatePayloadV2ToJSON(json: any): PoliciesCreatePayloadV2 {
    return PoliciesCreatePayloadV2ToJSONTyped(json, false);
}

export function PoliciesCreatePayloadV2ToJSONTyped(value?: PoliciesCreatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignment_rules': PolicyAssignmentRulesPayloadV2ToJSON(value['assignment_rules']),
        'conditions': ((value['conditions'] as Array<any>).map(ConditionGroupPayloadV2ToJSON)),
        'debrief': PolicyDebriefPayloadV2ToJSON(value['debrief']),
        'description': value['description'],
        'expressions': value['expressions'] == null ? undefined : ((value['expressions'] as Array<any>).map(ExpressionPayloadV2ToJSON)),
        'follow_up': PolicyFollowUpPayloadV2ToJSON(value['follow_up']),
        'name': value['name'],
        'on_call_readiness': PolicyOnCallReadinessV2ToJSON(value['on_call_readiness']),
        'policy_type': value['policy_type'],
        'post_mortem': PolicyPostMortemPayloadV2ToJSON(value['post_mortem']),
        'schedule': PolicyScheduleV2ToJSON(value['schedule']),
        'status': value['status'],
    };
}

