/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { PolicyFindingPostMortemV2 } from './PolicyFindingPostMortemV2.js';
import {
    PolicyFindingPostMortemV2FromJSON,
    PolicyFindingPostMortemV2FromJSONTyped,
    PolicyFindingPostMortemV2ToJSON,
    PolicyFindingPostMortemV2ToJSONTyped,
} from './PolicyFindingPostMortemV2.js';
import type { PolicyFindingDebriefV2 } from './PolicyFindingDebriefV2.js';
import {
    PolicyFindingDebriefV2FromJSON,
    PolicyFindingDebriefV2FromJSONTyped,
    PolicyFindingDebriefV2ToJSON,
    PolicyFindingDebriefV2ToJSONTyped,
} from './PolicyFindingDebriefV2.js';
import type { PolicyFindingDismissalV2 } from './PolicyFindingDismissalV2.js';
import {
    PolicyFindingDismissalV2FromJSON,
    PolicyFindingDismissalV2FromJSONTyped,
    PolicyFindingDismissalV2ToJSON,
    PolicyFindingDismissalV2ToJSONTyped,
} from './PolicyFindingDismissalV2.js';
import type { UserV2 } from './UserV2.js';
import {
    UserV2FromJSON,
    UserV2FromJSONTyped,
    UserV2ToJSON,
    UserV2ToJSONTyped,
} from './UserV2.js';
import type { PolicyFindingOnCallReadinessV2 } from './PolicyFindingOnCallReadinessV2.js';
import {
    PolicyFindingOnCallReadinessV2FromJSON,
    PolicyFindingOnCallReadinessV2FromJSONTyped,
    PolicyFindingOnCallReadinessV2ToJSON,
    PolicyFindingOnCallReadinessV2ToJSONTyped,
} from './PolicyFindingOnCallReadinessV2.js';
import type { PolicyFindingShiftConflictV2 } from './PolicyFindingShiftConflictV2.js';
import {
    PolicyFindingShiftConflictV2FromJSON,
    PolicyFindingShiftConflictV2FromJSONTyped,
    PolicyFindingShiftConflictV2ToJSON,
    PolicyFindingShiftConflictV2ToJSONTyped,
} from './PolicyFindingShiftConflictV2.js';
import type { PolicyFindingScheduleV2 } from './PolicyFindingScheduleV2.js';
import {
    PolicyFindingScheduleV2FromJSON,
    PolicyFindingScheduleV2FromJSONTyped,
    PolicyFindingScheduleV2ToJSON,
    PolicyFindingScheduleV2ToJSONTyped,
} from './PolicyFindingScheduleV2.js';
import type { PolicyFindingFollowUpV2 } from './PolicyFindingFollowUpV2.js';
import {
    PolicyFindingFollowUpV2FromJSON,
    PolicyFindingFollowUpV2FromJSONTyped,
    PolicyFindingFollowUpV2ToJSON,
    PolicyFindingFollowUpV2ToJSONTyped,
} from './PolicyFindingFollowUpV2.js';
import type { PolicyFindingVacationConflictV2 } from './PolicyFindingVacationConflictV2.js';
import {
    PolicyFindingVacationConflictV2FromJSON,
    PolicyFindingVacationConflictV2FromJSONTyped,
    PolicyFindingVacationConflictV2ToJSON,
    PolicyFindingVacationConflictV2ToJSONTyped,
} from './PolicyFindingVacationConflictV2.js';

/**
 * 
 * @export
 * @interface PolicyFindingV2
 */
export interface PolicyFindingV2 {
    /**
     * 
     */
    created_at: Date;
    /**
     * Days outside the policy's due date
     */
    days?: number;
    /**
     * 
     */
    debrief?: PolicyFindingDebriefV2;
    /**
     * 
     */
    dismissal?: PolicyFindingDismissalV2;
    /**
     * When this finding becomes overdue
     */
    due_at?: Date;
    /**
     * 
     */
    follow_up?: PolicyFindingFollowUpV2;
    /**
     * Unique ID of the finding
     */
    id: string;
    /**
     * When this finding was last re-evaluated
     */
    last_checked_at: Date;
    /**
     * 
     */
    on_call_readiness?: PolicyFindingOnCallReadinessV2;
    /**
     * The policy this finding was raised against
     */
    policy_id: string;
    /**
     * Type of the policy this finding was raised against
     */
    policy_type: PolicyFindingV2PolicyTypeEnum;
    /**
     * 
     */
    post_mortem?: PolicyFindingPostMortemV2;
    /**
     * Who is expected to resolve this finding
     */
    responsible_users: Array<UserV2>;
    /**
     * 
     */
    schedule?: PolicyFindingScheduleV2;
    /**
     * 
     */
    shift_conflict?: PolicyFindingShiftConflictV2;
    /**
     * Where this finding is in its lifecycle
     */
    state: PolicyFindingV2StateEnum;
    /**
     * 
     */
    updated_at: Date;
    /**
     * 
     */
    vacation_conflict?: PolicyFindingVacationConflictV2;
}


/**
 * @export
 */
export const PolicyFindingV2PolicyTypeEnum = {
    Debrief: 'debrief',
    FollowUp: 'follow_up',
    OnCallReadiness: 'on_call_readiness',
    PostMortem: 'post_mortem',
    Schedule: 'schedule',
    ShiftConflict: 'shift_conflict',
    VacationConflict: 'vacation_conflict',
} as const;
export type PolicyFindingV2PolicyTypeEnum = typeof PolicyFindingV2PolicyTypeEnum[keyof typeof PolicyFindingV2PolicyTypeEnum];

/**
 * @export
 */
export const PolicyFindingV2StateEnum = {
    Pending: 'pending',
    Active: 'active',
    Resolved: 'resolved',
    Cancelled: 'cancelled',
    Dismissed: 'dismissed',
} as const;
export type PolicyFindingV2StateEnum = typeof PolicyFindingV2StateEnum[keyof typeof PolicyFindingV2StateEnum];


/**
 * Check if a given object implements the PolicyFindingV2 interface.
 */
export function instanceOfPolicyFindingV2(value: object): value is PolicyFindingV2 {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('last_checked_at' in value) || value['last_checked_at'] === undefined) return false;
    if (!('policy_id' in value) || value['policy_id'] === undefined) return false;
    if (!('policy_type' in value) || value['policy_type'] === undefined) return false;
    if (!('responsible_users' in value) || value['responsible_users'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function PolicyFindingV2FromJSON(json: any): PolicyFindingV2 {
    return PolicyFindingV2FromJSONTyped(json, false);
}

export function PolicyFindingV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyFindingV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'days': json['days'] == null ? undefined : json['days'],
        'debrief': json['debrief'] == null ? undefined : PolicyFindingDebriefV2FromJSON(json['debrief']),
        'dismissal': json['dismissal'] == null ? undefined : PolicyFindingDismissalV2FromJSON(json['dismissal']),
        'due_at': json['due_at'] == null ? undefined : (parseDateTime(json['due_at'])),
        'follow_up': json['follow_up'] == null ? undefined : PolicyFindingFollowUpV2FromJSON(json['follow_up']),
        'id': json['id'],
        'last_checked_at': (json['last_checked_at'] == null ? json['last_checked_at'] : parseDateTime(json['last_checked_at'])),
        'on_call_readiness': json['on_call_readiness'] == null ? undefined : PolicyFindingOnCallReadinessV2FromJSON(json['on_call_readiness']),
        'policy_id': json['policy_id'],
        'policy_type': json['policy_type'],
        'post_mortem': json['post_mortem'] == null ? undefined : PolicyFindingPostMortemV2FromJSON(json['post_mortem']),
        'responsible_users': ((json['responsible_users'] as Array<any>).map(UserV2FromJSON)),
        'schedule': json['schedule'] == null ? undefined : PolicyFindingScheduleV2FromJSON(json['schedule']),
        'shift_conflict': json['shift_conflict'] == null ? undefined : PolicyFindingShiftConflictV2FromJSON(json['shift_conflict']),
        'state': json['state'],
        'updated_at': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'vacation_conflict': json['vacation_conflict'] == null ? undefined : PolicyFindingVacationConflictV2FromJSON(json['vacation_conflict']),
    };
}

export function PolicyFindingV2ToJSON(json: any): PolicyFindingV2 {
    return PolicyFindingV2ToJSONTyped(json, false);
}

export function PolicyFindingV2ToJSONTyped(value?: PolicyFindingV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'days': value['days'],
        'debrief': PolicyFindingDebriefV2ToJSON(value['debrief']),
        'dismissal': PolicyFindingDismissalV2ToJSON(value['dismissal']),
        'due_at': value['due_at'] == null ? value['due_at'] : serializeDateTime(value['due_at']),
        'follow_up': PolicyFindingFollowUpV2ToJSON(value['follow_up']),
        'id': value['id'],
        'last_checked_at': value['last_checked_at'] == null ? value['last_checked_at'] : serializeDateTime(value['last_checked_at']),
        'on_call_readiness': PolicyFindingOnCallReadinessV2ToJSON(value['on_call_readiness']),
        'policy_id': value['policy_id'],
        'policy_type': value['policy_type'],
        'post_mortem': PolicyFindingPostMortemV2ToJSON(value['post_mortem']),
        'responsible_users': ((value['responsible_users'] as Array<any>).map(UserV2ToJSON)),
        'schedule': PolicyFindingScheduleV2ToJSON(value['schedule']),
        'shift_conflict': PolicyFindingShiftConflictV2ToJSON(value['shift_conflict']),
        'state': value['state'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
        'vacation_conflict': PolicyFindingVacationConflictV2ToJSON(value['vacation_conflict']),
    };
}

