/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Detects gaps in on-call coverage. Set when policy_type is schedule.
 * @export
 * @interface PolicyScheduleV2
 */
export interface PolicyScheduleV2 {
    /**
     * Evaluate coverage across the whole schedule, or per rotation. Defaults to schedule.
     */
    evaluation_level?: PolicyScheduleV2EvaluationLevelEnum;
    /**
     * 
     */
    requirement_type: PolicyScheduleV2RequirementTypeEnum;
}


/**
 * @export
 */
export const PolicyScheduleV2EvaluationLevelEnum = {
    Schedule: 'schedule',
    Rotation: 'rotation',
} as const;
export type PolicyScheduleV2EvaluationLevelEnum = typeof PolicyScheduleV2EvaluationLevelEnum[keyof typeof PolicyScheduleV2EvaluationLevelEnum];

/**
 * @export
 */
export const PolicyScheduleV2RequirementTypeEnum = {
    Contiguous: 'contiguous',
} as const;
export type PolicyScheduleV2RequirementTypeEnum = typeof PolicyScheduleV2RequirementTypeEnum[keyof typeof PolicyScheduleV2RequirementTypeEnum];


/**
 * Check if a given object implements the PolicyScheduleV2 interface.
 */
export function instanceOfPolicyScheduleV2(value: object): value is PolicyScheduleV2 {
    if (!('requirement_type' in value) || value['requirement_type'] === undefined) return false;
    if (value['requirement_type'] !== 'contiguous') return false;
    
    return true;
}

export function PolicyScheduleV2FromJSON(json: any): PolicyScheduleV2 {
    return PolicyScheduleV2FromJSONTyped(json, false);
}

export function PolicyScheduleV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyScheduleV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluation_level': json['evaluation_level'] == null ? undefined : json['evaluation_level'],
        'requirement_type': json['requirement_type'],
    };
}

export function PolicyScheduleV2ToJSON(json: any): PolicyScheduleV2 {
    return PolicyScheduleV2ToJSONTyped(json, false);
}

export function PolicyScheduleV2ToJSONTyped(value?: PolicyScheduleV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evaluation_level': value['evaluation_level'],
        'requirement_type': value['requirement_type'],
    };
}

