/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PaginationMetaResultV2 } from './PaginationMetaResultV2.js';
import {
    PaginationMetaResultV2FromJSON,
    PaginationMetaResultV2FromJSONTyped,
    PaginationMetaResultV2ToJSON,
    PaginationMetaResultV2ToJSONTyped,
} from './PaginationMetaResultV2.js';
import type { ScheduleSyncTargetResourceV2 } from './ScheduleSyncTargetResourceV2.js';
import {
    ScheduleSyncTargetResourceV2FromJSON,
    ScheduleSyncTargetResourceV2FromJSONTyped,
    ScheduleSyncTargetResourceV2ToJSON,
    ScheduleSyncTargetResourceV2ToJSONTyped,
} from './ScheduleSyncTargetResourceV2.js';

/**
 * 
 * @export
 * @interface ScheduleSyncTargetsListResultV2
 */
export interface ScheduleSyncTargetsListResultV2 {
    /**
     * 
     */
    pagination_meta?: PaginationMetaResultV2;
    /**
     * 
     */
    schedule_sync_targets: Array<ScheduleSyncTargetResourceV2>;
}

/**
 * Check if a given object implements the ScheduleSyncTargetsListResultV2 interface.
 */
export function instanceOfScheduleSyncTargetsListResultV2(value: object): value is ScheduleSyncTargetsListResultV2 {
    if (!('schedule_sync_targets' in value) || value['schedule_sync_targets'] === undefined) return false;
    return true;
}

export function ScheduleSyncTargetsListResultV2FromJSON(json: any): ScheduleSyncTargetsListResultV2 {
    return ScheduleSyncTargetsListResultV2FromJSONTyped(json, false);
}

export function ScheduleSyncTargetsListResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleSyncTargetsListResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination_meta': json['pagination_meta'] == null ? undefined : PaginationMetaResultV2FromJSON(json['pagination_meta']),
        'schedule_sync_targets': ((json['schedule_sync_targets'] as Array<any>).map(ScheduleSyncTargetResourceV2FromJSON)),
    };
}

export function ScheduleSyncTargetsListResultV2ToJSON(json: any): ScheduleSyncTargetsListResultV2 {
    return ScheduleSyncTargetsListResultV2ToJSONTyped(json, false);
}

export function ScheduleSyncTargetsListResultV2ToJSONTyped(value?: ScheduleSyncTargetsListResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination_meta': PaginationMetaResultV2ToJSON(value['pagination_meta']),
        'schedule_sync_targets': ((value['schedule_sync_targets'] as Array<any>).map(ScheduleSyncTargetResourceV2ToJSON)),
    };
}

