/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { UserReferencePayloadV2 } from './UserReferencePayloadV2.js';
import {
    UserReferencePayloadV2FromJSON,
    UserReferencePayloadV2FromJSONTyped,
    UserReferencePayloadV2ToJSON,
    UserReferencePayloadV2ToJSONTyped,
} from './UserReferencePayloadV2.js';

/**
 * 
 * @export
 * @interface SchedulesUpdateOverridePayloadV2
 */
export interface SchedulesUpdateOverridePayloadV2 {
    /**
     * End time of the override
     */
    end_at: Date;
    /**
     * The layer this override applies to
     */
    layer_id: string;
    /**
     * The rotation this override applies to
     */
    rotation_id: string;
    /**
     * Start time of the override
     */
    start_at: Date;
    /**
     * 
     */
    user: UserReferencePayloadV2;
}

/**
 * Check if a given object implements the SchedulesUpdateOverridePayloadV2 interface.
 */
export function instanceOfSchedulesUpdateOverridePayloadV2(value: object): value is SchedulesUpdateOverridePayloadV2 {
    if (!('end_at' in value) || value['end_at'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    if (!('rotation_id' in value) || value['rotation_id'] === undefined) return false;
    if (!('start_at' in value) || value['start_at'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function SchedulesUpdateOverridePayloadV2FromJSON(json: any): SchedulesUpdateOverridePayloadV2 {
    return SchedulesUpdateOverridePayloadV2FromJSONTyped(json, false);
}

export function SchedulesUpdateOverridePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SchedulesUpdateOverridePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'end_at': (json['end_at'] == null ? json['end_at'] : parseDateTime(json['end_at'])),
        'layer_id': json['layer_id'],
        'rotation_id': json['rotation_id'],
        'start_at': (json['start_at'] == null ? json['start_at'] : parseDateTime(json['start_at'])),
        'user': UserReferencePayloadV2FromJSON(json['user']),
    };
}

export function SchedulesUpdateOverridePayloadV2ToJSON(json: any): SchedulesUpdateOverridePayloadV2 {
    return SchedulesUpdateOverridePayloadV2ToJSONTyped(json, false);
}

export function SchedulesUpdateOverridePayloadV2ToJSONTyped(value?: SchedulesUpdateOverridePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_at': value['end_at'] == null ? value['end_at'] : serializeDateTime(value['end_at']),
        'layer_id': value['layer_id'],
        'rotation_id': value['rotation_id'],
        'start_at': value['start_at'] == null ? value['start_at'] : serializeDateTime(value['start_at']),
        'user': UserReferencePayloadV2ToJSON(value['user']),
    };
}

