/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ScheduleV2 } from './ScheduleV2.js';
import {
    ScheduleV2FromJSON,
    ScheduleV2FromJSONTyped,
    ScheduleV2ToJSON,
    ScheduleV2ToJSONTyped,
} from './ScheduleV2.js';

/**
 * 
 * @export
 * @interface SchedulesCreateResultV2
 */
export interface SchedulesCreateResultV2 {
    /**
     * 
     */
    schedule: ScheduleV2;
}

/**
 * Check if a given object implements the SchedulesCreateResultV2 interface.
 */
export function instanceOfSchedulesCreateResultV2(value: object): value is SchedulesCreateResultV2 {
    if (!('schedule' in value) || value['schedule'] === undefined) return false;
    return true;
}

export function SchedulesCreateResultV2FromJSON(json: any): SchedulesCreateResultV2 {
    return SchedulesCreateResultV2FromJSONTyped(json, false);
}

export function SchedulesCreateResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SchedulesCreateResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'schedule': ScheduleV2FromJSON(json['schedule']),
    };
}

export function SchedulesCreateResultV2ToJSON(json: any): SchedulesCreateResultV2 {
    return SchedulesCreateResultV2ToJSONTyped(json, false);
}

export function SchedulesCreateResultV2ToJSONTyped(value?: SchedulesCreateResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schedule': ScheduleV2ToJSON(value['schedule']),
    };
}

