/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ScheduleReplicaSourceV2 } from './ScheduleReplicaSourceV2.js';
import {
    ScheduleReplicaSourceV2FromJSON,
    ScheduleReplicaSourceV2FromJSONTyped,
    ScheduleReplicaSourceV2ToJSON,
    ScheduleReplicaSourceV2ToJSONTyped,
} from './ScheduleReplicaSourceV2.js';

/**
 * 
 * @export
 * @interface ScheduleReplicaCreatePayloadV2
 */
export interface ScheduleReplicaCreatePayloadV2 {
    /**
     * How many days ahead to mirror this schedule into the external provider. Defaults to 14 if not set; maximum 90.
     */
    mirror_window_days?: number;
    /**
     * The ID of a user in the external provider that will be assigned whenever nobody is on-call in the incident.io schedule. External providers typically require someone to always be on-call, so this user fills gaps where incident.io has no one scheduled.
     */
    replica_fallback_user_id: string;
    /**
     * The external provider where this schedule is replicated to
     */
    replica_provider: ScheduleReplicaCreatePayloadV2ReplicaProviderEnum;
    /**
     * The ID of the schedule in the external provider that this replica syncs to. For PagerDuty this is the schedule ID (e.g. PO8107X), for Opsgenie the schedule ID, and for Jira Service Management the schedule ID.
     */
    replica_provider_id: string;
    /**
     * The specific rotation and layer combinations from the schedule to replicate. Each source identifies a single layer within a rotation to sync to the external provider.
     */
    sources: Array<ScheduleReplicaSourceV2>;
}


/**
 * @export
 */
export const ScheduleReplicaCreatePayloadV2ReplicaProviderEnum = {
    Native: 'native',
    Pagerduty: 'pagerduty',
    Opsgenie: 'opsgenie',
    Jsm: 'jsm',
} as const;
export type ScheduleReplicaCreatePayloadV2ReplicaProviderEnum = typeof ScheduleReplicaCreatePayloadV2ReplicaProviderEnum[keyof typeof ScheduleReplicaCreatePayloadV2ReplicaProviderEnum];


/**
 * Check if a given object implements the ScheduleReplicaCreatePayloadV2 interface.
 */
export function instanceOfScheduleReplicaCreatePayloadV2(value: object): value is ScheduleReplicaCreatePayloadV2 {
    if (!('replica_fallback_user_id' in value) || value['replica_fallback_user_id'] === undefined) return false;
    if (!('replica_provider' in value) || value['replica_provider'] === undefined) return false;
    if (!('replica_provider_id' in value) || value['replica_provider_id'] === undefined) return false;
    if (!('sources' in value) || value['sources'] === undefined) return false;
    return true;
}

export function ScheduleReplicaCreatePayloadV2FromJSON(json: any): ScheduleReplicaCreatePayloadV2 {
    return ScheduleReplicaCreatePayloadV2FromJSONTyped(json, false);
}

export function ScheduleReplicaCreatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleReplicaCreatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'mirror_window_days': json['mirror_window_days'] == null ? undefined : json['mirror_window_days'],
        'replica_fallback_user_id': json['replica_fallback_user_id'],
        'replica_provider': json['replica_provider'],
        'replica_provider_id': json['replica_provider_id'],
        'sources': ((json['sources'] as Array<any>).map(ScheduleReplicaSourceV2FromJSON)),
    };
}

export function ScheduleReplicaCreatePayloadV2ToJSON(json: any): ScheduleReplicaCreatePayloadV2 {
    return ScheduleReplicaCreatePayloadV2ToJSONTyped(json, false);
}

export function ScheduleReplicaCreatePayloadV2ToJSONTyped(value?: ScheduleReplicaCreatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mirror_window_days': value['mirror_window_days'],
        'replica_fallback_user_id': value['replica_fallback_user_id'],
        'replica_provider': value['replica_provider'],
        'replica_provider_id': value['replica_provider_id'],
        'sources': ((value['sources'] as Array<any>).map(ScheduleReplicaSourceV2ToJSON)),
    };
}

