/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ScheduleRotationWorkingIntervalCreatePayloadV2
 */
export interface ScheduleRotationWorkingIntervalCreatePayloadV2 {
    /**
     * End time of the interval, in 24hr format
     */
    end_time: string;
    /**
     * Start time of the interval, in 24hr format
     */
    start_time: string;
    /**
     * Weekdays for use with a schedule
     */
    weekday: ScheduleRotationWorkingIntervalCreatePayloadV2WeekdayEnum;
}


/**
 * @export
 */
export const ScheduleRotationWorkingIntervalCreatePayloadV2WeekdayEnum = {
    Monday: 'monday',
    Tuesday: 'tuesday',
    Wednesday: 'wednesday',
    Thursday: 'thursday',
    Friday: 'friday',
    Saturday: 'saturday',
    Sunday: 'sunday',
} as const;
export type ScheduleRotationWorkingIntervalCreatePayloadV2WeekdayEnum = typeof ScheduleRotationWorkingIntervalCreatePayloadV2WeekdayEnum[keyof typeof ScheduleRotationWorkingIntervalCreatePayloadV2WeekdayEnum];


/**
 * Check if a given object implements the ScheduleRotationWorkingIntervalCreatePayloadV2 interface.
 */
export function instanceOfScheduleRotationWorkingIntervalCreatePayloadV2(value: object): value is ScheduleRotationWorkingIntervalCreatePayloadV2 {
    if (!('end_time' in value) || value['end_time'] === undefined) return false;
    if (!('start_time' in value) || value['start_time'] === undefined) return false;
    if (!('weekday' in value) || value['weekday'] === undefined) return false;
    return true;
}

export function ScheduleRotationWorkingIntervalCreatePayloadV2FromJSON(json: any): ScheduleRotationWorkingIntervalCreatePayloadV2 {
    return ScheduleRotationWorkingIntervalCreatePayloadV2FromJSONTyped(json, false);
}

export function ScheduleRotationWorkingIntervalCreatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleRotationWorkingIntervalCreatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'end_time': json['end_time'],
        'start_time': json['start_time'],
        'weekday': json['weekday'],
    };
}

export function ScheduleRotationWorkingIntervalCreatePayloadV2ToJSON(json: any): ScheduleRotationWorkingIntervalCreatePayloadV2 {
    return ScheduleRotationWorkingIntervalCreatePayloadV2ToJSONTyped(json, false);
}

export function ScheduleRotationWorkingIntervalCreatePayloadV2ToJSONTyped(value?: ScheduleRotationWorkingIntervalCreatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_time': value['end_time'],
        'start_time': value['start_time'],
        'weekday': value['weekday'],
    };
}

