/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface ScheduleSlimV2
 */
export interface ScheduleSlimV2 {
    /**
     * 
     */
    created_at: Date;
    /**
     * Unique internal ID of the schedule
     */
    id: string;
    /**
     * Human readable name synced from external provider
     */
    name: string;
    /**
     * IDs of teams that own this schedule
     */
    team_ids?: Array<string>;
    /**
     * Timezone of the schedule, as interpreted at the point of generating the report
     */
    timezone: string;
    /**
     * 
     */
    updated_at: Date;
}

/**
 * Check if a given object implements the ScheduleSlimV2 interface.
 */
export function instanceOfScheduleSlimV2(value: object): value is ScheduleSlimV2 {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function ScheduleSlimV2FromJSON(json: any): ScheduleSlimV2 {
    return ScheduleSlimV2FromJSONTyped(json, false);
}

export function ScheduleSlimV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleSlimV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'id': json['id'],
        'name': json['name'],
        'team_ids': json['team_ids'] == null ? undefined : json['team_ids'],
        'timezone': json['timezone'],
        'updated_at': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function ScheduleSlimV2ToJSON(json: any): ScheduleSlimV2 {
    return ScheduleSlimV2ToJSONTyped(json, false);
}

export function ScheduleSlimV2ToJSONTyped(value?: ScheduleSlimV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'id': value['id'],
        'name': value['name'],
        'team_ids': value['team_ids'],
        'timezone': value['timezone'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
    };
}

