/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ScheduleSyncTargetResourceV2 } from './ScheduleSyncTargetResourceV2.js';
import {
    ScheduleSyncTargetResourceV2FromJSON,
    ScheduleSyncTargetResourceV2FromJSONTyped,
    ScheduleSyncTargetResourceV2ToJSON,
    ScheduleSyncTargetResourceV2ToJSONTyped,
} from './ScheduleSyncTargetResourceV2.js';

/**
 * 
 * @export
 * @interface ScheduleSyncTargetsUpdateResultV2
 */
export interface ScheduleSyncTargetsUpdateResultV2 {
    /**
     * 
     */
    schedule_sync_target: ScheduleSyncTargetResourceV2;
}

/**
 * Check if a given object implements the ScheduleSyncTargetsUpdateResultV2 interface.
 */
export function instanceOfScheduleSyncTargetsUpdateResultV2(value: object): value is ScheduleSyncTargetsUpdateResultV2 {
    if (!('schedule_sync_target' in value) || value['schedule_sync_target'] === undefined) return false;
    return true;
}

export function ScheduleSyncTargetsUpdateResultV2FromJSON(json: any): ScheduleSyncTargetsUpdateResultV2 {
    return ScheduleSyncTargetsUpdateResultV2FromJSONTyped(json, false);
}

export function ScheduleSyncTargetsUpdateResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleSyncTargetsUpdateResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'schedule_sync_target': ScheduleSyncTargetResourceV2FromJSON(json['schedule_sync_target']),
    };
}

export function ScheduleSyncTargetsUpdateResultV2ToJSON(json: any): ScheduleSyncTargetsUpdateResultV2 {
    return ScheduleSyncTargetsUpdateResultV2ToJSONTyped(json, false);
}

export function ScheduleSyncTargetsUpdateResultV2ToJSONTyped(value?: ScheduleSyncTargetsUpdateResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schedule_sync_target': ScheduleSyncTargetResourceV2ToJSON(value['schedule_sync_target']),
    };
}

