/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ScheduleReplicaUserStatusV2
 */
export interface ScheduleReplicaUserStatusV2 {
    /**
     * The corresponding user ID in the external provider (e.g. a PagerDuty user ID). If set, the user has been successfully mapped to an external user and will be included in the replica. If null, the user could not be resolved and syncing may produce errors.
     */
    external_user_id?: string;
    /**
     * The incident.io user ID for a user who appears in the schedule rotation.
     */
    user_id: string;
}

/**
 * Check if a given object implements the ScheduleReplicaUserStatusV2 interface.
 */
export function instanceOfScheduleReplicaUserStatusV2(value: object): value is ScheduleReplicaUserStatusV2 {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function ScheduleReplicaUserStatusV2FromJSON(json: any): ScheduleReplicaUserStatusV2 {
    return ScheduleReplicaUserStatusV2FromJSONTyped(json, false);
}

export function ScheduleReplicaUserStatusV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleReplicaUserStatusV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'external_user_id': json['external_user_id'] == null ? undefined : json['external_user_id'],
        'user_id': json['user_id'],
    };
}

export function ScheduleReplicaUserStatusV2ToJSON(json: any): ScheduleReplicaUserStatusV2 {
    return ScheduleReplicaUserStatusV2ToJSONTyped(json, false);
}

export function ScheduleReplicaUserStatusV2ToJSONTyped(value?: ScheduleReplicaUserStatusV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_user_id': value['external_user_id'],
        'user_id': value['user_id'],
    };
}

