/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ScheduleLayerUpdatePayloadV2
 */
export interface ScheduleLayerUpdatePayloadV2 {
    /**
     * Unique identifier of the layer
     */
    id?: string;
    /**
     * Name of the layer
     */
    name?: string;
}

/**
 * Check if a given object implements the ScheduleLayerUpdatePayloadV2 interface.
 */
export function instanceOfScheduleLayerUpdatePayloadV2(value: object): value is ScheduleLayerUpdatePayloadV2 {
    return true;
}

export function ScheduleLayerUpdatePayloadV2FromJSON(json: any): ScheduleLayerUpdatePayloadV2 {
    return ScheduleLayerUpdatePayloadV2FromJSONTyped(json, false);
}

export function ScheduleLayerUpdatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleLayerUpdatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ScheduleLayerUpdatePayloadV2ToJSON(json: any): ScheduleLayerUpdatePayloadV2 {
    return ScheduleLayerUpdatePayloadV2ToJSONTyped(json, false);
}

export function ScheduleLayerUpdatePayloadV2ToJSONTyped(value?: ScheduleLayerUpdatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

