/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { ScheduleRotationHandoverV2 } from './ScheduleRotationHandoverV2.js';
import {
    ScheduleRotationHandoverV2FromJSON,
    ScheduleRotationHandoverV2FromJSONTyped,
    ScheduleRotationHandoverV2ToJSON,
    ScheduleRotationHandoverV2ToJSONTyped,
} from './ScheduleRotationHandoverV2.js';
import type { ScheduleLayerCreatePayloadV2 } from './ScheduleLayerCreatePayloadV2.js';
import {
    ScheduleLayerCreatePayloadV2FromJSON,
    ScheduleLayerCreatePayloadV2FromJSONTyped,
    ScheduleLayerCreatePayloadV2ToJSON,
    ScheduleLayerCreatePayloadV2ToJSONTyped,
} from './ScheduleLayerCreatePayloadV2.js';
import type { ScheduleRotationWorkingIntervalCreatePayloadV2 } from './ScheduleRotationWorkingIntervalCreatePayloadV2.js';
import {
    ScheduleRotationWorkingIntervalCreatePayloadV2FromJSON,
    ScheduleRotationWorkingIntervalCreatePayloadV2FromJSONTyped,
    ScheduleRotationWorkingIntervalCreatePayloadV2ToJSON,
    ScheduleRotationWorkingIntervalCreatePayloadV2ToJSONTyped,
} from './ScheduleRotationWorkingIntervalCreatePayloadV2.js';
import type { UserReferencePayloadV2 } from './UserReferencePayloadV2.js';
import {
    UserReferencePayloadV2FromJSON,
    UserReferencePayloadV2FromJSONTyped,
    UserReferencePayloadV2ToJSON,
    UserReferencePayloadV2ToJSONTyped,
} from './UserReferencePayloadV2.js';

/**
 * 
 * @export
 * @interface ScheduleRotationCreatePayloadV2
 */
export interface ScheduleRotationCreatePayloadV2 {
    /**
     * When this version of the rotation takes effect. A rotation can appear multiple times in `rotations` with the same `id` to schedule changes ahead of time: each version applies from its `effective_from` until the next version's. Leave it unset on a rotation's first or only version.
     */
    effective_from?: Date;
    /**
     * Determines when shifts change hands and who takes them: the first user in `users` comes on shift at this time, handing over to the next user after each `handovers` interval, cycling through the list — for example, weekly handovers from a Monday 09:00 give week-long shifts that change hands on Mondays at 09:00.
     */
    handover_start_at?: Date;
    /**
     * The cadence shifts hand over on. With more than one entry, the intervals apply in turn — for example, one day then three days produces alternating one-day and three-day shifts.
     */
    handovers?: Array<ScheduleRotationHandoverV2>;
    /**
     * Unique identifier of the rotation
     */
    id?: string;
    /**
     * 
     */
    layers?: Array<ScheduleLayerCreatePayloadV2>;
    /**
     * Name of the rotation
     */
    name: string;
    /**
     * Scheduling algorithm to use for this rotation. 'fair' balances workload by considering handover duration, while 'sequential' uses simple round-robin rotation through users. Only applies when you have asymmetric handovers (e.g., 2 days then 5 days).
     */
    scheduling_mode?: ScheduleRotationCreatePayloadV2SchedulingModeEnum;
    /**
     * The people in the rotation, in the order they take shifts.
     */
    users?: Array<UserReferencePayloadV2>;
    /**
     * DEPRECATED: Use working_intervals instead.
     */
    working_interval?: Array<ScheduleRotationWorkingIntervalCreatePayloadV2>;
    /**
     * 
     */
    working_intervals?: Array<ScheduleRotationWorkingIntervalCreatePayloadV2>;
}


/**
 * @export
 */
export const ScheduleRotationCreatePayloadV2SchedulingModeEnum = {
    Fair: 'fair',
    Sequential: 'sequential',
} as const;
export type ScheduleRotationCreatePayloadV2SchedulingModeEnum = typeof ScheduleRotationCreatePayloadV2SchedulingModeEnum[keyof typeof ScheduleRotationCreatePayloadV2SchedulingModeEnum];


/**
 * Check if a given object implements the ScheduleRotationCreatePayloadV2 interface.
 */
export function instanceOfScheduleRotationCreatePayloadV2(value: object): value is ScheduleRotationCreatePayloadV2 {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ScheduleRotationCreatePayloadV2FromJSON(json: any): ScheduleRotationCreatePayloadV2 {
    return ScheduleRotationCreatePayloadV2FromJSONTyped(json, false);
}

export function ScheduleRotationCreatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleRotationCreatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'effective_from': json['effective_from'] == null ? undefined : (parseDateTime(json['effective_from'])),
        'handover_start_at': json['handover_start_at'] == null ? undefined : (parseDateTime(json['handover_start_at'])),
        'handovers': json['handovers'] == null ? undefined : ((json['handovers'] as Array<any>).map(ScheduleRotationHandoverV2FromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'layers': json['layers'] == null ? undefined : ((json['layers'] as Array<any>).map(ScheduleLayerCreatePayloadV2FromJSON)),
        'name': json['name'],
        'scheduling_mode': json['scheduling_mode'] == null ? undefined : json['scheduling_mode'],
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserReferencePayloadV2FromJSON)),
        'working_interval': json['working_interval'] == null ? undefined : ((json['working_interval'] as Array<any>).map(ScheduleRotationWorkingIntervalCreatePayloadV2FromJSON)),
        'working_intervals': json['working_intervals'] == null ? undefined : ((json['working_intervals'] as Array<any>).map(ScheduleRotationWorkingIntervalCreatePayloadV2FromJSON)),
    };
}

export function ScheduleRotationCreatePayloadV2ToJSON(json: any): ScheduleRotationCreatePayloadV2 {
    return ScheduleRotationCreatePayloadV2ToJSONTyped(json, false);
}

export function ScheduleRotationCreatePayloadV2ToJSONTyped(value?: ScheduleRotationCreatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'effective_from': value['effective_from'] == null ? value['effective_from'] : serializeDateTime(value['effective_from']),
        'handover_start_at': value['handover_start_at'] == null ? value['handover_start_at'] : serializeDateTime(value['handover_start_at']),
        'handovers': value['handovers'] == null ? undefined : ((value['handovers'] as Array<any>).map(ScheduleRotationHandoverV2ToJSON)),
        'id': value['id'],
        'layers': value['layers'] == null ? undefined : ((value['layers'] as Array<any>).map(ScheduleLayerCreatePayloadV2ToJSON)),
        'name': value['name'],
        'scheduling_mode': value['scheduling_mode'],
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserReferencePayloadV2ToJSON)),
        'working_interval': value['working_interval'] == null ? undefined : ((value['working_interval'] as Array<any>).map(ScheduleRotationWorkingIntervalCreatePayloadV2ToJSON)),
        'working_intervals': value['working_intervals'] == null ? undefined : ((value['working_intervals'] as Array<any>).map(ScheduleRotationWorkingIntervalCreatePayloadV2ToJSON)),
    };
}

