/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ScheduleSyncRuleV2 } from './ScheduleSyncRuleV2.js';
import {
    ScheduleSyncRuleV2FromJSON,
    ScheduleSyncRuleV2FromJSONTyped,
    ScheduleSyncRuleV2ToJSON,
    ScheduleSyncRuleV2ToJSONTyped,
} from './ScheduleSyncRuleV2.js';

/**
 * 
 * @export
 * @interface SchedulesCreateScheduleSyncRuleResultV2
 */
export interface SchedulesCreateScheduleSyncRuleResultV2 {
    /**
     * 
     */
    schedule_sync_rule: ScheduleSyncRuleV2;
}

/**
 * Check if a given object implements the SchedulesCreateScheduleSyncRuleResultV2 interface.
 */
export function instanceOfSchedulesCreateScheduleSyncRuleResultV2(value: object): value is SchedulesCreateScheduleSyncRuleResultV2 {
    if (!('schedule_sync_rule' in value) || value['schedule_sync_rule'] === undefined) return false;
    return true;
}

export function SchedulesCreateScheduleSyncRuleResultV2FromJSON(json: any): SchedulesCreateScheduleSyncRuleResultV2 {
    return SchedulesCreateScheduleSyncRuleResultV2FromJSONTyped(json, false);
}

export function SchedulesCreateScheduleSyncRuleResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SchedulesCreateScheduleSyncRuleResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'schedule_sync_rule': ScheduleSyncRuleV2FromJSON(json['schedule_sync_rule']),
    };
}

export function SchedulesCreateScheduleSyncRuleResultV2ToJSON(json: any): SchedulesCreateScheduleSyncRuleResultV2 {
    return SchedulesCreateScheduleSyncRuleResultV2ToJSONTyped(json, false);
}

export function SchedulesCreateScheduleSyncRuleResultV2ToJSONTyped(value?: SchedulesCreateScheduleSyncRuleResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schedule_sync_rule': ScheduleSyncRuleV2ToJSON(value['schedule_sync_rule']),
    };
}

