/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SecretV2 } from './SecretV2.js';
import {
    SecretV2FromJSON,
    SecretV2FromJSONTyped,
    SecretV2ToJSON,
    SecretV2ToJSONTyped,
} from './SecretV2.js';
import type { PaginationMetaResultV2 } from './PaginationMetaResultV2.js';
import {
    PaginationMetaResultV2FromJSON,
    PaginationMetaResultV2FromJSONTyped,
    PaginationMetaResultV2ToJSON,
    PaginationMetaResultV2ToJSONTyped,
} from './PaginationMetaResultV2.js';

/**
 * 
 * @export
 * @interface SecretsListResultV2
 */
export interface SecretsListResultV2 {
    /**
     * 
     */
    pagination_meta?: PaginationMetaResultV2;
    /**
     * 
     */
    secrets: Array<SecretV2>;
}

/**
 * Check if a given object implements the SecretsListResultV2 interface.
 */
export function instanceOfSecretsListResultV2(value: object): value is SecretsListResultV2 {
    if (!('secrets' in value) || value['secrets'] === undefined) return false;
    return true;
}

export function SecretsListResultV2FromJSON(json: any): SecretsListResultV2 {
    return SecretsListResultV2FromJSONTyped(json, false);
}

export function SecretsListResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretsListResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination_meta': json['pagination_meta'] == null ? undefined : PaginationMetaResultV2FromJSON(json['pagination_meta']),
        'secrets': ((json['secrets'] as Array<any>).map(SecretV2FromJSON)),
    };
}

export function SecretsListResultV2ToJSON(json: any): SecretsListResultV2 {
    return SecretsListResultV2ToJSONTyped(json, false);
}

export function SecretsListResultV2ToJSONTyped(value?: SecretsListResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination_meta': PaginationMetaResultV2ToJSON(value['pagination_meta']),
        'secrets': ((value['secrets'] as Array<any>).map(SecretV2ToJSON)),
    };
}

