/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SecretsRotatePayloadV2
 */
export interface SecretsRotatePayloadV2 {
    /**
     * The secret's new plaintext value. It's stored encrypted and never returned by the API.
     */
    value: string;
}

/**
 * Check if a given object implements the SecretsRotatePayloadV2 interface.
 */
export function instanceOfSecretsRotatePayloadV2(value: object): value is SecretsRotatePayloadV2 {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function SecretsRotatePayloadV2FromJSON(json: any): SecretsRotatePayloadV2 {
    return SecretsRotatePayloadV2FromJSONTyped(json, false);
}

export function SecretsRotatePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretsRotatePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function SecretsRotatePayloadV2ToJSON(json: any): SecretsRotatePayloadV2 {
    return SecretsRotatePayloadV2ToJSONTyped(json, false);
}

export function SecretsRotatePayloadV2ToJSONTyped(value?: SecretsRotatePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

