/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { StatusPageIncidentAffectedComponentV2 } from './StatusPageIncidentAffectedComponentV2.js';
import {
    StatusPageIncidentAffectedComponentV2FromJSON,
    StatusPageIncidentAffectedComponentV2FromJSONTyped,
    StatusPageIncidentAffectedComponentV2ToJSON,
    StatusPageIncidentAffectedComponentV2ToJSONTyped,
} from './StatusPageIncidentAffectedComponentV2.js';

/**
 * 
 * @export
 * @interface StatusPagesCreateStatusPageIncidentPayloadV2
 */
export interface StatusPagesCreateStatusPageIncidentPayloadV2 {
    /**
     * An array of mappings from component ID to current component status
     */
    component_statuses?: Array<StatusPageIncidentAffectedComponentV2>;
    /**
     * A unique key to de-duplicate requests. If you send a request with an idempotency_key that was already used, the original response will be returned.
     */
    idempotency_key: string;
    /**
     * Current status for this status page incident
     */
    incident_status: StatusPagesCreateStatusPageIncidentPayloadV2IncidentStatusEnum;
    /**
     * Markdown initial update on this status page incident
     */
    message: string;
    /**
     * A title for the incident
     */
    name: string;
    /**
     * Whether to notify subscribers about this status page incident. This will not work if your status page has more than 1000 subscribers.
     */
    notify_subscribers: boolean;
    /**
     * ID of the status page. You can find this by calling the ListStatusPages endpoint.
     */
    status_page_id: string;
}


/**
 * @export
 */
export const StatusPagesCreateStatusPageIncidentPayloadV2IncidentStatusEnum = {
    Investigating: 'investigating',
    Identified: 'identified',
    Monitoring: 'monitoring',
    Resolved: 'resolved',
} as const;
export type StatusPagesCreateStatusPageIncidentPayloadV2IncidentStatusEnum = typeof StatusPagesCreateStatusPageIncidentPayloadV2IncidentStatusEnum[keyof typeof StatusPagesCreateStatusPageIncidentPayloadV2IncidentStatusEnum];


/**
 * Check if a given object implements the StatusPagesCreateStatusPageIncidentPayloadV2 interface.
 */
export function instanceOfStatusPagesCreateStatusPageIncidentPayloadV2(value: object): value is StatusPagesCreateStatusPageIncidentPayloadV2 {
    if (!('idempotency_key' in value) || value['idempotency_key'] === undefined) return false;
    if (!('incident_status' in value) || value['incident_status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('notify_subscribers' in value) || value['notify_subscribers'] === undefined) return false;
    if (!('status_page_id' in value) || value['status_page_id'] === undefined) return false;
    return true;
}

export function StatusPagesCreateStatusPageIncidentPayloadV2FromJSON(json: any): StatusPagesCreateStatusPageIncidentPayloadV2 {
    return StatusPagesCreateStatusPageIncidentPayloadV2FromJSONTyped(json, false);
}

export function StatusPagesCreateStatusPageIncidentPayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusPagesCreateStatusPageIncidentPayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'component_statuses': json['component_statuses'] == null ? undefined : ((json['component_statuses'] as Array<any>).map(StatusPageIncidentAffectedComponentV2FromJSON)),
        'idempotency_key': json['idempotency_key'],
        'incident_status': json['incident_status'],
        'message': json['message'],
        'name': json['name'],
        'notify_subscribers': json['notify_subscribers'],
        'status_page_id': json['status_page_id'],
    };
}

export function StatusPagesCreateStatusPageIncidentPayloadV2ToJSON(json: any): StatusPagesCreateStatusPageIncidentPayloadV2 {
    return StatusPagesCreateStatusPageIncidentPayloadV2ToJSONTyped(json, false);
}

export function StatusPagesCreateStatusPageIncidentPayloadV2ToJSONTyped(value?: StatusPagesCreateStatusPageIncidentPayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'component_statuses': value['component_statuses'] == null ? undefined : ((value['component_statuses'] as Array<any>).map(StatusPageIncidentAffectedComponentV2ToJSON)),
        'idempotency_key': value['idempotency_key'],
        'incident_status': value['incident_status'],
        'message': value['message'],
        'name': value['name'],
        'notify_subscribers': value['notify_subscribers'],
        'status_page_id': value['status_page_id'],
    };
}

