/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { StatusPageMaintenanceV2 } from './StatusPageMaintenanceV2.js';
import {
    StatusPageMaintenanceV2FromJSON,
    StatusPageMaintenanceV2FromJSONTyped,
    StatusPageMaintenanceV2ToJSON,
    StatusPageMaintenanceV2ToJSONTyped,
} from './StatusPageMaintenanceV2.js';

/**
 * 
 * @export
 * @interface StatusPagesCreateStatusPageMaintenanceResultV2
 */
export interface StatusPagesCreateStatusPageMaintenanceResultV2 {
    /**
     * 
     */
    status_page_maintenance?: StatusPageMaintenanceV2;
}

/**
 * Check if a given object implements the StatusPagesCreateStatusPageMaintenanceResultV2 interface.
 */
export function instanceOfStatusPagesCreateStatusPageMaintenanceResultV2(value: object): value is StatusPagesCreateStatusPageMaintenanceResultV2 {
    return true;
}

export function StatusPagesCreateStatusPageMaintenanceResultV2FromJSON(json: any): StatusPagesCreateStatusPageMaintenanceResultV2 {
    return StatusPagesCreateStatusPageMaintenanceResultV2FromJSONTyped(json, false);
}

export function StatusPagesCreateStatusPageMaintenanceResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusPagesCreateStatusPageMaintenanceResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'status_page_maintenance': json['status_page_maintenance'] == null ? undefined : StatusPageMaintenanceV2FromJSON(json['status_page_maintenance']),
    };
}

export function StatusPagesCreateStatusPageMaintenanceResultV2ToJSON(json: any): StatusPagesCreateStatusPageMaintenanceResultV2 {
    return StatusPagesCreateStatusPageMaintenanceResultV2ToJSONTyped(json, false);
}

export function StatusPagesCreateStatusPageMaintenanceResultV2ToJSONTyped(value?: StatusPagesCreateStatusPageMaintenanceResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_page_maintenance': StatusPageMaintenanceV2ToJSON(value['status_page_maintenance']),
    };
}

