/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { StatusPageComponentAvailabilityV2 } from './StatusPageComponentAvailabilityV2.js';
import {
    StatusPageComponentAvailabilityV2FromJSON,
    StatusPageComponentAvailabilityV2FromJSONTyped,
    StatusPageComponentAvailabilityV2ToJSON,
    StatusPageComponentAvailabilityV2ToJSONTyped,
} from './StatusPageComponentAvailabilityV2.js';

/**
 * 
 * @export
 * @interface StatusPagesShowStatusPageComponentAvailabilityResultV2
 */
export interface StatusPagesShowStatusPageComponentAvailabilityResultV2 {
    /**
     * 
     */
    availability: StatusPageComponentAvailabilityV2;
}

/**
 * Check if a given object implements the StatusPagesShowStatusPageComponentAvailabilityResultV2 interface.
 */
export function instanceOfStatusPagesShowStatusPageComponentAvailabilityResultV2(value: object): value is StatusPagesShowStatusPageComponentAvailabilityResultV2 {
    if (!('availability' in value) || value['availability'] === undefined) return false;
    return true;
}

export function StatusPagesShowStatusPageComponentAvailabilityResultV2FromJSON(json: any): StatusPagesShowStatusPageComponentAvailabilityResultV2 {
    return StatusPagesShowStatusPageComponentAvailabilityResultV2FromJSONTyped(json, false);
}

export function StatusPagesShowStatusPageComponentAvailabilityResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusPagesShowStatusPageComponentAvailabilityResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'availability': StatusPageComponentAvailabilityV2FromJSON(json['availability']),
    };
}

export function StatusPagesShowStatusPageComponentAvailabilityResultV2ToJSON(json: any): StatusPagesShowStatusPageComponentAvailabilityResultV2 {
    return StatusPagesShowStatusPageComponentAvailabilityResultV2ToJSONTyped(json, false);
}

export function StatusPagesShowStatusPageComponentAvailabilityResultV2ToJSONTyped(value?: StatusPagesShowStatusPageComponentAvailabilityResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availability': StatusPageComponentAvailabilityV2ToJSON(value['availability']),
    };
}

