/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { StatusPageIncidentV2 } from './StatusPageIncidentV2.js';
import {
    StatusPageIncidentV2FromJSON,
    StatusPageIncidentV2FromJSONTyped,
    StatusPageIncidentV2ToJSON,
    StatusPageIncidentV2ToJSONTyped,
} from './StatusPageIncidentV2.js';

/**
 * 
 * @export
 * @interface StatusPagesCreateStatusPageIncidentResultV2
 */
export interface StatusPagesCreateStatusPageIncidentResultV2 {
    /**
     * 
     */
    status_page_incident?: StatusPageIncidentV2;
}

/**
 * Check if a given object implements the StatusPagesCreateStatusPageIncidentResultV2 interface.
 */
export function instanceOfStatusPagesCreateStatusPageIncidentResultV2(value: object): value is StatusPagesCreateStatusPageIncidentResultV2 {
    return true;
}

export function StatusPagesCreateStatusPageIncidentResultV2FromJSON(json: any): StatusPagesCreateStatusPageIncidentResultV2 {
    return StatusPagesCreateStatusPageIncidentResultV2FromJSONTyped(json, false);
}

export function StatusPagesCreateStatusPageIncidentResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusPagesCreateStatusPageIncidentResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'status_page_incident': json['status_page_incident'] == null ? undefined : StatusPageIncidentV2FromJSON(json['status_page_incident']),
    };
}

export function StatusPagesCreateStatusPageIncidentResultV2ToJSON(json: any): StatusPagesCreateStatusPageIncidentResultV2 {
    return StatusPagesCreateStatusPageIncidentResultV2ToJSONTyped(json, false);
}

export function StatusPagesCreateStatusPageIncidentResultV2ToJSONTyped(value?: StatusPagesCreateStatusPageIncidentResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_page_incident': StatusPageIncidentV2ToJSON(value['status_page_incident']),
    };
}

