/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { StatusPageLinkedResponseIncidentV1 } from './StatusPageLinkedResponseIncidentV1.js';
import {
    StatusPageLinkedResponseIncidentV1FromJSON,
    StatusPageLinkedResponseIncidentV1FromJSONTyped,
    StatusPageLinkedResponseIncidentV1ToJSON,
    StatusPageLinkedResponseIncidentV1ToJSONTyped,
} from './StatusPageLinkedResponseIncidentV1.js';

/**
 * 
 * @export
 * @interface StatusPagesListResponseIncidentsResultV1
 */
export interface StatusPagesListResponseIncidentsResultV1 {
    /**
     * 
     */
    incidents: Array<StatusPageLinkedResponseIncidentV1>;
}

/**
 * Check if a given object implements the StatusPagesListResponseIncidentsResultV1 interface.
 */
export function instanceOfStatusPagesListResponseIncidentsResultV1(value: object): value is StatusPagesListResponseIncidentsResultV1 {
    if (!('incidents' in value) || value['incidents'] === undefined) return false;
    return true;
}

export function StatusPagesListResponseIncidentsResultV1FromJSON(json: any): StatusPagesListResponseIncidentsResultV1 {
    return StatusPagesListResponseIncidentsResultV1FromJSONTyped(json, false);
}

export function StatusPagesListResponseIncidentsResultV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusPagesListResponseIncidentsResultV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'incidents': ((json['incidents'] as Array<any>).map(StatusPageLinkedResponseIncidentV1FromJSON)),
    };
}

export function StatusPagesListResponseIncidentsResultV1ToJSON(json: any): StatusPagesListResponseIncidentsResultV1 {
    return StatusPagesListResponseIncidentsResultV1ToJSONTyped(json, false);
}

export function StatusPagesListResponseIncidentsResultV1ToJSONTyped(value?: StatusPagesListResponseIncidentsResultV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'incidents': ((value['incidents'] as Array<any>).map(StatusPageLinkedResponseIncidentV1ToJSON)),
    };
}

