/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TelemetryGrafanaUpdateConfigV2 } from './TelemetryGrafanaUpdateConfigV2.js';
import {
    TelemetryGrafanaUpdateConfigV2FromJSON,
    TelemetryGrafanaUpdateConfigV2FromJSONTyped,
    TelemetryGrafanaUpdateConfigV2ToJSON,
    TelemetryGrafanaUpdateConfigV2ToJSONTyped,
} from './TelemetryGrafanaUpdateConfigV2.js';
import type { TelemetryDatadogUpdateConfigV2 } from './TelemetryDatadogUpdateConfigV2.js';
import {
    TelemetryDatadogUpdateConfigV2FromJSON,
    TelemetryDatadogUpdateConfigV2FromJSONTyped,
    TelemetryDatadogUpdateConfigV2ToJSON,
    TelemetryDatadogUpdateConfigV2ToJSONTyped,
} from './TelemetryDatadogUpdateConfigV2.js';

/**
 * 
 * @export
 * @interface TelemetryUpdateDataSourcePayloadV2
 */
export interface TelemetryUpdateDataSourcePayloadV2 {
    /**
     * 
     */
    datadog_config?: TelemetryDatadogUpdateConfigV2;
    /**
     * 
     */
    grafana_config?: TelemetryGrafanaUpdateConfigV2;
    /**
     * Updated display name
     */
    name?: string;
}

/**
 * Check if a given object implements the TelemetryUpdateDataSourcePayloadV2 interface.
 */
export function instanceOfTelemetryUpdateDataSourcePayloadV2(value: object): value is TelemetryUpdateDataSourcePayloadV2 {
    return true;
}

export function TelemetryUpdateDataSourcePayloadV2FromJSON(json: any): TelemetryUpdateDataSourcePayloadV2 {
    return TelemetryUpdateDataSourcePayloadV2FromJSONTyped(json, false);
}

export function TelemetryUpdateDataSourcePayloadV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): TelemetryUpdateDataSourcePayloadV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'datadog_config': json['datadog_config'] == null ? undefined : TelemetryDatadogUpdateConfigV2FromJSON(json['datadog_config']),
        'grafana_config': json['grafana_config'] == null ? undefined : TelemetryGrafanaUpdateConfigV2FromJSON(json['grafana_config']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TelemetryUpdateDataSourcePayloadV2ToJSON(json: any): TelemetryUpdateDataSourcePayloadV2 {
    return TelemetryUpdateDataSourcePayloadV2ToJSONTyped(json, false);
}

export function TelemetryUpdateDataSourcePayloadV2ToJSONTyped(value?: TelemetryUpdateDataSourcePayloadV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datadog_config': TelemetryDatadogUpdateConfigV2ToJSON(value['datadog_config']),
        'grafana_config': TelemetryGrafanaUpdateConfigV2ToJSON(value['grafana_config']),
        'name': value['name'],
    };
}

