/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TriggerSlimV2
 */
export interface TriggerSlimV2 {
    /**
     * Human readable identifier for this trigger
     */
    label: string;
    /**
     * Unique name of the trigger
     */
    name: string;
}

/**
 * Check if a given object implements the TriggerSlimV2 interface.
 */
export function instanceOfTriggerSlimV2(value: object): value is TriggerSlimV2 {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TriggerSlimV2FromJSON(json: any): TriggerSlimV2 {
    return TriggerSlimV2FromJSONTyped(json, false);
}

export function TriggerSlimV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerSlimV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'name': json['name'],
    };
}

export function TriggerSlimV2ToJSON(json: any): TriggerSlimV2 {
    return TriggerSlimV2ToJSONTyped(json, false);
}

export function TriggerSlimV2ToJSONTyped(value?: TriggerSlimV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'name': value['name'],
    };
}

