/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WorkloadMinutesV2
 */
export interface WorkloadMinutesV2 {
    /**
     * Total minutes the user spent on the incident
     */
    minutes_spent_on_incident: number;
    /**
     * Minutes spent during the user's late hours
     */
    minutes_spent_on_incident_in_late_hours: number;
    /**
     * Minutes spent during the user's sleeping hours
     */
    minutes_spent_on_incident_in_sleeping_hours: number;
    /**
     * Minutes spent during the user's working hours
     */
    minutes_spent_on_incident_in_working_hours: number;
}

/**
 * Check if a given object implements the WorkloadMinutesV2 interface.
 */
export function instanceOfWorkloadMinutesV2(value: object): value is WorkloadMinutesV2 {
    if (!('minutes_spent_on_incident' in value) || value['minutes_spent_on_incident'] === undefined) return false;
    if (!('minutes_spent_on_incident_in_late_hours' in value) || value['minutes_spent_on_incident_in_late_hours'] === undefined) return false;
    if (!('minutes_spent_on_incident_in_sleeping_hours' in value) || value['minutes_spent_on_incident_in_sleeping_hours'] === undefined) return false;
    if (!('minutes_spent_on_incident_in_working_hours' in value) || value['minutes_spent_on_incident_in_working_hours'] === undefined) return false;
    return true;
}

export function WorkloadMinutesV2FromJSON(json: any): WorkloadMinutesV2 {
    return WorkloadMinutesV2FromJSONTyped(json, false);
}

export function WorkloadMinutesV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkloadMinutesV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'minutes_spent_on_incident': json['minutes_spent_on_incident'],
        'minutes_spent_on_incident_in_late_hours': json['minutes_spent_on_incident_in_late_hours'],
        'minutes_spent_on_incident_in_sleeping_hours': json['minutes_spent_on_incident_in_sleeping_hours'],
        'minutes_spent_on_incident_in_working_hours': json['minutes_spent_on_incident_in_working_hours'],
    };
}

export function WorkloadMinutesV2ToJSON(json: any): WorkloadMinutesV2 {
    return WorkloadMinutesV2ToJSONTyped(json, false);
}

export function WorkloadMinutesV2ToJSONTyped(value?: WorkloadMinutesV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'minutes_spent_on_incident': value['minutes_spent_on_incident'],
        'minutes_spent_on_incident_in_late_hours': value['minutes_spent_on_incident_in_late_hours'],
        'minutes_spent_on_incident_in_sleeping_hours': value['minutes_spent_on_incident_in_sleeping_hours'],
        'minutes_spent_on_incident_in_working_hours': value['minutes_spent_on_incident_in_working_hours'],
    };
}

