/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { WorkflowSlimV2 } from './WorkflowSlimV2.js';
import {
    WorkflowSlimV2FromJSON,
    WorkflowSlimV2FromJSONTyped,
    WorkflowSlimV2ToJSON,
    WorkflowSlimV2ToJSONTyped,
} from './WorkflowSlimV2.js';

/**
 * 
 * @export
 * @interface WorkflowsListWorkflowsResultV2
 */
export interface WorkflowsListWorkflowsResultV2 {
    /**
     * 
     */
    workflows: Array<WorkflowSlimV2>;
}

/**
 * Check if a given object implements the WorkflowsListWorkflowsResultV2 interface.
 */
export function instanceOfWorkflowsListWorkflowsResultV2(value: object): value is WorkflowsListWorkflowsResultV2 {
    if (!('workflows' in value) || value['workflows'] === undefined) return false;
    return true;
}

export function WorkflowsListWorkflowsResultV2FromJSON(json: any): WorkflowsListWorkflowsResultV2 {
    return WorkflowsListWorkflowsResultV2FromJSONTyped(json, false);
}

export function WorkflowsListWorkflowsResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowsListWorkflowsResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'workflows': ((json['workflows'] as Array<any>).map(WorkflowSlimV2FromJSON)),
    };
}

export function WorkflowsListWorkflowsResultV2ToJSON(json: any): WorkflowsListWorkflowsResultV2 {
    return WorkflowsListWorkflowsResultV2ToJSONTyped(json, false);
}

export function WorkflowsListWorkflowsResultV2ToJSONTyped(value?: WorkflowsListWorkflowsResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflows': ((value['workflows'] as Array<any>).map(WorkflowSlimV2ToJSON)),
    };
}

