/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { StepProgressSlimV2 } from './StepProgressSlimV2.js';
import {
    StepProgressSlimV2FromJSON,
    StepProgressSlimV2FromJSONTyped,
    StepProgressSlimV2ToJSON,
    StepProgressSlimV2ToJSONTyped,
} from './StepProgressSlimV2.js';

/**
 * 
 * @export
 * @interface WorkflowRunSlimV2
 */
export interface WorkflowRunSlimV2 {
    /**
     * If the run was cancelled, this is when
     */
    cancelled_at?: Date;
    /**
     * When the resource was created
     */
    created_at: Date;
    /**
     * When the run was enqueued for execution
     */
    enqueued_at?: Date;
    /**
     * Error produced by the workflow, if it failed
     */
    error?: string;
    /**
     * Unique identifier for the workflow run
     */
    id: string;
    /**
     * If this run was against a specific incident, this is the ID of that incident
     */
    incident_id?: string;
    /**
     * If this run was against a specific incident, this is the reference of that incident
     */
    incident_reference?: string;
    /**
     * Status of each step as it is worked
     */
    progress: Array<StepProgressSlimV2>;
    /**
     * When the run was scheduled for
     */
    scheduled_at: Date;
    /**
     * When the resource was last updated
     */
    updated_at: Date;
    /**
     * Unique identifier for the underlying workflow
     */
    workflow_id: string;
    /**
     * Name of the underlying workflow
     */
    workflow_name?: string;
    /**
     * Unique identifier of the workflow version
     */
    workflow_version_id: string;
    /**
     * Monotonically incrementing version number for the version that ran
     */
    workflow_version_number: number;
}

/**
 * Check if a given object implements the WorkflowRunSlimV2 interface.
 */
export function instanceOfWorkflowRunSlimV2(value: object): value is WorkflowRunSlimV2 {
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('scheduled_at' in value) || value['scheduled_at'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    if (!('workflow_id' in value) || value['workflow_id'] === undefined) return false;
    if (!('workflow_version_id' in value) || value['workflow_version_id'] === undefined) return false;
    if (!('workflow_version_number' in value) || value['workflow_version_number'] === undefined) return false;
    return true;
}

export function WorkflowRunSlimV2FromJSON(json: any): WorkflowRunSlimV2 {
    return WorkflowRunSlimV2FromJSONTyped(json, false);
}

export function WorkflowRunSlimV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRunSlimV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'cancelled_at': json['cancelled_at'] == null ? undefined : (parseDateTime(json['cancelled_at'])),
        'created_at': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'enqueued_at': json['enqueued_at'] == null ? undefined : (parseDateTime(json['enqueued_at'])),
        'error': json['error'] == null ? undefined : json['error'],
        'id': json['id'],
        'incident_id': json['incident_id'] == null ? undefined : json['incident_id'],
        'incident_reference': json['incident_reference'] == null ? undefined : json['incident_reference'],
        'progress': ((json['progress'] as Array<any>).map(StepProgressSlimV2FromJSON)),
        'scheduled_at': (json['scheduled_at'] == null ? json['scheduled_at'] : parseDateTime(json['scheduled_at'])),
        'updated_at': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'workflow_id': json['workflow_id'],
        'workflow_name': json['workflow_name'] == null ? undefined : json['workflow_name'],
        'workflow_version_id': json['workflow_version_id'],
        'workflow_version_number': json['workflow_version_number'],
    };
}

export function WorkflowRunSlimV2ToJSON(json: any): WorkflowRunSlimV2 {
    return WorkflowRunSlimV2ToJSONTyped(json, false);
}

export function WorkflowRunSlimV2ToJSONTyped(value?: WorkflowRunSlimV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cancelled_at': value['cancelled_at'] == null ? value['cancelled_at'] : serializeDateTime(value['cancelled_at']),
        'created_at': value['created_at'] == null ? value['created_at'] : serializeDateTime(value['created_at']),
        'enqueued_at': value['enqueued_at'] == null ? value['enqueued_at'] : serializeDateTime(value['enqueued_at']),
        'error': value['error'],
        'id': value['id'],
        'incident_id': value['incident_id'],
        'incident_reference': value['incident_reference'],
        'progress': ((value['progress'] as Array<any>).map(StepProgressSlimV2ToJSON)),
        'scheduled_at': value['scheduled_at'] == null ? value['scheduled_at'] : serializeDateTime(value['scheduled_at']),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : serializeDateTime(value['updated_at']),
        'workflow_id': value['workflow_id'],
        'workflow_name': value['workflow_name'],
        'workflow_version_id': value['workflow_version_id'],
        'workflow_version_number': value['workflow_version_number'],
    };
}

