/* tslint:disable */
/* eslint-disable */
/**
 * incident.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ManagementMetaV2 } from './ManagementMetaV2.js';
import {
    ManagementMetaV2FromJSON,
    ManagementMetaV2FromJSONTyped,
    ManagementMetaV2ToJSON,
    ManagementMetaV2ToJSONTyped,
} from './ManagementMetaV2.js';
import type { WorkflowV2 } from './WorkflowV2.js';
import {
    WorkflowV2FromJSON,
    WorkflowV2FromJSONTyped,
    WorkflowV2ToJSON,
    WorkflowV2ToJSONTyped,
} from './WorkflowV2.js';

/**
 * 
 * @export
 * @interface WorkflowsCreateWorkflowResultV2
 */
export interface WorkflowsCreateWorkflowResultV2 {
    /**
     * 
     */
    management_meta: ManagementMetaV2;
    /**
     * 
     */
    workflow: WorkflowV2;
}

/**
 * Check if a given object implements the WorkflowsCreateWorkflowResultV2 interface.
 */
export function instanceOfWorkflowsCreateWorkflowResultV2(value: object): value is WorkflowsCreateWorkflowResultV2 {
    if (!('management_meta' in value) || value['management_meta'] === undefined) return false;
    if (!('workflow' in value) || value['workflow'] === undefined) return false;
    return true;
}

export function WorkflowsCreateWorkflowResultV2FromJSON(json: any): WorkflowsCreateWorkflowResultV2 {
    return WorkflowsCreateWorkflowResultV2FromJSONTyped(json, false);
}

export function WorkflowsCreateWorkflowResultV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowsCreateWorkflowResultV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'management_meta': ManagementMetaV2FromJSON(json['management_meta']),
        'workflow': WorkflowV2FromJSON(json['workflow']),
    };
}

export function WorkflowsCreateWorkflowResultV2ToJSON(json: any): WorkflowsCreateWorkflowResultV2 {
    return WorkflowsCreateWorkflowResultV2ToJSONTyped(json, false);
}

export function WorkflowsCreateWorkflowResultV2ToJSONTyped(value?: WorkflowsCreateWorkflowResultV2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'management_meta': ManagementMetaV2ToJSON(value['management_meta']),
        'workflow': WorkflowV2ToJSON(value['workflow']),
    };
}

